package artifact

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"io"
	"net"
	"net/http"
	"os"
	"time"
)

type Client struct {
	HTTP    *http.Client
	TempDir string
}

func NewClient() *Client {
	return &Client{
		HTTP: &http.Client{Transport: NewTransport(), Timeout: 5 * time.Minute},
	}
}

// NewTransport enforces the outbound network boundary for operator URLs.
func NewTransport() *http.Transport {
	transport := http.DefaultTransport.(*http.Transport).Clone()
	transport.Proxy = nil // Repository credentials must not reach environment proxies.
	transport.DialContext = dialRepository
	transport.TLSHandshakeTimeout = 10 * time.Second
	transport.ResponseHeaderTimeout = 30 * time.Second
	return transport
}

func dialRepository(
	ctx context.Context,
	network, address string,
) (net.Conn, error) {
	host, port, err := net.SplitHostPort(address)
	if err != nil {
		return nil, ErrFetch
	}
	ips, err := net.DefaultResolver.LookupIPAddr(ctx, host)
	if err != nil || validateRepositoryIPs(ips) != nil {
		return nil, ErrFetch
	}
	var dialer net.Dialer
	dialer.Timeout = 30 * time.Second
	for _, ip := range ips {
		conn, err := dialer.DialContext(
			ctx,
			network,
			net.JoinHostPort(ip.String(), port),
		)
		if err == nil {
			return conn, nil
		}
	}
	return nil, ErrFetch
}

func validateRepositoryIPs(ips []net.IPAddr) error {
	if len(ips) == 0 {
		return ErrFetch
	}
	for _, ip := range ips {
		if ip.Zone != "" || !AllowedDestinationIP(ip.IP) {
			return ErrFetch
		}
	}
	return nil
}

// AllowedDestinationIP permits private services but excludes local and cloud
// metadata destinations, including Alibaba ECS and AWS's IPv6 endpoint.
func AllowedDestinationIP(ip net.IP) bool {
	return ip.IsGlobalUnicast() && !ip.IsLoopback() &&
		!ip.IsLinkLocalUnicast() && !ip.Equal(net.IPv4(100, 100, 100, 200)) &&
		!ip.Equal(net.ParseIP("fd00:ec2::254"))
}

type Download struct {
	Path   string
	SHA256 string
	Size   int64
}

type Pin struct {
	URL     string `json:"url"`
	Version string `json:"version"`
	SHA256  string `json:"sha256"`
	Size    int64  `json:"size"`
}

// Pins are generated by Fetch: SHA256 is lowercase hex and Size is required.

// Fetch downloads into a private temporary file. The caller owns its removal.
// pin.SHA256 is empty only while resolving a new release pin.
func (c *Client) Fetch(
	ctx context.Context,
	source Repository,
	pin Pin,
) (result Download, err error) {
	response, err := c.request(ctx, source, pin)
	if err != nil {
		return result, err
	}
	var temporaryPath string
	defer func() {
		closeErr := response.Body.Close()
		if closeErr != nil && errors.Is(err, ErrNotFound) {
			// A failed response cleanup is not a missing-package override.
			err = errors.Join(ErrFetch, closeErr)
		} else {
			err = errors.Join(err, closeErr)
		}
		if err != nil && temporaryPath != "" {
			err = errors.Join(err, os.Remove(temporaryPath))
			result = Download{}
		}
	}()
	if response.StatusCode == http.StatusNotFound {
		return result, ErrNotFound
	}
	if response.StatusCode != http.StatusOK ||
		response.ContentLength > MaxDownload {
		return result, ErrFetch
	}
	file, err := os.CreateTemp(c.TempDir, "durpdeploy-artifact-*.zip")
	if err != nil {
		return result, err
	}
	temporaryPath = file.Name()
	defer func() {
		err = errors.Join(err, file.Close())
	}()
	hash := sha256.New()
	size, err := io.Copy(
		io.MultiWriter(file, hash),
		io.LimitReader(response.Body, MaxDownload+1),
	)
	if err != nil {
		if ctx.Err() != nil {
			return result, ctx.Err()
		}
		return result, ErrFetch
	}
	if size > MaxDownload {
		return result, ErrFetch
	}
	digest := hex.EncodeToString(hash.Sum(nil))
	if pin.SHA256 != "" && (digest != pin.SHA256 || size != pin.Size) {
		return result, ErrChecksum
	}
	if err := ValidateZIP(ctx, file.Name()); err != nil {
		return result, err
	}
	return Download{Path: file.Name(), SHA256: digest, Size: size}, nil
}
