package artifact

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"time"
)

type Client struct{ HTTP *http.Client }

func NewClient() *Client {
	transport := http.DefaultTransport.(*http.Transport).Clone()
	transport.Proxy = nil // Repository credentials must not reach environment proxies.
	transport.DialContext = dialRepository
	transport.TLSHandshakeTimeout = 10 * time.Second
	transport.ResponseHeaderTimeout = 30 * time.Second
	return &Client{
		HTTP: &http.Client{Transport: transport, Timeout: 5 * time.Minute},
	}
}

func dialRepository(
	ctx context.Context,
	network, address string,
) (net.Conn, error) {
	host, port, err := net.SplitHostPort(address)
	if err != nil {
		return nil, ErrFetch
	}
	ips, err := net.DefaultResolver.LookupIPAddr(ctx, host)
	if err != nil || len(ips) == 0 {
		return nil, ErrFetch
	}
	for _, ip := range ips {
		if ip.Zone != "" || !ip.IP.IsGlobalUnicast() || ip.IP.IsLoopback() ||
			ip.IP.IsLinkLocalUnicast() {
			return nil, ErrFetch
		}
	}
	var dialer net.Dialer
	dialer.Timeout = 30 * time.Second
	for _, ip := range ips {
		conn, err := dialer.DialContext(
			ctx,
			network,
			net.JoinHostPort(ip.String(), port),
		)
		if err == nil {
			return conn, nil
		}
	}
	return nil, ErrFetch
}

type Download struct {
	Path   string
	SHA256 string
	Size   int64
}

type Pin struct {
	URL     string `json:"url"`
	Version string `json:"version"`
	SHA256  string `json:"sha256"`
	Size    int64  `json:"size"`
}

// Pins are generated by Fetch: SHA256 is lowercase hex and Size is required.

// Fetch downloads into a private temporary file. The caller owns its removal.
// pin.SHA256 is empty only while resolving a new release pin.
func (c *Client) Fetch(
	ctx context.Context,
	source Repository,
	pin Pin,
) (result Download, err error) {
	if err := source.Validate(); err != nil {
		return result, err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, pin.URL, nil)
	if err != nil || validURL(req.URL) != nil {
		return result, ErrInvalid
	}
	origin, err := url.Parse(source.URLTemplate)
	if err != nil || origin.Host != req.URL.Host {
		return result, ErrInvalid
	}
	switch source.AuthType {
	case "bearer":
		req.Header.Set("Authorization", "Bearer "+source.Credential)
	case "basic":
		req.SetBasicAuth(source.Username, source.Credential)
	}
	client := *c.HTTP
	client.CheckRedirect = func(next *http.Request, via []*http.Request) error {
		if len(via) >= 5 || validURL(next.URL) != nil ||
			next.URL.Host != req.URL.Host {
			return ErrFetch
		}
		return nil
	}
	response, err := client.Do(req)
	// Do errors can contain URL paths or server-controlled redirect text.
	if err != nil {
		if ctx.Err() != nil {
			return result, ctx.Err()
		}
		return result, ErrFetch
	}
	var temporaryPath string
	defer func() {
		err = errors.Join(err, response.Body.Close())
		if err != nil && temporaryPath != "" {
			err = errors.Join(err, os.Remove(temporaryPath))
			result = Download{}
		}
	}()
	if response.StatusCode != http.StatusOK ||
		response.ContentLength > MaxDownload {
		return result, ErrFetch
	}
	file, err := os.CreateTemp("", "durpdeploy-artifact-*.zip")
	if err != nil {
		return result, err
	}
	temporaryPath = file.Name()
	defer func() {
		err = errors.Join(err, file.Close())
	}()
	hash := sha256.New()
	size, err := io.Copy(
		io.MultiWriter(file, hash),
		io.LimitReader(response.Body, MaxDownload+1),
	)
	if err != nil {
		if ctx.Err() != nil {
			return result, ctx.Err()
		}
		return result, ErrFetch
	}
	if size > MaxDownload {
		return result, ErrFetch
	}
	digest := hex.EncodeToString(hash.Sum(nil))
	if pin.SHA256 != "" && (digest != pin.SHA256 || size != pin.Size) {
		return result, ErrChecksum
	}
	if err := ValidateZIP(ctx, file.Name()); err != nil {
		return result, err
	}
	return Download{Path: file.Name(), SHA256: digest, Size: size}, nil
}
