#!/usr/bin/env bash
set -euo pipefail
hook=$(realpath "$(dirname "$0")/pre-commit")
root=$(dirname "$(dirname "$hook")")
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
git init -q "$tmp/repo"
cp "$root/go.mod" "$root/go.sum" "$tmp/repo/"
cd "$tmp/repo"
staged_file='staged file.go'

# Given: valid staged Go content, but invalid unrelated/unstaged files.
printf 'package example\n' >"$staged_file"
git add "$staged_file"
printf 'package example\nvar unfinished =\n' >unrelated.go
printf 'package example\nvar unfinished =\n' >"$staged_file"
# When / Then: only the index content is checked, including spaced paths.
bash "$hook"

# Given: the index needs formatting, even though the working tree is clean.
printf 'package example\nfunc example(){println("hello")}\n' >"$staged_file"
git add "$staged_file"
printf 'package example\n' >"$staged_file"
# When / Then: staged bad formatting is rejected.
if bash "$hook" >"$tmp/result" 2>&1; then
	printf 'FAIL: unformatted staged content was accepted\n' >&2
	exit 1
fi

# Given / When / Then: malformed staged Go must also fail closed.
printf 'package example\nvar unfinished =\n' >"$staged_file"
git add "$staged_file"
if bash "$hook" >"$tmp/result" 2>&1; then
	printf 'FAIL: malformed staged content was accepted\n' >&2
	exit 1
fi

# Given: a staged generated Go file, excluded by the repository policy.
printf '// Code generated by test. DO NOT EDIT.\npackage example\nfunc example(){println("hello")}\n' >"$staged_file"
git add "$staged_file"
# When / Then: generated files are skipped.
bash "$hook"

# Given: a shared global hook configuration must survive project installation.
mkdir -p "$tmp/global-hooks" scripts
printf '#!/usr/bin/env bash\nexit 0\n' >"$tmp/global-hooks/pre-commit"
chmod +x "$tmp/global-hooks/pre-commit"
cp "$tmp/global-hooks/pre-commit" "$tmp/global-hook-before"
cp "$hook" scripts/pre-commit
git config core.hooksPath "$tmp/global-hooks"

# When: install the project hook with core.hooksPath configured globally.
make --no-print-directory -f "$root/Makefile" install-hooks

# Then: preserve the global dispatcher and install in the common git directory.
cmp "$tmp/global-hook-before" "$tmp/global-hooks/pre-commit"
common_dir=$(git rev-parse --git-common-dir)
cmp "$hook" "$common_dir/hooks/pre-commit"

# Given: a linked worktree shares repository hooks with its main checkout.
tree=$(git write-tree)
commit=$(git -c user.name=Test -c user.email=test@example.invalid \
    commit-tree "$tree" -m fixture)
git update-ref refs/heads/fixture "$commit"
git worktree add -q -b linked-fixture "$tmp/linked" fixture
mkdir -p "$tmp/linked/scripts"
cp "$hook" "$tmp/linked/scripts/pre-commit"
cd "$tmp/linked"

# When / Then: installation from a linked worktree reaches the same hook.
make --no-print-directory -f "$root/Makefile" install-hooks
cmp "$tmp/global-hook-before" "$tmp/global-hooks/pre-commit"
cmp "$hook" "$(git rev-parse --git-common-dir)/hooks/pre-commit"
printf 'Pre-commit staged-content contract: PASS\n'
