#!/usr/bin/env bash
set -euo pipefail
hook=$(realpath "$(dirname "$0")/pre-commit")
root=$(dirname "$(dirname "$hook")")
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
git init -q "$tmp/repo"
cp "$root/go.mod" "$root/go.sum" "$tmp/repo/"
cd "$tmp/repo"
staged_file='staged file.go'

# Given: valid staged Go content, but invalid unrelated/unstaged files.
printf 'package example\n' >"$staged_file"
git add "$staged_file"
printf 'package example\nvar unfinished =\n' >unrelated.go
printf 'package example\nvar unfinished =\n' >"$staged_file"
# When / Then: only the index content is checked, including spaced paths.
bash "$hook"

# Given: the index needs formatting, even though the working tree is clean.
printf 'package example\nfunc example(){println("hello")}\n' >"$staged_file"
git add "$staged_file"
printf 'package example\n' >"$staged_file"
# When / Then: staged bad formatting is rejected.
if bash "$hook" >"$tmp/result" 2>&1; then
	printf 'FAIL: unformatted staged content was accepted\n' >&2
	exit 1
fi

# Given / When / Then: malformed staged Go must also fail closed.
printf 'package example\nvar unfinished =\n' >"$staged_file"
git add "$staged_file"
if bash "$hook" >"$tmp/result" 2>&1; then
	printf 'FAIL: malformed staged content was accepted\n' >&2
	exit 1
fi

# Given: a staged generated Go file, excluded by the repository policy.
printf '// Code generated by test. DO NOT EDIT.\npackage example\nfunc example(){println("hello")}\n' >"$staged_file"
git add "$staged_file"
# When / Then: generated files are skipped.
bash "$hook"
printf 'Pre-commit staged-content contract: PASS\n'
