// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"
	"database/sql"
)

const addAgentLabel = `-- name: AddAgentLabel :execrows
INSERT INTO agent_labels (agent_id, label)
SELECT ?1, ?2
WHERE NOT EXISTS (SELECT 1 FROM agent_labels WHERE agent_id = ?1 AND label = ?2)
`

type AddAgentLabelParams struct {
	AgentID string `json:"agent_id"`
	Label   string `json:"label"`
}

func (q *Queries) AddAgentLabel(ctx context.Context, arg AddAgentLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addAgentLabel, arg.AgentID, arg.Label)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const assignEnvironmentAgent = `-- name: AssignEnvironmentAgent :execrows
INSERT INTO environment_agent_assignments (environment_id, agent_id)
SELECT ?1, ?2
WHERE NOT EXISTS (SELECT 1 FROM environment_agent_assignments
 WHERE environment_id = ?1)
`

type AssignEnvironmentAgentParams struct {
	EnvironmentID int64  `json:"environment_id"`
	AgentID       string `json:"agent_id"`
}

func (q *Queries) AssignEnvironmentAgent(ctx context.Context, arg AssignEnvironmentAgentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, assignEnvironmentAgent, arg.EnvironmentID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, name, endpoint) VALUES (?, ?, ?) RETURNING id, name, endpoint, status, agent_version, certificate_pem, certificate_fingerprint, encrypted_identity, last_heartbeat_at, revoked_at, created_at, updated_at
`

type CreateAgentParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Endpoint string `json:"endpoint"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent, arg.ID, arg.Name, arg.Endpoint)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Status,
		&i.AgentVersion,
		&i.CertificatePem,
		&i.CertificateFingerprint,
		&i.EncryptedIdentity,
		&i.LastHeartbeatAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentLabel = `-- name: DeleteAgentLabel :execrows
DELETE FROM agent_labels WHERE agent_id = ? AND label = ?
`

type DeleteAgentLabelParams struct {
	AgentID string `json:"agent_id"`
	Label   string `json:"label"`
}

func (q *Queries) DeleteAgentLabel(ctx context.Context, arg DeleteAgentLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAgentLabel, arg.AgentID, arg.Label)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePendingAgent = `-- name: DeletePendingAgent :execrows
DELETE FROM agents WHERE id = ? AND status = 'pending'
AND NOT EXISTS (SELECT 1 FROM agent_pairings WHERE agent_id = agents.id)
`

func (q *Queries) DeletePendingAgent(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingAgent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, endpoint, status, agent_version, certificate_pem, certificate_fingerprint, encrypted_identity, last_heartbeat_at, revoked_at, created_at, updated_at FROM agents WHERE id = ?
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Status,
		&i.AgentVersion,
		&i.CertificatePem,
		&i.CertificateFingerprint,
		&i.EncryptedIdentity,
		&i.LastHeartbeatAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironmentAgentAssignment = `-- name: GetEnvironmentAgentAssignment :one
SELECT environment_id, agent_id, created_at FROM environment_agent_assignments WHERE environment_id = ?
`

func (q *Queries) GetEnvironmentAgentAssignment(ctx context.Context, environmentID int64) (EnvironmentAgentAssignment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentAgentAssignment, environmentID)
	var i EnvironmentAgentAssignment
	err := row.Scan(&i.EnvironmentID, &i.AgentID, &i.CreatedAt)
	return i, err
}

const heartbeatAgent = `-- name: HeartbeatAgent :execrows
UPDATE agents SET last_heartbeat_at = ?1, agent_version = ?2,
    updated_at = ?1
WHERE id = ?3 AND certificate_fingerprint = ?4
  AND status = 'active'
  AND (last_heartbeat_at IS NULL OR last_heartbeat_at <= ?1)
  AND EXISTS (SELECT 1 FROM agent_pairings WHERE agent_id = agents.id AND state = 'paired')
`

type HeartbeatAgentParams struct {
	Now                    sql.NullInt64  `json:"now"`
	AgentVersion           sql.NullString `json:"agent_version"`
	ID                     string         `json:"id"`
	CertificateFingerprint sql.NullString `json:"certificate_fingerprint"`
}

func (q *Queries) HeartbeatAgent(ctx context.Context, arg HeartbeatAgentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, heartbeatAgent,
		arg.Now,
		arg.AgentVersion,
		arg.ID,
		arg.CertificateFingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAgentEnvironments = `-- name: ListAgentEnvironments :many
SELECT e.id, e.name, e.description, e.tags, e.created_at FROM environments e JOIN environment_agent_assignments a ON a.environment_id = e.id
WHERE a.agent_id = ? ORDER BY e.name, e.id
`

func (q *Queries) ListAgentEnvironments(ctx context.Context, agentID string) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, listAgentEnvironments, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentLabels = `-- name: ListAgentLabels :many
SELECT label FROM agent_labels WHERE agent_id = ? ORDER BY label
`

func (q *Queries) ListAgentLabels(ctx context.Context, agentID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAgentLabels, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, endpoint, status, agent_version, certificate_pem, certificate_fingerprint, encrypted_identity, last_heartbeat_at, revoked_at, created_at, updated_at FROM agents ORDER BY name, id
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Endpoint,
			&i.Status,
			&i.AgentVersion,
			&i.CertificatePem,
			&i.CertificateFingerprint,
			&i.EncryptedIdentity,
			&i.LastHeartbeatAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentAgents = `-- name: ListEnvironmentAgents :many
SELECT a.id, a.name, a.endpoint, a.status, a.agent_version, a.certificate_pem, a.certificate_fingerprint, a.encrypted_identity, a.last_heartbeat_at, a.revoked_at, a.created_at, a.updated_at FROM agents a JOIN environment_agent_assignments e ON e.agent_id = a.id
WHERE e.environment_id = ? ORDER BY a.name, a.id
`

func (q *Queries) ListEnvironmentAgents(ctx context.Context, environmentID int64) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironmentAgents, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Endpoint,
			&i.Status,
			&i.AgentVersion,
			&i.CertificatePem,
			&i.CertificateFingerprint,
			&i.EncryptedIdentity,
			&i.LastHeartbeatAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEnvironmentAgentAssignment = `-- name: LockEnvironmentAgentAssignment :execrows
UPDATE environment_agent_assignments SET created_at = created_at
WHERE environment_agent_assignments.environment_id = ?1
  AND environment_agent_assignments.agent_id = ?2
  AND EXISTS (SELECT 1 FROM agents a
      WHERE a.id = environment_agent_assignments.agent_id
        AND a.status = 'active')
  AND EXISTS (SELECT 1 FROM agent_pairings p
      WHERE p.agent_id = environment_agent_assignments.agent_id
        AND p.state = 'paired')
`

type LockEnvironmentAgentAssignmentParams struct {
	EnvironmentID int64  `json:"environment_id"`
	AgentID       string `json:"agent_id"`
}

func (q *Queries) LockEnvironmentAgentAssignment(ctx context.Context, arg LockEnvironmentAgentAssignmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockEnvironmentAgentAssignment, arg.EnvironmentID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAgentStatus = `-- name: SetAgentStatus :one
UPDATE agents SET status = ?1, updated_at = unixepoch(),
    revoked_at = CASE WHEN ?1 = 'revoked' THEN unixepoch() ELSE revoked_at END
WHERE id = ?2 AND status IN ('pending', 'active', 'disabled')
  AND (?1 = 'revoked'
       OR (status IN ('active', 'disabled') AND (?1 = 'active' OR ?1 = 'disabled'))) RETURNING id, name, endpoint, status, agent_version, certificate_pem, certificate_fingerprint, encrypted_identity, last_heartbeat_at, revoked_at, created_at, updated_at
`

type SetAgentStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) SetAgentStatus(ctx context.Context, arg SetAgentStatusParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, setAgentStatus, arg.Status, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Status,
		&i.AgentVersion,
		&i.CertificatePem,
		&i.CertificateFingerprint,
		&i.EncryptedIdentity,
		&i.LastHeartbeatAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unassignEnvironmentAgent = `-- name: UnassignEnvironmentAgent :execrows
DELETE FROM environment_agent_assignments WHERE environment_id = ? AND agent_id = ?
`

type UnassignEnvironmentAgentParams struct {
	EnvironmentID int64  `json:"environment_id"`
	AgentID       string `json:"agent_id"`
}

func (q *Queries) UnassignEnvironmentAgent(ctx context.Context, arg UnassignEnvironmentAgentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unassignEnvironmentAgent, arg.EnvironmentID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents SET name = ?, endpoint = ?, updated_at = unixepoch()
WHERE id = ? AND status IN ('pending', 'active', 'disabled') RETURNING id, name, endpoint, status, agent_version, certificate_pem, certificate_fingerprint, encrypted_identity, last_heartbeat_at, revoked_at, created_at, updated_at
`

type UpdateAgentParams struct {
	Name     string `json:"name"`
	Endpoint string `json:"endpoint"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgent, arg.Name, arg.Endpoint, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Status,
		&i.AgentVersion,
		&i.CertificatePem,
		&i.CertificateFingerprint,
		&i.EncryptedIdentity,
		&i.LastHeartbeatAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
