// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_dispatch.sql

package db

import (
	"context"
	"database/sql"
)

const acknowledgeRemoteDeploymentCancellation = `-- name: AcknowledgeRemoteDeploymentCancellation :execrows
UPDATE remote_deployment_claims SET state = 'cancelled',
    finished_at = ?1, updated_at = ?1
WHERE deployment_id = ?2
  AND agent_id = ?3
  AND claim_token_hash = ?4
  AND state = 'cancel_requested'
`

type AcknowledgeRemoteDeploymentCancellationParams struct {
	Now            sql.NullInt64 `json:"now"`
	DeploymentID   int64         `json:"deployment_id"`
	AgentID        string        `json:"agent_id"`
	ClaimTokenHash []byte        `json:"claim_token_hash"`
}

func (q *Queries) AcknowledgeRemoteDeploymentCancellation(ctx context.Context, arg AcknowledgeRemoteDeploymentCancellationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acknowledgeRemoteDeploymentCancellation,
		arg.Now,
		arg.DeploymentID,
		arg.AgentID,
		arg.ClaimTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimRemoteDeployment = `-- name: ClaimRemoteDeployment :execrows
UPDATE remote_deployment_claims SET state = 'claimed',
    claim_token_hash = ?1,
    ciphertext = ?2,
    claim_expires_at = CAST(?3 AS BIGINT),
    last_heartbeat_at = CAST(?4 AS BIGINT),
    updated_at = CAST(?4 AS BIGINT)
WHERE remote_deployment_claims.deployment_id = ?5
  AND remote_deployment_claims.agent_id = ?6
  AND remote_deployment_claims.state = 'waiting'
  AND remote_deployment_claims.claim_token_hash IS NULL
  AND remote_deployment_claims.started_at IS NULL
  AND CAST(?3 AS BIGINT) >
      CAST(?4 AS BIGINT)
  AND EXISTS (SELECT 1 FROM deployments d
      WHERE d.id = remote_deployment_claims.deployment_id
        AND d.assigned_agent_id = remote_deployment_claims.agent_id
        AND d.status = 'pending')
  AND EXISTS (SELECT 1 FROM agents a
      WHERE a.id = remote_deployment_claims.agent_id AND a.status = 'active'
        AND EXISTS (SELECT 1 FROM agent_pairings p
            WHERE p.agent_id = a.id AND p.state = 'paired'))
  AND NOT EXISTS (SELECT 1 FROM remote_deployment_claims busy
      WHERE busy.agent_id = remote_deployment_claims.agent_id
        AND busy.deployment_id <> remote_deployment_claims.deployment_id
        AND busy.state IN ('claimed', 'started', 'cancel_requested'))
`

type ClaimRemoteDeploymentParams struct {
	ClaimTokenHash []byte         `json:"claim_token_hash"`
	Ciphertext     sql.NullString `json:"ciphertext"`
	ClaimExpiresAt int64          `json:"claim_expires_at"`
	Now            int64          `json:"now"`
	DeploymentID   int64          `json:"deployment_id"`
	AgentID        string         `json:"agent_id"`
}

func (q *Queries) ClaimRemoteDeployment(ctx context.Context, arg ClaimRemoteDeploymentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimRemoteDeployment,
		arg.ClaimTokenHash,
		arg.Ciphertext,
		arg.ClaimExpiresAt,
		arg.Now,
		arg.DeploymentID,
		arg.AgentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createRemoteDeploymentClaim = `-- name: CreateRemoteDeploymentClaim :execrows
INSERT INTO remote_deployment_claims (deployment_id, agent_id)
SELECT d.id, d.assigned_agent_id FROM deployments d
WHERE d.id = ?1 AND d.assigned_agent_id IS NOT NULL
  AND d.status IN ('pending', 'pending_approval')
  AND NOT EXISTS (SELECT 1 FROM remote_deployment_claims c
      WHERE c.deployment_id = d.id)
`

func (q *Queries) CreateRemoteDeploymentClaim(ctx context.Context, deploymentID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, createRemoteDeploymentClaim, deploymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const currentUnixTime = `-- name: CurrentUnixTime :one
SELECT CAST(unixepoch() AS BIGINT) AS now
`

func (q *Queries) CurrentUnixTime(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, currentUnixTime)
	var now int64
	err := row.Scan(&now)
	return now, err
}

const expireRemoteCancellation = `-- name: ExpireRemoteCancellation :execrows
UPDATE remote_deployment_claims SET state = 'cancel_unconfirmed',
    reason = 'cancel_ack_timeout', finished_at = ?1,
    updated_at = ?1
WHERE state = 'cancel_requested'
  AND cancel_requested_at <= ?2
`

type ExpireRemoteCancellationParams struct {
	Now         sql.NullInt64 `json:"now"`
	StaleBefore sql.NullInt64 `json:"stale_before"`
}

func (q *Queries) ExpireRemoteCancellation(ctx context.Context, arg ExpireRemoteCancellationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireRemoteCancellation, arg.Now, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expireRemoteClaims = `-- name: ExpireRemoteClaims :execrows
UPDATE remote_deployment_claims SET state = 'waiting', reason = NULL,
    claim_token_hash = NULL, ciphertext = NULL, claim_expires_at = NULL,
    last_heartbeat_at = NULL, updated_at = ?1
WHERE state = 'claimed' AND started_at IS NULL
  AND claim_expires_at <= ?1
`

func (q *Queries) ExpireRemoteClaims(ctx context.Context, now int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireRemoteClaims, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishRemoteDeployment = `-- name: FinishRemoteDeployment :execrows
UPDATE remote_deployment_claims SET state = ?1,
    reason = ?2, finished_at = ?3,
    updated_at = ?3
WHERE remote_deployment_claims.deployment_id = ?4
  AND remote_deployment_claims.agent_id = ?5
  AND remote_deployment_claims.claim_token_hash = ?6
  AND remote_deployment_claims.state = 'started'
  AND remote_deployment_claims.started_at IS NOT NULL
  AND (?1 = 'succeeded' OR ?1 = 'failed')
  AND EXISTS (SELECT 1 FROM deployments d
      WHERE d.id = remote_deployment_claims.deployment_id
        AND d.assigned_agent_id = remote_deployment_claims.agent_id
        AND d.status IN ('pending', 'running'))
  AND EXISTS (SELECT 1 FROM agents a
      WHERE a.id = remote_deployment_claims.agent_id AND a.status = 'active'
        AND EXISTS (SELECT 1 FROM agent_pairings p
            WHERE p.agent_id = a.id AND p.state = 'paired'))
`

type FinishRemoteDeploymentParams struct {
	State          string         `json:"state"`
	Reason         sql.NullString `json:"reason"`
	Now            sql.NullInt64  `json:"now"`
	DeploymentID   int64          `json:"deployment_id"`
	AgentID        string         `json:"agent_id"`
	ClaimTokenHash []byte         `json:"claim_token_hash"`
}

func (q *Queries) FinishRemoteDeployment(ctx context.Context, arg FinishRemoteDeploymentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishRemoteDeployment,
		arg.State,
		arg.Reason,
		arg.Now,
		arg.DeploymentID,
		arg.AgentID,
		arg.ClaimTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRemoteDeploymentClaim = `-- name: GetRemoteDeploymentClaim :one
SELECT deployment_id, agent_id, state, reason, claim_token_hash, ciphertext, claim_expires_at, last_heartbeat_at, started_at, finished_at, cancel_requested_at, created_at, updated_at FROM remote_deployment_claims WHERE deployment_id = ?
`

func (q *Queries) GetRemoteDeploymentClaim(ctx context.Context, deploymentID int64) (RemoteDeploymentClaim, error) {
	row := q.db.QueryRowContext(ctx, getRemoteDeploymentClaim, deploymentID)
	var i RemoteDeploymentClaim
	err := row.Scan(
		&i.DeploymentID,
		&i.AgentID,
		&i.State,
		&i.Reason,
		&i.ClaimTokenHash,
		&i.Ciphertext,
		&i.ClaimExpiresAt,
		&i.LastHeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatRemoteDeployment = `-- name: HeartbeatRemoteDeployment :execrows
UPDATE remote_deployment_claims SET last_heartbeat_at = ?1,
    updated_at = ?1
WHERE remote_deployment_claims.deployment_id = ?2
  AND remote_deployment_claims.agent_id = ?3
  AND remote_deployment_claims.claim_token_hash = ?4
  AND remote_deployment_claims.state IN ('started', 'cancel_requested')
  AND remote_deployment_claims.last_heartbeat_at <= ?1
  AND EXISTS (SELECT 1 FROM agents a
      WHERE a.id = remote_deployment_claims.agent_id AND a.status = 'active'
        AND EXISTS (SELECT 1 FROM agent_pairings p
            WHERE p.agent_id = a.id AND p.state = 'paired'))
`

type HeartbeatRemoteDeploymentParams struct {
	Now            sql.NullInt64 `json:"now"`
	DeploymentID   int64         `json:"deployment_id"`
	AgentID        string        `json:"agent_id"`
	ClaimTokenHash []byte        `json:"claim_token_hash"`
}

func (q *Queries) HeartbeatRemoteDeployment(ctx context.Context, arg HeartbeatRemoteDeploymentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, heartbeatRemoteDeployment,
		arg.Now,
		arg.DeploymentID,
		arg.AgentID,
		arg.ClaimTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listWaitingRemoteDeploymentClaims = `-- name: ListWaitingRemoteDeploymentClaims :many
SELECT c.deployment_id, c.agent_id, c.state, c.reason, c.claim_token_hash, c.ciphertext, c.claim_expires_at, c.last_heartbeat_at, c.started_at, c.finished_at, c.cancel_requested_at, c.created_at, c.updated_at FROM remote_deployment_claims c
JOIN deployments d ON d.id = c.deployment_id
WHERE c.agent_id = ?1 AND c.state = 'waiting'
  AND d.assigned_agent_id = c.agent_id AND d.status = 'pending'
ORDER BY c.created_at, c.deployment_id
`

func (q *Queries) ListWaitingRemoteDeploymentClaims(ctx context.Context, agentID string) ([]RemoteDeploymentClaim, error) {
	rows, err := q.db.QueryContext(ctx, listWaitingRemoteDeploymentClaims, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteDeploymentClaim
	for rows.Next() {
		var i RemoteDeploymentClaim
		if err := rows.Scan(
			&i.DeploymentID,
			&i.AgentID,
			&i.State,
			&i.Reason,
			&i.ClaimTokenHash,
			&i.Ciphertext,
			&i.ClaimExpiresAt,
			&i.LastHeartbeatAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockClaimAgent = `-- name: LockClaimAgent :execrows
UPDATE agents SET updated_at = updated_at WHERE id = ? AND status = 'active'
`

func (q *Queries) LockClaimAgent(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockClaimAgent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const lockPendingRemoteDeployment = `-- name: LockPendingRemoteDeployment :execrows
UPDATE deployments SET status = status
WHERE id = ?1
  AND assigned_agent_id = ?2
  AND status = 'pending'
`

type LockPendingRemoteDeploymentParams struct {
	DeploymentID int64          `json:"deployment_id"`
	AgentID      sql.NullString `json:"agent_id"`
}

func (q *Queries) LockPendingRemoteDeployment(ctx context.Context, arg LockPendingRemoteDeploymentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockPendingRemoteDeployment, arg.DeploymentID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const lockRemoteDeploymentClaim = `-- name: LockRemoteDeploymentClaim :execrows
UPDATE remote_deployment_claims SET updated_at = updated_at
WHERE remote_deployment_claims.deployment_id = ?1
  AND remote_deployment_claims.agent_id = ?2
  AND remote_deployment_claims.claim_token_hash = ?3
  AND remote_deployment_claims.state IN ('started', 'cancel_requested')
  AND EXISTS (SELECT 1 FROM agents a
      WHERE a.id = remote_deployment_claims.agent_id AND a.status = 'active'
        AND EXISTS (SELECT 1 FROM agent_pairings p
            WHERE p.agent_id = a.id AND p.state = 'paired'))
`

type LockRemoteDeploymentClaimParams struct {
	DeploymentID   int64  `json:"deployment_id"`
	AgentID        string `json:"agent_id"`
	ClaimTokenHash []byte `json:"claim_token_hash"`
}

func (q *Queries) LockRemoteDeploymentClaim(ctx context.Context, arg LockRemoteDeploymentClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockRemoteDeploymentClaim, arg.DeploymentID, arg.AgentID, arg.ClaimTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const lockWaitingRemoteDeploymentClaim = `-- name: LockWaitingRemoteDeploymentClaim :execrows
UPDATE remote_deployment_claims SET updated_at = updated_at
WHERE deployment_id = ?1
  AND agent_id = ?2
  AND state = 'waiting'
  AND claim_token_hash IS NULL
  AND ciphertext IS NULL
`

type LockWaitingRemoteDeploymentClaimParams struct {
	DeploymentID int64  `json:"deployment_id"`
	AgentID      string `json:"agent_id"`
}

func (q *Queries) LockWaitingRemoteDeploymentClaim(ctx context.Context, arg LockWaitingRemoteDeploymentClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockWaitingRemoteDeploymentClaim, arg.DeploymentID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const loseStaleRemoteClaims = `-- name: LoseStaleRemoteClaims :execrows
UPDATE remote_deployment_claims SET state = 'lost',
    reason = 'heartbeat_lost', finished_at = ?1,
    updated_at = ?1
WHERE state = 'started'
  AND last_heartbeat_at <= ?2
`

type LoseStaleRemoteClaimsParams struct {
	Now         sql.NullInt64 `json:"now"`
	StaleBefore sql.NullInt64 `json:"stale_before"`
}

func (q *Queries) LoseStaleRemoteClaims(ctx context.Context, arg LoseStaleRemoteClaimsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, loseStaleRemoteClaims, arg.Now, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requestRemoteDeploymentCancellation = `-- name: RequestRemoteDeploymentCancellation :execrows
UPDATE remote_deployment_claims SET
    state = CASE WHEN started_at IS NULL THEN 'cancelled'
        ELSE 'cancel_requested' END,
    finished_at = CASE WHEN started_at IS NULL THEN ?1 ELSE NULL END,
    cancel_requested_at = ?1, updated_at = ?1
WHERE deployment_id = ?2
  AND state IN ('waiting', 'claimed', 'started')
`

type RequestRemoteDeploymentCancellationParams struct {
	Now          sql.NullInt64 `json:"now"`
	DeploymentID int64         `json:"deployment_id"`
}

func (q *Queries) RequestRemoteDeploymentCancellation(ctx context.Context, arg RequestRemoteDeploymentCancellationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestRemoteDeploymentCancellation, arg.Now, arg.DeploymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startRemoteDeployment = `-- name: StartRemoteDeployment :execrows
UPDATE remote_deployment_claims SET state = 'started',
    started_at = ?1, updated_at = ?1
WHERE remote_deployment_claims.deployment_id = ?2
  AND remote_deployment_claims.agent_id = ?3
  AND remote_deployment_claims.claim_token_hash = ?4
  AND remote_deployment_claims.state = 'claimed'
  AND remote_deployment_claims.started_at IS NULL
  AND remote_deployment_claims.claim_expires_at > ?1
  AND EXISTS (SELECT 1 FROM deployments d
      WHERE d.id = remote_deployment_claims.deployment_id
        AND d.assigned_agent_id = remote_deployment_claims.agent_id
        AND d.status = 'pending')
  AND EXISTS (SELECT 1 FROM agents a
      WHERE a.id = remote_deployment_claims.agent_id AND a.status = 'active'
        AND EXISTS (SELECT 1 FROM agent_pairings p
            WHERE p.agent_id = a.id AND p.state = 'paired'))
`

type StartRemoteDeploymentParams struct {
	Now            sql.NullInt64 `json:"now"`
	DeploymentID   int64         `json:"deployment_id"`
	AgentID        string        `json:"agent_id"`
	ClaimTokenHash []byte        `json:"claim_token_hash"`
}

func (q *Queries) StartRemoteDeployment(ctx context.Context, arg StartRemoteDeploymentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startRemoteDeployment,
		arg.Now,
		arg.DeploymentID,
		arg.AgentID,
		arg.ClaimTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
