// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_dispatch.sql

package db

import (
	"context"
	"database/sql"
)

const acknowledgeDeploymentDispatchCancellation = `-- name: AcknowledgeDeploymentDispatchCancellation :one
UPDATE deployment_dispatches
SET state = 'cancelled',
    finished_at = ?1,
    updated_at = unixepoch()
WHERE deployment_id = ?2
  AND agent_id = ?3
  AND claim_token_hash = ?4
  AND state = 'cancel_requested'
RETURNING deployment_id, mode, pool_id, selector, state, reason, agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at
`

type AcknowledgeDeploymentDispatchCancellationParams struct {
	FinishedAt     sql.NullInt64  `json:"finished_at"`
	DeploymentID   int64          `json:"deployment_id"`
	AgentID        sql.NullString `json:"agent_id"`
	ClaimTokenHash []byte         `json:"claim_token_hash"`
}

func (q *Queries) AcknowledgeDeploymentDispatchCancellation(ctx context.Context, arg AcknowledgeDeploymentDispatchCancellationParams) (DeploymentDispatch, error) {
	row := q.db.QueryRowContext(ctx, acknowledgeDeploymentDispatchCancellation,
		arg.FinishedAt,
		arg.DeploymentID,
		arg.AgentID,
		arg.ClaimTokenHash,
	)
	var i DeploymentDispatch
	err := row.Scan(
		&i.DeploymentID,
		&i.Mode,
		&i.PoolID,
		&i.Selector,
		&i.State,
		&i.Reason,
		&i.AgentID,
		&i.ClaimTokenHash,
		&i.ClaimExpiresAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastHeartbeatAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimDeploymentDispatch = `-- name: ClaimDeploymentDispatch :one
UPDATE deployment_dispatches
SET state = 'claimed',
    agent_id = ?1,
    claim_token_hash = ?2,
    claim_expires_at = ?3,
    last_heartbeat_at = ?4,
    updated_at = unixepoch()
WHERE deployment_id = ?5
  AND state = 'waiting'
  AND EXISTS (
      SELECT 1
      FROM agents AS a
      JOIN agent_pool_memberships AS m ON m.agent_id = a.id
      WHERE a.id = ?1
        AND a.status = 'active'
        AND m.pool_id = deployment_dispatches.pool_id
  )
  AND (
      selector = ''
      OR (
          SELECT COUNT(*)
          FROM agent_tags AS t
          WHERE t.agent_id = ?1
            AND instr(
                ',' || deployment_dispatches.selector || ',',
                ',' || t.tag_key || '=' || t.tag_value || ','
            ) > 0
      ) = length(deployment_dispatches.selector) -
          length(replace(deployment_dispatches.selector, ',', '')) + 1
  )
  AND NOT EXISTS (
      SELECT 1
      FROM deployment_dispatches AS active_dispatch
        WHERE active_dispatch.agent_id = ?1
        AND active_dispatch.state IN ('claimed', 'started', 'cancel_requested')
  )
RETURNING deployment_id, mode, pool_id, selector, state, reason, agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at
`

type ClaimDeploymentDispatchParams struct {
	AgentID         sql.NullString `json:"agent_id"`
	ClaimTokenHash  []byte         `json:"claim_token_hash"`
	ClaimExpiresAt  sql.NullInt64  `json:"claim_expires_at"`
	LastHeartbeatAt sql.NullInt64  `json:"last_heartbeat_at"`
	DeploymentID    int64          `json:"deployment_id"`
}

func (q *Queries) ClaimDeploymentDispatch(ctx context.Context, arg ClaimDeploymentDispatchParams) (DeploymentDispatch, error) {
	row := q.db.QueryRowContext(ctx, claimDeploymentDispatch,
		arg.AgentID,
		arg.ClaimTokenHash,
		arg.ClaimExpiresAt,
		arg.LastHeartbeatAt,
		arg.DeploymentID,
	)
	var i DeploymentDispatch
	err := row.Scan(
		&i.DeploymentID,
		&i.Mode,
		&i.PoolID,
		&i.Selector,
		&i.State,
		&i.Reason,
		&i.AgentID,
		&i.ClaimTokenHash,
		&i.ClaimExpiresAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastHeartbeatAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimOldestEligibleDeployment = `-- name: ClaimOldestEligibleDeployment :one
UPDATE deployment_dispatches
SET state = 'claimed',
    agent_id = ?1,
    claim_token_hash = ?2,
    claim_expires_at = ?3,
    last_heartbeat_at = ?4,
    updated_at = unixepoch()
WHERE deployment_id = (
    SELECT candidate.deployment_id
    FROM deployment_dispatches AS candidate
    JOIN agent_pools AS pool ON pool.id = candidate.pool_id
    JOIN agent_pool_memberships AS membership
        ON membership.pool_id = candidate.pool_id
    JOIN agents AS agent ON agent.id = membership.agent_id
    WHERE candidate.mode = 'remote'
      AND candidate.state = 'waiting'
      AND pool.enabled = 1
      AND agent.id = ?1
      AND agent.status = 'active'
      AND (
          candidate.selector = ''
          OR (
              SELECT COUNT(*)
              FROM agent_tags AS tag
              WHERE tag.agent_id = agent.id
                AND instr(
                    ',' || candidate.selector || ',',
                    ',' || tag.tag_key || '=' || tag.tag_value || ','
                ) > 0
          ) = length(candidate.selector) -
              length(replace(candidate.selector, ',', '')) + 1
      )
      AND NOT EXISTS (
          SELECT 1
          FROM deployment_dispatches AS active_dispatch
          WHERE active_dispatch.agent_id = agent.id
            AND active_dispatch.state IN ('claimed', 'started', 'cancel_requested')
      )
    ORDER BY candidate.created_at ASC, candidate.deployment_id ASC
    LIMIT 1
)
RETURNING deployment_id, mode, pool_id, selector, state, reason, agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at
`

type ClaimOldestEligibleDeploymentParams struct {
	AgentID         sql.NullString `json:"agent_id"`
	ClaimTokenHash  []byte         `json:"claim_token_hash"`
	ClaimExpiresAt  sql.NullInt64  `json:"claim_expires_at"`
	LastHeartbeatAt sql.NullInt64  `json:"last_heartbeat_at"`
}

func (q *Queries) ClaimOldestEligibleDeployment(ctx context.Context, arg ClaimOldestEligibleDeploymentParams) (DeploymentDispatch, error) {
	row := q.db.QueryRowContext(ctx, claimOldestEligibleDeployment,
		arg.AgentID,
		arg.ClaimTokenHash,
		arg.ClaimExpiresAt,
		arg.LastHeartbeatAt,
	)
	var i DeploymentDispatch
	err := row.Scan(
		&i.DeploymentID,
		&i.Mode,
		&i.PoolID,
		&i.Selector,
		&i.State,
		&i.Reason,
		&i.AgentID,
		&i.ClaimTokenHash,
		&i.ClaimExpiresAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastHeartbeatAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentEvent = `-- name: CreateAgentEvent :one
INSERT INTO agent_events (agent_id, deployment_id, event_type, dispatch_state)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
RETURNING id, agent_id, deployment_id, event_type, dispatch_state, details, created_at
`

type CreateAgentEventParams struct {
	AgentID       sql.NullString `json:"agent_id"`
	DeploymentID  sql.NullInt64  `json:"deployment_id"`
	EventType     string         `json:"event_type"`
	DispatchState sql.NullString `json:"dispatch_state"`
}

func (q *Queries) CreateAgentEvent(ctx context.Context, arg CreateAgentEventParams) (AgentEvent, error) {
	row := q.db.QueryRowContext(ctx, createAgentEvent,
		arg.AgentID,
		arg.DeploymentID,
		arg.EventType,
		arg.DispatchState,
	)
	var i AgentEvent
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.DeploymentID,
		&i.EventType,
		&i.DispatchState,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const createAgentEventForDispatch = `-- name: CreateAgentEventForDispatch :one
INSERT INTO agent_events (agent_id, deployment_id, event_type, dispatch_state, details)
SELECT
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
WHERE EXISTS (
    SELECT 1
    FROM deployment_dispatches
    WHERE deployment_id = ?2
      AND agent_id = ?1
      AND claim_token_hash = ?6
      AND state = ?4
)
RETURNING id, agent_id, deployment_id, event_type, dispatch_state, details, created_at
`

type CreateAgentEventForDispatchParams struct {
	AgentID        sql.NullString `json:"agent_id"`
	DeploymentID   sql.NullInt64  `json:"deployment_id"`
	EventType      string         `json:"event_type"`
	CurrentState   sql.NullString `json:"current_state"`
	Details        sql.NullString `json:"details"`
	ClaimTokenHash []byte         `json:"claim_token_hash"`
}

func (q *Queries) CreateAgentEventForDispatch(ctx context.Context, arg CreateAgentEventForDispatchParams) (AgentEvent, error) {
	row := q.db.QueryRowContext(ctx, createAgentEventForDispatch,
		arg.AgentID,
		arg.DeploymentID,
		arg.EventType,
		arg.CurrentState,
		arg.Details,
		arg.ClaimTokenHash,
	)
	var i AgentEvent
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.DeploymentID,
		&i.EventType,
		&i.DispatchState,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const createDeploymentDispatch = `-- name: CreateDeploymentDispatch :one
INSERT INTO deployment_dispatches (deployment_id, mode, pool_id, selector, state, reason)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
ON CONFLICT(deployment_id) DO UPDATE
SET deployment_id = deployment_dispatches.deployment_id
RETURNING deployment_id, mode, pool_id, selector, state, reason, agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at
`

type CreateDeploymentDispatchParams struct {
	DeploymentID int64          `json:"deployment_id"`
	Mode         string         `json:"mode"`
	PoolID       sql.NullInt64  `json:"pool_id"`
	Selector     string         `json:"selector"`
	State        string         `json:"state"`
	Reason       sql.NullString `json:"reason"`
}

func (q *Queries) CreateDeploymentDispatch(ctx context.Context, arg CreateDeploymentDispatchParams) (DeploymentDispatch, error) {
	row := q.db.QueryRowContext(ctx, createDeploymentDispatch,
		arg.DeploymentID,
		arg.Mode,
		arg.PoolID,
		arg.Selector,
		arg.State,
		arg.Reason,
	)
	var i DeploymentDispatch
	err := row.Scan(
		&i.DeploymentID,
		&i.Mode,
		&i.PoolID,
		&i.Selector,
		&i.State,
		&i.Reason,
		&i.AgentID,
		&i.ClaimTokenHash,
		&i.ClaimExpiresAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastHeartbeatAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeploymentPayload = `-- name: CreateDeploymentPayload :one
INSERT INTO deployment_payloads (deployment_id, ciphertext)
VALUES (?1, ?2)
ON CONFLICT(deployment_id) DO UPDATE
SET deployment_id = deployment_payloads.deployment_id
RETURNING deployment_id, ciphertext, created_at
`

type CreateDeploymentPayloadParams struct {
	DeploymentID int64  `json:"deployment_id"`
	Ciphertext   string `json:"ciphertext"`
}

func (q *Queries) CreateDeploymentPayload(ctx context.Context, arg CreateDeploymentPayloadParams) (DeploymentPayload, error) {
	row := q.db.QueryRowContext(ctx, createDeploymentPayload, arg.DeploymentID, arg.Ciphertext)
	var i DeploymentPayload
	err := row.Scan(&i.DeploymentID, &i.Ciphertext, &i.CreatedAt)
	return i, err
}

const createOfflineAgentEvent = `-- name: CreateOfflineAgentEvent :execrows
INSERT INTO agent_events (agent_id, event_type)
SELECT a.id, 'agent_offline'
FROM agents AS a
WHERE a.id = ?1
  AND a.status = 'active'
  AND a.last_heartbeat_at <= ?2
  AND NOT EXISTS (
      SELECT 1
      FROM agent_events AS event
      WHERE event.agent_id = a.id
        AND event.event_type = 'agent_offline'
        AND event.created_at >= a.last_heartbeat_at
  )
`

type CreateOfflineAgentEventParams struct {
	AgentID             string        `json:"agent_id"`
	LastHeartbeatBefore sql.NullInt64 `json:"last_heartbeat_before"`
}

func (q *Queries) CreateOfflineAgentEvent(ctx context.Context, arg CreateOfflineAgentEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createOfflineAgentEvent, arg.AgentID, arg.LastHeartbeatBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expireDeploymentDispatchCancellation = `-- name: ExpireDeploymentDispatchCancellation :execrows
UPDATE deployment_dispatches
SET state = 'cancel_unconfirmed',
    updated_at = unixepoch()
WHERE state = 'cancel_requested'
  AND cancel_requested_at <= ?1
`

func (q *Queries) ExpireDeploymentDispatchCancellation(ctx context.Context, cancelRequestedBefore sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireDeploymentDispatchCancellation, cancelRequestedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDeploymentDispatch = `-- name: GetDeploymentDispatch :one
SELECT deployment_id, mode, pool_id, selector, state, reason, agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at FROM deployment_dispatches WHERE deployment_id = ?
`

func (q *Queries) GetDeploymentDispatch(ctx context.Context, deploymentID int64) (DeploymentDispatch, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentDispatch, deploymentID)
	var i DeploymentDispatch
	err := row.Scan(
		&i.DeploymentID,
		&i.Mode,
		&i.PoolID,
		&i.Selector,
		&i.State,
		&i.Reason,
		&i.AgentID,
		&i.ClaimTokenHash,
		&i.ClaimExpiresAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastHeartbeatAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeploymentPayload = `-- name: GetDeploymentPayload :one
SELECT deployment_id, ciphertext, created_at FROM deployment_payloads WHERE deployment_id = ?
`

func (q *Queries) GetDeploymentPayload(ctx context.Context, deploymentID int64) (DeploymentPayload, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentPayload, deploymentID)
	var i DeploymentPayload
	err := row.Scan(&i.DeploymentID, &i.Ciphertext, &i.CreatedAt)
	return i, err
}

const listExpiredCancellationDeploymentDispatches = `-- name: ListExpiredCancellationDeploymentDispatches :many
SELECT deployment_id, mode, pool_id, selector, state, reason, agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at
FROM deployment_dispatches
WHERE state = 'cancel_requested'
  AND cancel_requested_at <= ?1
`

func (q *Queries) ListExpiredCancellationDeploymentDispatches(ctx context.Context, cancelRequestedBefore sql.NullInt64) ([]DeploymentDispatch, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredCancellationDeploymentDispatches, cancelRequestedBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentDispatch
	for rows.Next() {
		var i DeploymentDispatch
		if err := rows.Scan(
			&i.DeploymentID,
			&i.Mode,
			&i.PoolID,
			&i.Selector,
			&i.State,
			&i.Reason,
			&i.AgentID,
			&i.ClaimTokenHash,
			&i.ClaimExpiresAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.LastHeartbeatAt,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredClaimedDeploymentDispatches = `-- name: ListExpiredClaimedDeploymentDispatches :many
SELECT deployment_id, mode, pool_id, selector, state, reason, agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at
FROM deployment_dispatches
WHERE state = 'claimed'
  AND claim_expires_at <= ?1
`

func (q *Queries) ListExpiredClaimedDeploymentDispatches(ctx context.Context, claimExpiresBefore sql.NullInt64) ([]DeploymentDispatch, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredClaimedDeploymentDispatches, claimExpiresBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentDispatch
	for rows.Next() {
		var i DeploymentDispatch
		if err := rows.Scan(
			&i.DeploymentID,
			&i.Mode,
			&i.PoolID,
			&i.Selector,
			&i.State,
			&i.Reason,
			&i.AgentID,
			&i.ClaimTokenHash,
			&i.ClaimExpiresAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.LastHeartbeatAt,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLostStartedDeploymentDispatches = `-- name: ListLostStartedDeploymentDispatches :many
SELECT deployment_id, mode, pool_id, selector, state, reason, agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at
FROM deployment_dispatches
WHERE state = 'started'
  AND last_heartbeat_at <= ?1
`

func (q *Queries) ListLostStartedDeploymentDispatches(ctx context.Context, lastHeartbeatBefore sql.NullInt64) ([]DeploymentDispatch, error) {
	rows, err := q.db.QueryContext(ctx, listLostStartedDeploymentDispatches, lastHeartbeatBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentDispatch
	for rows.Next() {
		var i DeploymentDispatch
		if err := rows.Scan(
			&i.DeploymentID,
			&i.Mode,
			&i.PoolID,
			&i.Selector,
			&i.State,
			&i.Reason,
			&i.AgentID,
			&i.ClaimTokenHash,
			&i.ClaimExpiresAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.LastHeartbeatAt,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfflineAgentIDs = `-- name: ListOfflineAgentIDs :many
SELECT id
FROM agents
WHERE status = 'active'
  AND last_heartbeat_at <= ?1
`

func (q *Queries) ListOfflineAgentIDs(ctx context.Context, lastHeartbeatBefore sql.NullInt64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listOfflineAgentIDs, lastHeartbeatBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reclaimExpiredClaimedDeploymentDispatch = `-- name: ReclaimExpiredClaimedDeploymentDispatch :one
UPDATE deployment_dispatches
SET state = 'waiting',
    agent_id = NULL,
    claim_token_hash = NULL,
    claim_expires_at = NULL,
    last_heartbeat_at = NULL,
    updated_at = ?1
WHERE deployment_id = ?2
  AND agent_id = ?3
  AND claim_token_hash = ?4
  AND state = 'claimed'
  AND claim_expires_at <= ?5
RETURNING deployment_id, mode, pool_id, selector, state, reason, agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at
`

type ReclaimExpiredClaimedDeploymentDispatchParams struct {
	UpdatedAt          int64          `json:"updated_at"`
	DeploymentID       int64          `json:"deployment_id"`
	AgentID            sql.NullString `json:"agent_id"`
	ClaimTokenHash     []byte         `json:"claim_token_hash"`
	ClaimExpiresBefore sql.NullInt64  `json:"claim_expires_before"`
}

func (q *Queries) ReclaimExpiredClaimedDeploymentDispatch(ctx context.Context, arg ReclaimExpiredClaimedDeploymentDispatchParams) (DeploymentDispatch, error) {
	row := q.db.QueryRowContext(ctx, reclaimExpiredClaimedDeploymentDispatch,
		arg.UpdatedAt,
		arg.DeploymentID,
		arg.AgentID,
		arg.ClaimTokenHash,
		arg.ClaimExpiresBefore,
	)
	var i DeploymentDispatch
	err := row.Scan(
		&i.DeploymentID,
		&i.Mode,
		&i.PoolID,
		&i.Selector,
		&i.State,
		&i.Reason,
		&i.AgentID,
		&i.ClaimTokenHash,
		&i.ClaimExpiresAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastHeartbeatAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renewDeploymentDispatchClaim = `-- name: RenewDeploymentDispatchClaim :one
UPDATE deployment_dispatches
SET claim_expires_at = ?1,
    last_heartbeat_at = ?2,
    updated_at = unixepoch()
WHERE deployment_id = ?3
  AND agent_id = ?4
  AND claim_token_hash = ?5
  AND state = ?6
RETURNING deployment_id, mode, pool_id, selector, state, reason, agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at
`

type RenewDeploymentDispatchClaimParams struct {
	ClaimExpiresAt  sql.NullInt64  `json:"claim_expires_at"`
	LastHeartbeatAt sql.NullInt64  `json:"last_heartbeat_at"`
	DeploymentID    int64          `json:"deployment_id"`
	AgentID         sql.NullString `json:"agent_id"`
	ClaimTokenHash  []byte         `json:"claim_token_hash"`
	CurrentState    string         `json:"current_state"`
}

func (q *Queries) RenewDeploymentDispatchClaim(ctx context.Context, arg RenewDeploymentDispatchClaimParams) (DeploymentDispatch, error) {
	row := q.db.QueryRowContext(ctx, renewDeploymentDispatchClaim,
		arg.ClaimExpiresAt,
		arg.LastHeartbeatAt,
		arg.DeploymentID,
		arg.AgentID,
		arg.ClaimTokenHash,
		arg.CurrentState,
	)
	var i DeploymentDispatch
	err := row.Scan(
		&i.DeploymentID,
		&i.Mode,
		&i.PoolID,
		&i.Selector,
		&i.State,
		&i.Reason,
		&i.AgentID,
		&i.ClaimTokenHash,
		&i.ClaimExpiresAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastHeartbeatAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requestDeploymentDispatchCancellation = `-- name: RequestDeploymentDispatchCancellation :one
UPDATE deployment_dispatches
SET state = 'cancel_requested',
    cancel_requested_at = ?1,
    updated_at = unixepoch()
WHERE deployment_id = ?2
  AND state = ?3
RETURNING deployment_id, mode, pool_id, selector, state, reason, agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at
`

type RequestDeploymentDispatchCancellationParams struct {
	CancelRequestedAt sql.NullInt64 `json:"cancel_requested_at"`
	DeploymentID      int64         `json:"deployment_id"`
	CurrentState      string        `json:"current_state"`
}

func (q *Queries) RequestDeploymentDispatchCancellation(ctx context.Context, arg RequestDeploymentDispatchCancellationParams) (DeploymentDispatch, error) {
	row := q.db.QueryRowContext(ctx, requestDeploymentDispatchCancellation, arg.CancelRequestedAt, arg.DeploymentID, arg.CurrentState)
	var i DeploymentDispatch
	err := row.Scan(
		&i.DeploymentID,
		&i.Mode,
		&i.PoolID,
		&i.Selector,
		&i.State,
		&i.Reason,
		&i.AgentID,
		&i.ClaimTokenHash,
		&i.ClaimExpiresAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastHeartbeatAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startClaimedDeploymentDispatch = `-- name: StartClaimedDeploymentDispatch :one
UPDATE deployment_dispatches
SET state = 'started',
    started_at = ?1,
    claim_expires_at = NULL,
    last_heartbeat_at = ?2,
    updated_at = unixepoch()
WHERE deployment_id = ?3
  AND agent_id = ?4
  AND claim_token_hash = ?5
  AND state = 'claimed'
RETURNING deployment_id, mode, pool_id, selector, state, reason, agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at
`

type StartClaimedDeploymentDispatchParams struct {
	StartedAt       sql.NullInt64  `json:"started_at"`
	LastHeartbeatAt sql.NullInt64  `json:"last_heartbeat_at"`
	DeploymentID    int64          `json:"deployment_id"`
	AgentID         sql.NullString `json:"agent_id"`
	ClaimTokenHash  []byte         `json:"claim_token_hash"`
}

func (q *Queries) StartClaimedDeploymentDispatch(ctx context.Context, arg StartClaimedDeploymentDispatchParams) (DeploymentDispatch, error) {
	row := q.db.QueryRowContext(ctx, startClaimedDeploymentDispatch,
		arg.StartedAt,
		arg.LastHeartbeatAt,
		arg.DeploymentID,
		arg.AgentID,
		arg.ClaimTokenHash,
	)
	var i DeploymentDispatch
	err := row.Scan(
		&i.DeploymentID,
		&i.Mode,
		&i.PoolID,
		&i.Selector,
		&i.State,
		&i.Reason,
		&i.AgentID,
		&i.ClaimTokenHash,
		&i.ClaimExpiresAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastHeartbeatAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionDeploymentDispatch = `-- name: TransitionDeploymentDispatch :one
UPDATE deployment_dispatches
SET state = ?1,
    reason = ?2,
    finished_at = ?3,
    updated_at = unixepoch()
WHERE deployment_id = ?4
  AND agent_id = ?5
  AND claim_token_hash = ?6
   AND state = ?7
RETURNING deployment_id, mode, pool_id, selector, state, reason, agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at
`

type TransitionDeploymentDispatchParams struct {
	NextState      string         `json:"next_state"`
	Reason         sql.NullString `json:"reason"`
	FinishedAt     sql.NullInt64  `json:"finished_at"`
	DeploymentID   int64          `json:"deployment_id"`
	AgentID        sql.NullString `json:"agent_id"`
	ClaimTokenHash []byte         `json:"claim_token_hash"`
	CurrentState   string         `json:"current_state"`
}

func (q *Queries) TransitionDeploymentDispatch(ctx context.Context, arg TransitionDeploymentDispatchParams) (DeploymentDispatch, error) {
	row := q.db.QueryRowContext(ctx, transitionDeploymentDispatch,
		arg.NextState,
		arg.Reason,
		arg.FinishedAt,
		arg.DeploymentID,
		arg.AgentID,
		arg.ClaimTokenHash,
		arg.CurrentState,
	)
	var i DeploymentDispatch
	err := row.Scan(
		&i.DeploymentID,
		&i.Mode,
		&i.PoolID,
		&i.Selector,
		&i.State,
		&i.Reason,
		&i.AgentID,
		&i.ClaimTokenHash,
		&i.ClaimExpiresAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastHeartbeatAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
