// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_deletion.sql

package db

import (
	"context"
	"database/sql"
)

const clearAgentDispatchPayloads = `-- name: ClearAgentDispatchPayloads :exec
UPDATE deployment_dispatches SET ciphertext = NULL
WHERE EXISTS (SELECT 1 FROM deployment_step_attempts a
  WHERE a.deployment_id = deployment_dispatches.deployment_id
    AND a.step_index = deployment_dispatches.step_index
    AND a.attempt = deployment_dispatches.attempt AND a.agent_id = ?)
`

func (q *Queries) ClearAgentDispatchPayloads(ctx context.Context, agentID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, clearAgentDispatchPayloads, agentID)
	return err
}

const countAgentActiveDeploymentReferences = `-- name: CountAgentActiveDeploymentReferences :one
SELECT COUNT(*) FROM deployments d
WHERE (d.status NOT IN ('succeeded', 'failed', 'cancelled', 'rejected', 'expired', 'cleanup_unconfirmed')
  OR (d.status = 'cleanup_unconfirmed'
    AND (d.container_namespace IS NOT NULL
      OR (NOT EXISTS (SELECT 1 FROM remote_step_runs s WHERE s.deployment_id = d.id AND s.cleanup_confirmed_at IS NOT NULL)
      AND NOT EXISTS (SELECT 1 FROM remote_deployment_claims c WHERE c.deployment_id = d.id AND c.cleanup_confirmed_at IS NOT NULL)
      AND d.cleanup_confirmed_at IS NULL)
      OR EXISTS (SELECT 1 FROM remote_step_runs s WHERE s.deployment_id = d.id AND s.state = 'cleanup_unconfirmed' AND s.cleanup_confirmed_at IS NULL)
      OR EXISTS (SELECT 1 FROM remote_deployment_claims c WHERE c.deployment_id = d.id AND c.state = 'cleanup_unconfirmed' AND c.cleanup_confirmed_at IS NULL))))
  AND (d.assigned_agent_id = ?1
    OR EXISTS (SELECT 1 FROM remote_step_runs s WHERE s.deployment_id = d.id AND s.agent_id = ?1)
    OR EXISTS (SELECT 1 FROM remote_deployment_claims c WHERE c.deployment_id = d.id AND c.agent_id = ?1)
    OR EXISTS (SELECT 1 FROM deployment_step_attempts a WHERE a.deployment_id = d.id AND a.agent_id = ?1))
`

func (q *Queries) CountAgentActiveDeploymentReferences(ctx context.Context, agentID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentActiveDeploymentReferences, agentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAgentDeletionBlockers = `-- name: CountAgentDeletionBlockers :one
SELECT
  (SELECT COUNT(*) FROM remote_step_runs s WHERE s.agent_id = ?1
    AND (s.state IN ('claimed', 'started', 'cancel_requested', 'lost', 'cancel_unconfirmed')
      OR (s.state = 'cleanup_unconfirmed' AND s.cleanup_confirmed_at IS NULL)
      OR COALESCE(s.log_buffer_ciphertext, '') <> ''))
  + (SELECT COUNT(*) FROM remote_deployment_claims c WHERE c.agent_id = ?1
    AND (c.state IN ('claimed', 'started', 'cancel_requested', 'lost', 'cancel_unconfirmed')
      OR (c.state = 'cleanup_unconfirmed' AND c.cleanup_confirmed_at IS NULL)
      OR COALESCE(c.log_buffer_ciphertext, '') <> ''))
  + (SELECT COUNT(*) FROM deployment_step_attempts a WHERE a.agent_id = ?1
    AND a.state IN ('claimed', 'started', 'cancel_requested', 'lost', 'cancel_uncertain'))
`

func (q *Queries) CountAgentDeletionBlockers(ctx context.Context, agentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentDeletionBlockers, agentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAgentLabels = `-- name: DeleteAgentLabels :exec
DELETE FROM agent_labels WHERE agent_id = ?
`

func (q *Queries) DeleteAgentLabels(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentLabels, agentID)
	return err
}

const deleteAgentPairing = `-- name: DeleteAgentPairing :exec
DELETE FROM agent_pairings WHERE agent_id = ?
`

func (q *Queries) DeleteAgentPairing(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentPairing, agentID)
	return err
}

const deleteAgentRegistration = `-- name: DeleteAgentRegistration :execrows
DELETE FROM agents WHERE id = ?
`

func (q *Queries) DeleteAgentRegistration(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAgentRegistration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAgentRemoteClaims = `-- name: DeleteAgentRemoteClaims :exec
DELETE FROM remote_deployment_claims WHERE agent_id = ?
`

func (q *Queries) DeleteAgentRemoteClaims(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentRemoteClaims, agentID)
	return err
}

const deleteAgentRemoteLogSequences = `-- name: DeleteAgentRemoteLogSequences :exec
DELETE FROM remote_step_log_sequences WHERE agent_id = ?
`

func (q *Queries) DeleteAgentRemoteLogSequences(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentRemoteLogSequences, agentID)
	return err
}

const deleteAgentRemoteStepRuns = `-- name: DeleteAgentRemoteStepRuns :exec
DELETE FROM remote_step_runs WHERE agent_id = ?
`

func (q *Queries) DeleteAgentRemoteStepRuns(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentRemoteStepRuns, agentID)
	return err
}

const detachAgentDeploymentAttempts = `-- name: DetachAgentDeploymentAttempts :exec
UPDATE deployment_step_attempts
SET agent_id = NULL, claim_token_hash = NULL, claim_expires_at = NULL
WHERE agent_id = ?
`

func (q *Queries) DetachAgentDeploymentAttempts(ctx context.Context, agentID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, detachAgentDeploymentAttempts, agentID)
	return err
}

const detachAgentDeployments = `-- name: DetachAgentDeployments :exec
UPDATE deployments SET assigned_agent_id = NULL WHERE assigned_agent_id = ?
`

func (q *Queries) DetachAgentDeployments(ctx context.Context, assignedAgentID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, detachAgentDeployments, assignedAgentID)
	return err
}

const lockAgentForDeletion = `-- name: LockAgentForDeletion :execrows
UPDATE agents SET updated_at = updated_at -- NOSONAR: intentional write lock
WHERE id = ?
`

func (q *Queries) LockAgentForDeletion(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockAgentForDeletion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const preserveAgentDeploymentCleanup = `-- name: PreserveAgentDeploymentCleanup :exec
UPDATE deployments SET cleanup_confirmed_at = unixepoch()
WHERE status = 'cleanup_unconfirmed' AND cleanup_confirmed_at IS NULL
  AND container_namespace IS NULL
  AND (EXISTS (SELECT 1 FROM remote_step_runs s WHERE s.deployment_id = deployments.id
      AND s.agent_id = ?1 AND s.cleanup_confirmed_at IS NOT NULL)
    OR EXISTS (SELECT 1 FROM remote_deployment_claims c WHERE c.deployment_id = deployments.id
      AND c.agent_id = ?1 AND c.cleanup_confirmed_at IS NOT NULL))
  AND NOT EXISTS (SELECT 1 FROM remote_step_runs s WHERE s.deployment_id = deployments.id
      AND s.state = 'cleanup_unconfirmed' AND s.cleanup_confirmed_at IS NULL)
  AND NOT EXISTS (SELECT 1 FROM remote_deployment_claims c WHERE c.deployment_id = deployments.id
      AND c.state = 'cleanup_unconfirmed' AND c.cleanup_confirmed_at IS NULL)
`

func (q *Queries) PreserveAgentDeploymentCleanup(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, preserveAgentDeploymentCleanup, agentID)
	return err
}
