// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_fleet.sql

package db

import (
	"context"
	"database/sql"
)

const listFleetCurrentWork = `-- name: ListFleetCurrentWork :many
SELECT agent_id, deployment_id, step_index, state FROM remote_step_runs
WHERE state IN ('claimed', 'started', 'cancel_requested')
    OR (state = 'cleanup_unconfirmed' AND cleanup_confirmed_at IS NULL)
UNION ALL
SELECT agent_id, deployment_id, CAST(-1 AS INTEGER) AS step_index, state
FROM remote_deployment_claims
WHERE state IN ('claimed', 'started', 'cancel_requested')
    OR (state = 'cleanup_unconfirmed' AND cleanup_confirmed_at IS NULL)
ORDER BY agent_id, deployment_id, step_index
`

type ListFleetCurrentWorkRow struct {
	AgentID      string `json:"agent_id"`
	DeploymentID int64  `json:"deployment_id"`
	StepIndex    int64  `json:"step_index"`
	State        string `json:"state"`
}

func (q *Queries) ListFleetCurrentWork(ctx context.Context) ([]ListFleetCurrentWorkRow, error) {
	rows, err := q.db.QueryContext(ctx, listFleetCurrentWork)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFleetCurrentWorkRow
	for rows.Next() {
		var i ListFleetCurrentWorkRow
		if err := rows.Scan(
			&i.AgentID,
			&i.DeploymentID,
			&i.StepIndex,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetExecutionCapabilities = `-- name: ListFleetExecutionCapabilities :many
SELECT agent_id, 'mode' AS kind, execution_mode AS value FROM agent_execution_modes
UNION ALL SELECT agent_id, 'runtime' AS kind, runtime AS value FROM agent_container_runtimes
UNION ALL SELECT agent_id, 'interpreter' AS kind, interpreter AS value FROM agent_container_interpreters
ORDER BY agent_id, kind, value
`

type ListFleetExecutionCapabilitiesRow struct {
	AgentID string `json:"agent_id"`
	Kind    string `json:"kind"`
	Value   string `json:"value"`
}

func (q *Queries) ListFleetExecutionCapabilities(ctx context.Context) ([]ListFleetExecutionCapabilitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFleetExecutionCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFleetExecutionCapabilitiesRow
	for rows.Next() {
		var i ListFleetExecutionCapabilitiesRow
		if err := rows.Scan(&i.AgentID, &i.Kind, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetHealthBaselines = `-- name: ListFleetHealthBaselines :many
SELECT a.id, CAST(COALESCE(p.paired_at, a.created_at) AS INTEGER) AS baseline
FROM agents a LEFT JOIN agent_pairings p ON p.agent_id = a.id
`

type ListFleetHealthBaselinesRow struct {
	ID       string `json:"id"`
	Baseline int64  `json:"baseline"`
}

func (q *Queries) ListFleetHealthBaselines(ctx context.Context) ([]ListFleetHealthBaselinesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFleetHealthBaselines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFleetHealthBaselinesRow
	for rows.Next() {
		var i ListFleetHealthBaselinesRow
		if err := rows.Scan(&i.ID, &i.Baseline); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetInterpreters = `-- name: ListFleetInterpreters :many
SELECT agent_id, interpreter FROM agent_interpreters
ORDER BY agent_id, interpreter
`

func (q *Queries) ListFleetInterpreters(ctx context.Context) ([]AgentInterpreter, error) {
	rows, err := q.db.QueryContext(ctx, listFleetInterpreters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentInterpreter
	for rows.Next() {
		var i AgentInterpreter
		if err := rows.Scan(&i.AgentID, &i.Interpreter); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetLastErrors = `-- name: ListFleetLastErrors :many
SELECT agent_id, deployment_id, step_index, state, reason, finished_at FROM (
    SELECT agent_id, deployment_id, step_index, state, reason, finished_at,
        ROW_NUMBER() OVER (PARTITION BY agent_id ORDER BY finished_at DESC,
            deployment_id DESC, step_index DESC) AS ordinal
    FROM (
        SELECT agent_id, deployment_id, step_index, state, state AS reason, finished_at
        FROM remote_step_runs WHERE state IN ('failed', 'lost', 'cancel_unconfirmed', 'cleanup_unconfirmed')
        UNION ALL
        SELECT agent_id, deployment_id, CAST(-1 AS INTEGER) AS step_index, state,
            COALESCE(reason, state) AS reason, finished_at
        FROM remote_deployment_claims
        WHERE state IN ('failed', 'lost', 'cancel_unconfirmed', 'cleanup_unconfirmed')
    ) failures
) ranked WHERE ordinal = 1
`

type ListFleetLastErrorsRow struct {
	AgentID      string        `json:"agent_id"`
	DeploymentID int64         `json:"deployment_id"`
	StepIndex    int64         `json:"step_index"`
	State        string        `json:"state"`
	Reason       string        `json:"reason"`
	FinishedAt   sql.NullInt64 `json:"finished_at"`
}

func (q *Queries) ListFleetLastErrors(ctx context.Context) ([]ListFleetLastErrorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFleetLastErrors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFleetLastErrorsRow
	for rows.Next() {
		var i ListFleetLastErrorsRow
		if err := rows.Scan(
			&i.AgentID,
			&i.DeploymentID,
			&i.StepIndex,
			&i.State,
			&i.Reason,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetLastSuccessfulDeployments = `-- name: ListFleetLastSuccessfulDeployments :many
SELECT agent_id, deployment_id, finished_at FROM (
    SELECT agent_id, deployment_id, finished_at,
        ROW_NUMBER() OVER (PARTITION BY agent_id
            ORDER BY finished_at DESC, deployment_id DESC) AS ordinal
    FROM (
        SELECT r.agent_id, d.id AS deployment_id, d.finished_at
        FROM remote_step_runs r JOIN deployments d ON d.id = r.deployment_id
        WHERE r.state = 'succeeded' AND d.status = 'succeeded'
        UNION
        SELECT c.agent_id, d.id AS deployment_id, d.finished_at
        FROM remote_deployment_claims c JOIN deployments d ON d.id = c.deployment_id
        WHERE c.state = 'succeeded' AND d.status = 'succeeded'
    ) successes
) ranked WHERE ordinal = 1
`

type ListFleetLastSuccessfulDeploymentsRow struct {
	AgentID      string        `json:"agent_id"`
	DeploymentID int64         `json:"deployment_id"`
	FinishedAt   sql.NullInt64 `json:"finished_at"`
}

func (q *Queries) ListFleetLastSuccessfulDeployments(ctx context.Context) ([]ListFleetLastSuccessfulDeploymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFleetLastSuccessfulDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFleetLastSuccessfulDeploymentsRow
	for rows.Next() {
		var i ListFleetLastSuccessfulDeploymentsRow
		if err := rows.Scan(&i.AgentID, &i.DeploymentID, &i.FinishedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFleetQueuedWork = `-- name: ListFleetQueuedWork :many
SELECT agent_id, CAST(COUNT(*) AS INTEGER) AS queued_work FROM (
    SELECT agent_id FROM remote_step_runs WHERE state = 'waiting'
    UNION ALL
    SELECT agent_id FROM remote_deployment_claims WHERE state = 'waiting'
) queued GROUP BY agent_id
`

type ListFleetQueuedWorkRow struct {
	AgentID    string `json:"agent_id"`
	QueuedWork int64  `json:"queued_work"`
}

func (q *Queries) ListFleetQueuedWork(ctx context.Context) ([]ListFleetQueuedWorkRow, error) {
	rows, err := q.db.QueryContext(ctx, listFleetQueuedWork)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFleetQueuedWorkRow
	for rows.Next() {
		var i ListFleetQueuedWorkRow
		if err := rows.Scan(&i.AgentID, &i.QueuedWork); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
