// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package db

import (
	"context"
	"database/sql"
)

const activatePendingAgent = `-- name: ActivatePendingAgent :one
UPDATE agents
SET status = 'active',
    certificate_pem = ?,
    certificate_fingerprint = ?,
    agent_version = ?,
    last_heartbeat_at = ?,
    enrolled_at = ?,
    updated_at = ?
WHERE id = ?
  AND status = 'pending'
RETURNING id, status, certificate_fingerprint, agent_version, enrolled_at
`

type ActivatePendingAgentParams struct {
	CertificatePem         sql.NullString `json:"certificate_pem"`
	CertificateFingerprint sql.NullString `json:"certificate_fingerprint"`
	AgentVersion           sql.NullString `json:"agent_version"`
	LastHeartbeatAt        sql.NullInt64  `json:"last_heartbeat_at"`
	EnrolledAt             sql.NullInt64  `json:"enrolled_at"`
	UpdatedAt              int64          `json:"updated_at"`
	ID                     string         `json:"id"`
}

type ActivatePendingAgentRow struct {
	ID                     string         `json:"id"`
	Status                 string         `json:"status"`
	CertificateFingerprint sql.NullString `json:"certificate_fingerprint"`
	AgentVersion           sql.NullString `json:"agent_version"`
	EnrolledAt             sql.NullInt64  `json:"enrolled_at"`
}

func (q *Queries) ActivatePendingAgent(ctx context.Context, arg ActivatePendingAgentParams) (ActivatePendingAgentRow, error) {
	row := q.db.QueryRowContext(ctx, activatePendingAgent,
		arg.CertificatePem,
		arg.CertificateFingerprint,
		arg.AgentVersion,
		arg.LastHeartbeatAt,
		arg.EnrolledAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i ActivatePendingAgentRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CertificateFingerprint,
		&i.AgentVersion,
		&i.EnrolledAt,
	)
	return i, err
}

const consumeAgentEnrollmentToken = `-- name: ConsumeAgentEnrollmentToken :execrows
UPDATE agent_enrollment_tokens
SET used_at = ?
WHERE token_hash = ?
  AND agent_id = ?
  AND expires_at > ?
  AND used_at IS NULL
  AND revoked_at IS NULL
  AND EXISTS (
      SELECT 1
      FROM agents
      WHERE agents.id = agent_enrollment_tokens.agent_id
        AND agents.status = 'pending'
  )
`

type ConsumeAgentEnrollmentTokenParams struct {
	UsedAt    sql.NullInt64 `json:"used_at"`
	TokenHash []byte        `json:"token_hash"`
	AgentID   string        `json:"agent_id"`
	ExpiresAt int64         `json:"expires_at"`
}

func (q *Queries) ConsumeAgentEnrollmentToken(ctx context.Context, arg ConsumeAgentEnrollmentTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeAgentEnrollmentToken,
		arg.UsedAt,
		arg.TokenHash,
		arg.AgentID,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAgentEnrollmentToken = `-- name: CreateAgentEnrollmentToken :exec
INSERT INTO agent_enrollment_tokens (
    token_hash, token_prefix, agent_id, expires_at
) VALUES (?, ?, ?, ?)
`

type CreateAgentEnrollmentTokenParams struct {
	TokenHash   []byte `json:"token_hash"`
	TokenPrefix string `json:"token_prefix"`
	AgentID     string `json:"agent_id"`
	ExpiresAt   int64  `json:"expires_at"`
}

func (q *Queries) CreateAgentEnrollmentToken(ctx context.Context, arg CreateAgentEnrollmentTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAgentEnrollmentToken,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.AgentID,
		arg.ExpiresAt,
	)
	return err
}

const createPendingAgent = `-- name: CreatePendingAgent :one
INSERT INTO agents (id, name, agent_version)
VALUES (?, ?, ?)
RETURNING id, name, status, agent_version, created_at
`

type CreatePendingAgentParams struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	AgentVersion sql.NullString `json:"agent_version"`
}

type CreatePendingAgentRow struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Status       string         `json:"status"`
	AgentVersion sql.NullString `json:"agent_version"`
	CreatedAt    int64          `json:"created_at"`
}

func (q *Queries) CreatePendingAgent(ctx context.Context, arg CreatePendingAgentParams) (CreatePendingAgentRow, error) {
	row := q.db.QueryRowContext(ctx, createPendingAgent, arg.ID, arg.Name, arg.AgentVersion)
	var i CreatePendingAgentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AgentVersion,
		&i.CreatedAt,
	)
	return i, err
}

const deletePendingUnreferencedAgent = `-- name: DeletePendingUnreferencedAgent :execrows
DELETE FROM agents
WHERE id = ?
  AND status = 'pending'
  AND NOT EXISTS (
      SELECT 1 FROM agent_pool_memberships WHERE agent_id = agents.id
  )
  AND NOT EXISTS (SELECT 1 FROM agent_tags WHERE agent_id = agents.id)
  AND NOT EXISTS (
      SELECT 1 FROM agent_enrollment_tokens WHERE agent_id = agents.id
  )
  AND NOT EXISTS (SELECT 1 FROM agent_events WHERE agent_id = agents.id)
  AND NOT EXISTS (
      SELECT 1 FROM deployment_dispatches WHERE agent_id = agents.id
  )
`

func (q *Queries) DeletePendingUnreferencedAgent(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingUnreferencedAgent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const disableAgent = `-- name: DisableAgent :execrows
UPDATE agents
SET status = 'disabled',
    updated_at = ?
WHERE id = ?
  AND status = 'active'
`

type DisableAgentParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) DisableAgent(ctx context.Context, arg DisableAgentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, disableAgent, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveAgentByFingerprint = `-- name: GetActiveAgentByFingerprint :one
SELECT id, name, agent_version, certificate_pem, certificate_fingerprint, last_heartbeat_at,
       enrolled_at
FROM agents
WHERE certificate_fingerprint = ?
  AND status = 'active'
`

type GetActiveAgentByFingerprintRow struct {
	ID                     string         `json:"id"`
	Name                   string         `json:"name"`
	AgentVersion           sql.NullString `json:"agent_version"`
	CertificatePem         sql.NullString `json:"certificate_pem"`
	CertificateFingerprint sql.NullString `json:"certificate_fingerprint"`
	LastHeartbeatAt        sql.NullInt64  `json:"last_heartbeat_at"`
	EnrolledAt             sql.NullInt64  `json:"enrolled_at"`
}

func (q *Queries) GetActiveAgentByFingerprint(ctx context.Context, certificateFingerprint sql.NullString) (GetActiveAgentByFingerprintRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveAgentByFingerprint, certificateFingerprint)
	var i GetActiveAgentByFingerprintRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AgentVersion,
		&i.CertificatePem,
		&i.CertificateFingerprint,
		&i.LastHeartbeatAt,
		&i.EnrolledAt,
	)
	return i, err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, status, agent_version, certificate_pem, certificate_fingerprint, last_heartbeat_at, enrolled_at, revoked_at, created_at, updated_at FROM agents WHERE id = ?
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AgentVersion,
		&i.CertificatePem,
		&i.CertificateFingerprint,
		&i.LastHeartbeatAt,
		&i.EnrolledAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, status, agent_version, certificate_pem, certificate_fingerprint, last_heartbeat_at, enrolled_at, revoked_at, created_at, updated_at FROM agents ORDER BY name ASC, id ASC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.AgentVersion,
			&i.CertificatePem,
			&i.CertificateFingerprint,
			&i.LastHeartbeatAt,
			&i.EnrolledAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRedactedAgentEventsByAgent = `-- name: ListRedactedAgentEventsByAgent :many
SELECT id, agent_id, deployment_id, event_type, dispatch_state, created_at
FROM agent_events
WHERE agent_id = ?
ORDER BY created_at DESC, id DESC
`

type ListRedactedAgentEventsByAgentRow struct {
	ID            int64          `json:"id"`
	AgentID       sql.NullString `json:"agent_id"`
	DeploymentID  sql.NullInt64  `json:"deployment_id"`
	EventType     string         `json:"event_type"`
	DispatchState sql.NullString `json:"dispatch_state"`
	CreatedAt     int64          `json:"created_at"`
}

func (q *Queries) ListRedactedAgentEventsByAgent(ctx context.Context, agentID sql.NullString) ([]ListRedactedAgentEventsByAgentRow, error) {
	rows, err := q.db.QueryContext(ctx, listRedactedAgentEventsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRedactedAgentEventsByAgentRow
	for rows.Next() {
		var i ListRedactedAgentEventsByAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.DeploymentID,
			&i.EventType,
			&i.DispatchState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reenrollAgent = `-- name: ReenrollAgent :execrows
UPDATE agents
SET status = 'pending',
    certificate_pem = NULL,
    certificate_fingerprint = NULL,
    last_heartbeat_at = NULL,
    enrolled_at = NULL,
    revoked_at = NULL,
    updated_at = ?
WHERE id = ?
  AND status = 'revoked'
`

type ReenrollAgentParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ReenrollAgent(ctx context.Context, arg ReenrollAgentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reenrollAgent, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeAgent = `-- name: RevokeAgent :execrows
UPDATE agents
SET status = 'revoked',
    revoked_at = ?,
    updated_at = ?
WHERE id = ?
  AND status IN ('active', 'disabled')
`

type RevokeAgentParams struct {
	RevokedAt sql.NullInt64 `json:"revoked_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) RevokeAgent(ctx context.Context, arg RevokeAgentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAgent, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeAgentEnrollmentTokens = `-- name: RevokeAgentEnrollmentTokens :exec
UPDATE agent_enrollment_tokens
SET revoked_at = ?
WHERE agent_id = ?
  AND used_at IS NULL
  AND revoked_at IS NULL
`

type RevokeAgentEnrollmentTokensParams struct {
	RevokedAt sql.NullInt64 `json:"revoked_at"`
	AgentID   string        `json:"agent_id"`
}

func (q *Queries) RevokeAgentEnrollmentTokens(ctx context.Context, arg RevokeAgentEnrollmentTokensParams) error {
	_, err := q.db.ExecContext(ctx, revokeAgentEnrollmentTokens, arg.RevokedAt, arg.AgentID)
	return err
}

const touchAgentHeartbeat = `-- name: TouchAgentHeartbeat :execrows
UPDATE agents
SET last_heartbeat_at = ?1,
    updated_at = ?2
WHERE id = ?3
  AND status = 'active'
`

type TouchAgentHeartbeatParams struct {
	LastHeartbeatAt sql.NullInt64 `json:"last_heartbeat_at"`
	UpdatedAt       int64         `json:"updated_at"`
	ID              string        `json:"id"`
}

func (q *Queries) TouchAgentHeartbeat(ctx context.Context, arg TouchAgentHeartbeatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchAgentHeartbeat, arg.LastHeartbeatAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAgentHeartbeat = `-- name: UpdateAgentHeartbeat :execrows
UPDATE agents
SET agent_version = ?,
    last_heartbeat_at = ?,
    updated_at = ?
WHERE id = ?
  AND status = 'active'
`

type UpdateAgentHeartbeatParams struct {
	AgentVersion    sql.NullString `json:"agent_version"`
	LastHeartbeatAt sql.NullInt64  `json:"last_heartbeat_at"`
	UpdatedAt       int64          `json:"updated_at"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateAgentHeartbeat(ctx context.Context, arg UpdateAgentHeartbeatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAgentHeartbeat,
		arg.AgentVersion,
		arg.LastHeartbeatAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
