// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"
	"database/sql"
)

const addAgentEnvironmentLabel = `-- name: AddAgentEnvironmentLabel :execrows
INSERT INTO agent_environment_labels (agent_id, environment_id)
SELECT ?1, ?2
WHERE NOT EXISTS (SELECT 1 FROM agent_environment_labels
 WHERE agent_id = ?1
   AND environment_id = ?2)
`

type AddAgentEnvironmentLabelParams struct {
	AgentID       string `json:"agent_id"`
	EnvironmentID int64  `json:"environment_id"`
}

func (q *Queries) AddAgentEnvironmentLabel(ctx context.Context, arg AddAgentEnvironmentLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addAgentEnvironmentLabel, arg.AgentID, arg.EnvironmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const addAgentLabel = `-- name: AddAgentLabel :execrows
INSERT INTO agent_labels (agent_id, label)
SELECT ?1, ?2
WHERE NOT EXISTS (SELECT 1 FROM agent_labels WHERE agent_id = ?1 AND label = ?2)
`

type AddAgentLabelParams struct {
	AgentID string `json:"agent_id"`
	Label   string `json:"label"`
}

func (q *Queries) AddAgentLabel(ctx context.Context, arg AddAgentLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addAgentLabel, arg.AgentID, arg.Label)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, name, endpoint) VALUES (?, ?, ?) RETURNING id, name, endpoint, status, agent_version, certificate_pem, certificate_fingerprint, encrypted_identity, last_heartbeat_at, revoked_at, created_at, updated_at
`

type CreateAgentParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Endpoint string `json:"endpoint"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent, arg.ID, arg.Name, arg.Endpoint)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Status,
		&i.AgentVersion,
		&i.CertificatePem,
		&i.CertificateFingerprint,
		&i.EncryptedIdentity,
		&i.LastHeartbeatAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentEnvironmentLabel = `-- name: DeleteAgentEnvironmentLabel :execrows
DELETE FROM agent_environment_labels
WHERE agent_id = ? AND environment_id = ?
`

type DeleteAgentEnvironmentLabelParams struct {
	AgentID       string `json:"agent_id"`
	EnvironmentID int64  `json:"environment_id"`
}

func (q *Queries) DeleteAgentEnvironmentLabel(ctx context.Context, arg DeleteAgentEnvironmentLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAgentEnvironmentLabel, arg.AgentID, arg.EnvironmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAgentLabel = `-- name: DeleteAgentLabel :execrows
DELETE FROM agent_labels WHERE agent_id = ? AND label = ?
`

type DeleteAgentLabelParams struct {
	AgentID string `json:"agent_id"`
	Label   string `json:"label"`
}

func (q *Queries) DeleteAgentLabel(ctx context.Context, arg DeleteAgentLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAgentLabel, arg.AgentID, arg.Label)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePendingAgent = `-- name: DeletePendingAgent :execrows
DELETE FROM agents WHERE id = ? AND status = 'pending'
AND NOT EXISTS (SELECT 1 FROM agent_pairings WHERE agent_id = agents.id)
`

func (q *Queries) DeletePendingAgent(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingAgent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, endpoint, status, agent_version, certificate_pem, certificate_fingerprint, encrypted_identity, last_heartbeat_at, revoked_at, created_at, updated_at FROM agents WHERE id = ?
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Status,
		&i.AgentVersion,
		&i.CertificatePem,
		&i.CertificateFingerprint,
		&i.EncryptedIdentity,
		&i.LastHeartbeatAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatAgent = `-- name: HeartbeatAgent :execrows
UPDATE agents SET last_heartbeat_at = ?1, agent_version = ?2,
    updated_at = ?1
WHERE id = ?3 AND certificate_fingerprint = ?4
  AND status = 'active'
  AND (last_heartbeat_at IS NULL OR last_heartbeat_at <= ?1)
  AND EXISTS (SELECT 1 FROM agent_pairings WHERE agent_id = agents.id AND state = 'paired')
`

type HeartbeatAgentParams struct {
	Now                    sql.NullInt64  `json:"now"`
	AgentVersion           sql.NullString `json:"agent_version"`
	ID                     string         `json:"id"`
	CertificateFingerprint sql.NullString `json:"certificate_fingerprint"`
}

func (q *Queries) HeartbeatAgent(ctx context.Context, arg HeartbeatAgentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, heartbeatAgent,
		arg.Now,
		arg.AgentVersion,
		arg.ID,
		arg.CertificateFingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAgentEnvironmentLabels = `-- name: ListAgentEnvironmentLabels :many
SELECT e.id, e.name, e.description, e.tags, e.created_at FROM environments e
JOIN agent_environment_labels l ON l.environment_id = e.id
WHERE l.agent_id = ? ORDER BY e.name, e.id
`

func (q *Queries) ListAgentEnvironmentLabels(ctx context.Context, agentID string) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, listAgentEnvironmentLabels, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentLabels = `-- name: ListAgentLabels :many
SELECT label FROM agent_labels WHERE agent_id = ? ORDER BY label
`

func (q *Queries) ListAgentLabels(ctx context.Context, agentID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAgentLabels, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, endpoint, status, agent_version, certificate_pem, certificate_fingerprint, encrypted_identity, last_heartbeat_at, revoked_at, created_at, updated_at FROM agents ORDER BY name, id
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Endpoint,
			&i.Status,
			&i.AgentVersion,
			&i.CertificatePem,
			&i.CertificateFingerprint,
			&i.EncryptedIdentity,
			&i.LastHeartbeatAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableAgentEnvironmentLabels = `-- name: ListAvailableAgentEnvironmentLabels :many
SELECT e.id, e.name, e.description, e.tags, e.created_at FROM environments e
WHERE NOT EXISTS (SELECT 1 FROM agent_environment_labels l
 WHERE l.agent_id = ?1 AND l.environment_id = e.id)
ORDER BY e.name, e.id
`

func (q *Queries) ListAvailableAgentEnvironmentLabels(ctx context.Context, agentID string) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableAgentEnvironmentLabels, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableAgentLabels = `-- name: ListAvailableAgentLabels :many
SELECT DISTINCT label FROM agent_labels ORDER BY label
`

func (q *Queries) ListAvailableAgentLabels(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableAgentLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevocableAgentClaims = `-- name: ListRevocableAgentClaims :many
SELECT deployment_id, agent_id, state, reason, claim_token_hash, ciphertext, claim_expires_at, last_heartbeat_at, started_at, finished_at, cancel_requested_at, created_at, updated_at, log_buffer_ciphertext FROM remote_deployment_claims
WHERE agent_id = ? AND state IN ('waiting', 'claimed', 'started', 'cancel_requested')
ORDER BY deployment_id
`

func (q *Queries) ListRevocableAgentClaims(ctx context.Context, agentID string) ([]RemoteDeploymentClaim, error) {
	rows, err := q.db.QueryContext(ctx, listRevocableAgentClaims, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteDeploymentClaim
	for rows.Next() {
		var i RemoteDeploymentClaim
		if err := rows.Scan(
			&i.DeploymentID,
			&i.AgentID,
			&i.State,
			&i.Reason,
			&i.ClaimTokenHash,
			&i.Ciphertext,
			&i.ClaimExpiresAt,
			&i.LastHeartbeatAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LogBufferCiphertext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetRevokedAgentForPairing = `-- name: ResetRevokedAgentForPairing :execrows
UPDATE agents SET endpoint = ?1, status = 'pending',
    agent_version = NULL, certificate_pem = NULL,
    certificate_fingerprint = NULL, encrypted_identity = NULL,
    last_heartbeat_at = NULL, revoked_at = NULL, updated_at = unixepoch()
WHERE id = ?2 AND status = 'revoked'
`

type ResetRevokedAgentForPairingParams struct {
	Endpoint string `json:"endpoint"`
	ID       string `json:"id"`
}

func (q *Queries) ResetRevokedAgentForPairing(ctx context.Context, arg ResetRevokedAgentForPairingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetRevokedAgentForPairing, arg.Endpoint, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeAgentRemoteStepRuns = `-- name: RevokeAgentRemoteStepRuns :execrows
UPDATE remote_step_runs SET state = 'lost', finished_at = ?1,
    updated_at = ?1, log_buffer_ciphertext = NULL
WHERE agent_id = ?2
  AND state IN ('waiting', 'claimed', 'started', 'cancel_requested')
`

type RevokeAgentRemoteStepRunsParams struct {
	Now     sql.NullInt64 `json:"now"`
	AgentID string        `json:"agent_id"`
}

func (q *Queries) RevokeAgentRemoteStepRuns(ctx context.Context, arg RevokeAgentRemoteStepRunsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAgentRemoteStepRuns, arg.Now, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeStartedRemoteClaim = `-- name: RevokeStartedRemoteClaim :execrows
UPDATE remote_deployment_claims SET state = 'lost',
    reason = 'remote_agent_revoked_after_start', cancel_requested_at = NULL,
    finished_at = ?1, updated_at = ?1,
    log_buffer_ciphertext = NULL
WHERE deployment_id = ?2
  AND agent_id = ?3
  AND state IN ('started', 'cancel_requested') AND started_at IS NOT NULL
`

type RevokeStartedRemoteClaimParams struct {
	Now          sql.NullInt64 `json:"now"`
	DeploymentID int64         `json:"deployment_id"`
	AgentID      string        `json:"agent_id"`
}

func (q *Queries) RevokeStartedRemoteClaim(ctx context.Context, arg RevokeStartedRemoteClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeStartedRemoteClaim, arg.Now, arg.DeploymentID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeUnstartedRemoteClaim = `-- name: RevokeUnstartedRemoteClaim :execrows
UPDATE remote_deployment_claims SET state = 'failed',
    reason = 'remote_agent_revoked_before_start',
    finished_at = ?1, updated_at = ?1,
    log_buffer_ciphertext = NULL
WHERE deployment_id = ?2
  AND agent_id = ?3
  AND state IN ('waiting', 'claimed') AND started_at IS NULL
`

type RevokeUnstartedRemoteClaimParams struct {
	Now          sql.NullInt64 `json:"now"`
	DeploymentID int64         `json:"deployment_id"`
	AgentID      string        `json:"agent_id"`
}

func (q *Queries) RevokeUnstartedRemoteClaim(ctx context.Context, arg RevokeUnstartedRemoteClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeUnstartedRemoteClaim, arg.Now, arg.DeploymentID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAgentStatus = `-- name: SetAgentStatus :one
UPDATE agents SET status = ?1, updated_at = unixepoch(),
    revoked_at = CASE WHEN ?1 = 'revoked' THEN unixepoch() ELSE revoked_at END
WHERE id = ?2 AND status IN ('pending', 'active', 'disabled')
  AND (?1 = 'revoked'
       OR (status IN ('active', 'disabled') AND (?1 = 'active' OR ?1 = 'disabled'))) RETURNING id, name, endpoint, status, agent_version, certificate_pem, certificate_fingerprint, encrypted_identity, last_heartbeat_at, revoked_at, created_at, updated_at
`

type SetAgentStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) SetAgentStatus(ctx context.Context, arg SetAgentStatusParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, setAgentStatus, arg.Status, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Status,
		&i.AgentVersion,
		&i.CertificatePem,
		&i.CertificateFingerprint,
		&i.EncryptedIdentity,
		&i.LastHeartbeatAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const terminateRevokedRemoteDeployment = `-- name: TerminateRevokedRemoteDeployment :execrows
UPDATE deployments SET
    status = 'failed',
    finished_at = ?1
WHERE id = ?2
  AND assigned_agent_id = ?3
  AND status IN ('pending', 'pending_approval', 'running')
`

type TerminateRevokedRemoteDeploymentParams struct {
	Now          sql.NullInt64  `json:"now"`
	DeploymentID int64          `json:"deployment_id"`
	AgentID      sql.NullString `json:"agent_id"`
}

func (q *Queries) TerminateRevokedRemoteDeployment(ctx context.Context, arg TerminateRevokedRemoteDeploymentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, terminateRevokedRemoteDeployment, arg.Now, arg.DeploymentID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAgentHeartbeat = `-- name: TouchAgentHeartbeat :execrows
UPDATE agents SET last_heartbeat_at = ?1, updated_at = ?1
WHERE id = ?2 AND status = 'active'
  AND (last_heartbeat_at IS NULL OR last_heartbeat_at <= ?1)
  AND EXISTS (SELECT 1 FROM agent_pairings WHERE agent_id = agents.id AND state = 'paired')
`

type TouchAgentHeartbeatParams struct {
	Now sql.NullInt64 `json:"now"`
	ID  string        `json:"id"`
}

func (q *Queries) TouchAgentHeartbeat(ctx context.Context, arg TouchAgentHeartbeatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchAgentHeartbeat, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents SET name = ?, endpoint = ?, updated_at = unixepoch()
WHERE id = ? AND status IN ('pending', 'active', 'disabled') RETURNING id, name, endpoint, status, agent_version, certificate_pem, certificate_fingerprint, encrypted_identity, last_heartbeat_at, revoked_at, created_at, updated_at
`

type UpdateAgentParams struct {
	Name     string `json:"name"`
	Endpoint string `json:"endpoint"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgent, arg.Name, arg.Endpoint, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Endpoint,
		&i.Status,
		&i.AgentVersion,
		&i.CertificatePem,
		&i.CertificateFingerprint,
		&i.EncryptedIdentity,
		&i.LastHeartbeatAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
