// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_tokens.sql

package db

import (
	"context"
	"database/sql"
)

const countAllApiTokens = `-- name: CountAllApiTokens :one
SELECT COUNT(*) FROM api_tokens
`

func (q *Queries) CountAllApiTokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllApiTokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllApiTokensByUser = `-- name: CountAllApiTokensByUser :one
SELECT COUNT(*) FROM api_tokens WHERE user_id = ?
`

func (q *Queries) CountAllApiTokensByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllApiTokensByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countApiTokensByUser = `-- name: CountApiTokensByUser :one
SELECT COUNT(*) FROM api_tokens WHERE user_id = ?
`

func (q *Queries) CountApiTokensByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countApiTokensByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApiToken = `-- name: CreateApiToken :one
INSERT INTO api_tokens (id, user_id, name, token_prefix, token_hash, scope, expires_at) VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, user_id, name, token_prefix, token_hash, scope, last_used_at, expires_at, created_at, revoked_at
`

type CreateApiTokenParams struct {
	ID          string        `json:"id"`
	UserID      int64         `json:"user_id"`
	Name        string        `json:"name"`
	TokenPrefix string        `json:"token_prefix"`
	TokenHash   string        `json:"token_hash"`
	Scope       string        `json:"scope"`
	ExpiresAt   sql.NullInt64 `json:"expires_at"`
}

func (q *Queries) CreateApiToken(ctx context.Context, arg CreateApiTokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createApiToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenPrefix,
		arg.TokenHash,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.Scope,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getApiTokenByHash = `-- name: GetApiTokenByHash :one
SELECT t.id, t.user_id, t.name, t.token_prefix, t.token_hash, t.scope, t.last_used_at, t.expires_at, t.created_at, t.revoked_at, u.email, u.name AS user_name, u.role FROM api_tokens t JOIN users u ON t.user_id = u.id WHERE t.token_hash = ? AND t.revoked_at IS NULL AND (t.expires_at IS NULL OR t.expires_at > ?)
`

type GetApiTokenByHashParams struct {
	TokenHash string        `json:"token_hash"`
	ExpiresAt sql.NullInt64 `json:"expires_at"`
}

type GetApiTokenByHashRow struct {
	ID          string        `json:"id"`
	UserID      int64         `json:"user_id"`
	Name        string        `json:"name"`
	TokenPrefix string        `json:"token_prefix"`
	TokenHash   string        `json:"token_hash"`
	Scope       string        `json:"scope"`
	LastUsedAt  sql.NullInt64 `json:"last_used_at"`
	ExpiresAt   sql.NullInt64 `json:"expires_at"`
	CreatedAt   int64         `json:"created_at"`
	RevokedAt   sql.NullInt64 `json:"revoked_at"`
	Email       string        `json:"email"`
	UserName    string        `json:"user_name"`
	Role        string        `json:"role"`
}

func (q *Queries) GetApiTokenByHash(ctx context.Context, arg GetApiTokenByHashParams) (GetApiTokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getApiTokenByHash, arg.TokenHash, arg.ExpiresAt)
	var i GetApiTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.Scope,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.Email,
		&i.UserName,
		&i.Role,
	)
	return i, err
}

const getApiTokenByID = `-- name: GetApiTokenByID :one
SELECT id, user_id, name, token_prefix, token_hash, scope, last_used_at, expires_at, created_at, revoked_at FROM api_tokens WHERE id = ? AND revoked_at IS NULL
`

func (q *Queries) GetApiTokenByID(ctx context.Context, id string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getApiTokenByID, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.Scope,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAllApiTokens = `-- name: ListAllApiTokens :many
SELECT t.id, t.token_prefix, t.name, t.user_id, u.email, u.name AS user_name, t.scope, t.last_used_at, t.expires_at, t.created_at, t.revoked_at FROM api_tokens t JOIN users u ON t.user_id = u.id ORDER BY t.created_at DESC
`

type ListAllApiTokensRow struct {
	ID          string        `json:"id"`
	TokenPrefix string        `json:"token_prefix"`
	Name        string        `json:"name"`
	UserID      int64         `json:"user_id"`
	Email       string        `json:"email"`
	UserName    string        `json:"user_name"`
	Scope       string        `json:"scope"`
	LastUsedAt  sql.NullInt64 `json:"last_used_at"`
	ExpiresAt   sql.NullInt64 `json:"expires_at"`
	CreatedAt   int64         `json:"created_at"`
	RevokedAt   sql.NullInt64 `json:"revoked_at"`
}

func (q *Queries) ListAllApiTokens(ctx context.Context) ([]ListAllApiTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllApiTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllApiTokensRow
	for rows.Next() {
		var i ListAllApiTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenPrefix,
			&i.Name,
			&i.UserID,
			&i.Email,
			&i.UserName,
			&i.Scope,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllApiTokensByUser = `-- name: ListAllApiTokensByUser :many
SELECT t.id, t.token_prefix, t.name, t.user_id, u.email, u.name AS user_name, t.scope, t.last_used_at, t.expires_at, t.created_at, t.revoked_at FROM api_tokens t JOIN users u ON t.user_id = u.id WHERE t.user_id = ? ORDER BY t.created_at DESC
`

type ListAllApiTokensByUserRow struct {
	ID          string        `json:"id"`
	TokenPrefix string        `json:"token_prefix"`
	Name        string        `json:"name"`
	UserID      int64         `json:"user_id"`
	Email       string        `json:"email"`
	UserName    string        `json:"user_name"`
	Scope       string        `json:"scope"`
	LastUsedAt  sql.NullInt64 `json:"last_used_at"`
	ExpiresAt   sql.NullInt64 `json:"expires_at"`
	CreatedAt   int64         `json:"created_at"`
	RevokedAt   sql.NullInt64 `json:"revoked_at"`
}

func (q *Queries) ListAllApiTokensByUser(ctx context.Context, userID int64) ([]ListAllApiTokensByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllApiTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllApiTokensByUserRow
	for rows.Next() {
		var i ListAllApiTokensByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenPrefix,
			&i.Name,
			&i.UserID,
			&i.Email,
			&i.UserName,
			&i.Scope,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllApiTokensByUserPaginated = `-- name: ListAllApiTokensByUserPaginated :many
SELECT t.id, t.token_prefix, t.name, t.user_id, u.email, u.name AS user_name, t.scope, t.last_used_at, t.expires_at, t.created_at, t.revoked_at FROM api_tokens t JOIN users u ON t.user_id = u.id WHERE t.user_id = ? ORDER BY t.created_at DESC
LIMIT ? OFFSET ?
`

type ListAllApiTokensByUserPaginatedParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListAllApiTokensByUserPaginatedRow struct {
	ID          string        `json:"id"`
	TokenPrefix string        `json:"token_prefix"`
	Name        string        `json:"name"`
	UserID      int64         `json:"user_id"`
	Email       string        `json:"email"`
	UserName    string        `json:"user_name"`
	Scope       string        `json:"scope"`
	LastUsedAt  sql.NullInt64 `json:"last_used_at"`
	ExpiresAt   sql.NullInt64 `json:"expires_at"`
	CreatedAt   int64         `json:"created_at"`
	RevokedAt   sql.NullInt64 `json:"revoked_at"`
}

func (q *Queries) ListAllApiTokensByUserPaginated(ctx context.Context, arg ListAllApiTokensByUserPaginatedParams) ([]ListAllApiTokensByUserPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllApiTokensByUserPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllApiTokensByUserPaginatedRow
	for rows.Next() {
		var i ListAllApiTokensByUserPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenPrefix,
			&i.Name,
			&i.UserID,
			&i.Email,
			&i.UserName,
			&i.Scope,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllApiTokensPaginated = `-- name: ListAllApiTokensPaginated :many
SELECT t.id, t.token_prefix, t.name, t.user_id, u.email, u.name AS user_name, t.scope, t.last_used_at, t.expires_at, t.created_at, t.revoked_at FROM api_tokens t JOIN users u ON t.user_id = u.id ORDER BY t.created_at DESC
LIMIT ? OFFSET ?
`

type ListAllApiTokensPaginatedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListAllApiTokensPaginatedRow struct {
	ID          string        `json:"id"`
	TokenPrefix string        `json:"token_prefix"`
	Name        string        `json:"name"`
	UserID      int64         `json:"user_id"`
	Email       string        `json:"email"`
	UserName    string        `json:"user_name"`
	Scope       string        `json:"scope"`
	LastUsedAt  sql.NullInt64 `json:"last_used_at"`
	ExpiresAt   sql.NullInt64 `json:"expires_at"`
	CreatedAt   int64         `json:"created_at"`
	RevokedAt   sql.NullInt64 `json:"revoked_at"`
}

func (q *Queries) ListAllApiTokensPaginated(ctx context.Context, arg ListAllApiTokensPaginatedParams) ([]ListAllApiTokensPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllApiTokensPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllApiTokensPaginatedRow
	for rows.Next() {
		var i ListAllApiTokensPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenPrefix,
			&i.Name,
			&i.UserID,
			&i.Email,
			&i.UserName,
			&i.Scope,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiTokensByUser = `-- name: ListApiTokensByUser :many
SELECT id, token_prefix, name, scope, last_used_at, expires_at, created_at, revoked_at FROM api_tokens WHERE user_id = ? ORDER BY created_at DESC
`

type ListApiTokensByUserRow struct {
	ID          string        `json:"id"`
	TokenPrefix string        `json:"token_prefix"`
	Name        string        `json:"name"`
	Scope       string        `json:"scope"`
	LastUsedAt  sql.NullInt64 `json:"last_used_at"`
	ExpiresAt   sql.NullInt64 `json:"expires_at"`
	CreatedAt   int64         `json:"created_at"`
	RevokedAt   sql.NullInt64 `json:"revoked_at"`
}

func (q *Queries) ListApiTokensByUser(ctx context.Context, userID int64) ([]ListApiTokensByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listApiTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiTokensByUserRow
	for rows.Next() {
		var i ListApiTokensByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenPrefix,
			&i.Name,
			&i.Scope,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiTokensByUserPaginated = `-- name: ListApiTokensByUserPaginated :many
SELECT id, token_prefix, name, scope, last_used_at, expires_at, created_at, revoked_at FROM api_tokens WHERE user_id = ? ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListApiTokensByUserPaginatedParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListApiTokensByUserPaginatedRow struct {
	ID          string        `json:"id"`
	TokenPrefix string        `json:"token_prefix"`
	Name        string        `json:"name"`
	Scope       string        `json:"scope"`
	LastUsedAt  sql.NullInt64 `json:"last_used_at"`
	ExpiresAt   sql.NullInt64 `json:"expires_at"`
	CreatedAt   int64         `json:"created_at"`
	RevokedAt   sql.NullInt64 `json:"revoked_at"`
}

func (q *Queries) ListApiTokensByUserPaginated(ctx context.Context, arg ListApiTokensByUserPaginatedParams) ([]ListApiTokensByUserPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listApiTokensByUserPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiTokensByUserPaginatedRow
	for rows.Next() {
		var i ListApiTokensByUserPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenPrefix,
			&i.Name,
			&i.Scope,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiToken = `-- name: RevokeApiToken :exec
UPDATE api_tokens SET revoked_at = strftime('%s','now') WHERE id = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeApiToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeApiToken, id)
	return err
}

const touchApiTokenLastUsed = `-- name: TouchApiTokenLastUsed :exec
UPDATE api_tokens SET last_used_at = ? WHERE id = ?
`

type TouchApiTokenLastUsedParams struct {
	LastUsedAt sql.NullInt64 `json:"last_used_at"`
	ID         string        `json:"id"`
}

func (q *Queries) TouchApiTokenLastUsed(ctx context.Context, arg TouchApiTokenLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, touchApiTokenLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
