// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_queue.sql

package db

import (
	"context"
	"database/sql"
)

const admitQueuedDeployment = `-- name: AdmitQueuedDeployment :execrows
UPDATE deployments SET status = 'pending' WHERE id = ? AND status = 'queued'
`

func (q *Queries) AdmitQueuedDeployment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, admitQueuedDeployment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelQueuedDeployment = `-- name: CancelQueuedDeployment :execrows
UPDATE deployments SET status = 'cancelled', finished_at = unixepoch()
WHERE id = ? AND status IN ('queued', 'pending_approval', 'pending')
AND NOT EXISTS (SELECT 1 FROM remote_deployment_claims c WHERE c.deployment_id = deployments.id
    AND c.state NOT IN ('waiting', 'cancelled'))
`

func (q *Queries) CancelQueuedDeployment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelQueuedDeployment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelWaitingQueuedRemoteClaim = `-- name: CancelWaitingQueuedRemoteClaim :exec
UPDATE remote_deployment_claims SET state = 'cancelled', finished_at = unixepoch(), updated_at = unixepoch()
WHERE deployment_id = ? AND state = 'waiting'
`

func (q *Queries) CancelWaitingQueuedRemoteClaim(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, cancelWaitingQueuedRemoteClaim, deploymentID)
	return err
}

const createEnvironmentDeploymentSlot = `-- name: CreateEnvironmentDeploymentSlot :exec
INSERT INTO environment_deployment_slots (environment_id, project_id, deployment_id)
SELECT ?1, r.project_id, d.id FROM deployments d
JOIN releases r ON r.id=d.release_id WHERE d.id=?2
`

type CreateEnvironmentDeploymentSlotParams struct {
	EnvironmentID int64 `json:"environment_id"`
	DeploymentID  int64 `json:"deployment_id"`
}

func (q *Queries) CreateEnvironmentDeploymentSlot(ctx context.Context, arg CreateEnvironmentDeploymentSlotParams) error {
	_, err := q.db.ExecContext(ctx, createEnvironmentDeploymentSlot, arg.EnvironmentID, arg.DeploymentID)
	return err
}

const deleteDeploymentSlot = `-- name: DeleteDeploymentSlot :exec
DELETE FROM environment_deployment_slots WHERE deployment_id = ?
`

func (q *Queries) DeleteDeploymentSlot(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeploymentSlot, deploymentID)
	return err
}

const getDeploymentQueueState = `-- name: GetDeploymentQueueState :one
SELECT d.status,
    (SELECT COUNT(*) FROM deployments ahead
     WHERE d.status = 'queued' AND ahead.environment_id = d.environment_id
       AND ahead.status = 'queued'
       AND EXISTS (SELECT 1 FROM releases ahead_release JOIN releases own_release
           ON own_release.project_id=ahead_release.project_id
           WHERE ahead_release.id=ahead.release_id AND own_release.id=d.release_id)
       AND (ahead.created_at < d.created_at OR (ahead.created_at = d.created_at AND ahead.id <= d.id))) AS queue_position,
    active.id AS active_deployment_id, active.kind, r.project_id,
    x.id AS runbook_execution_id
FROM deployments d
JOIN releases own_release ON own_release.id=d.release_id
LEFT JOIN environment_deployment_slots s ON s.environment_id = d.environment_id AND s.project_id=own_release.project_id
LEFT JOIN deployments active ON active.id = s.deployment_id
    AND (CAST(?1 AS INTEGER) = 1 OR EXISTS (
        SELECT 1 FROM releases visible JOIN project_members m ON m.project_id = visible.project_id
        WHERE visible.id = active.release_id AND m.user_id = ?2))
LEFT JOIN releases r ON r.id = active.release_id
LEFT JOIN runbook_executions x ON x.deployment_id = active.id
WHERE d.id = ?3
`

type GetDeploymentQueueStateParams struct {
	IsAdmin      int64 `json:"is_admin"`
	UserID       int64 `json:"user_id"`
	DeploymentID int64 `json:"deployment_id"`
}

type GetDeploymentQueueStateRow struct {
	Status             string         `json:"status"`
	QueuePosition      int64          `json:"queue_position"`
	ActiveDeploymentID sql.NullInt64  `json:"active_deployment_id"`
	Kind               sql.NullString `json:"kind"`
	ProjectID          sql.NullInt64  `json:"project_id"`
	RunbookExecutionID sql.NullInt64  `json:"runbook_execution_id"`
}

func (q *Queries) GetDeploymentQueueState(ctx context.Context, arg GetDeploymentQueueStateParams) (GetDeploymentQueueStateRow, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentQueueState, arg.IsAdmin, arg.UserID, arg.DeploymentID)
	var i GetDeploymentQueueStateRow
	err := row.Scan(
		&i.Status,
		&i.QueuePosition,
		&i.ActiveDeploymentID,
		&i.Kind,
		&i.ProjectID,
		&i.RunbookExecutionID,
	)
	return i, err
}

const getDeploymentSlot = `-- name: GetDeploymentSlot :one
SELECT s.deployment_id FROM environment_deployment_slots s
JOIN deployments d ON d.environment_id=s.environment_id
JOIN releases r ON r.id=d.release_id AND r.project_id=s.project_id
WHERE d.id = ?
`

func (q *Queries) GetDeploymentSlot(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentSlot, id)
	var deployment_id int64
	err := row.Scan(&deployment_id)
	return deployment_id, err
}

const getNextQueuedDeployment = `-- name: GetNextQueuedDeployment :one
SELECT d.id FROM deployments d JOIN releases r ON r.id=d.release_id
JOIN deployments scope ON scope.environment_id=d.environment_id
JOIN releases scope_release ON scope_release.id=scope.release_id AND scope_release.project_id=r.project_id
WHERE scope.id = ? AND d.status = 'queued'
ORDER BY d.created_at, d.id LIMIT 1
`

func (q *Queries) GetNextQueuedDeployment(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextQueuedDeployment, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const listDeploymentQueueBlockers = `-- name: ListDeploymentQueueBlockers :many
SELECT d.id FROM deployments d JOIN releases r ON r.id=d.release_id
JOIN deployments scope ON scope.environment_id=d.environment_id
JOIN releases scope_release ON scope_release.id=scope.release_id AND scope_release.project_id=r.project_id
WHERE scope.id = ? AND (
    d.status IN ('pending', 'running', 'publishing_artifact', 'awaiting_artifact_approval')
    OR (d.status = 'cleanup_unconfirmed'
        AND (d.container_namespace IS NOT NULL OR (
        d.cleanup_confirmed_at IS NULL AND
        NOT EXISTS (SELECT 1 FROM remote_deployment_claims c
            WHERE c.deployment_id = d.id AND c.state = 'cleanup_unconfirmed')
        AND NOT EXISTS (SELECT 1 FROM remote_step_runs s
            WHERE s.deployment_id = d.id AND s.state = 'cleanup_unconfirmed'))))
    OR EXISTS (SELECT 1 FROM remote_deployment_claims c WHERE c.deployment_id = d.id
        AND c.state = 'cleanup_unconfirmed' AND c.cleanup_confirmed_at IS NULL)
    OR EXISTS (SELECT 1 FROM remote_step_runs s WHERE s.deployment_id = d.id
        AND s.state = 'cleanup_unconfirmed' AND s.cleanup_confirmed_at IS NULL)
    OR EXISTS (SELECT 1 FROM remote_deployment_claims c WHERE c.deployment_id = d.id
        AND c.state IN ('claimed', 'started', 'cancel_requested', 'lost', 'cancel_unconfirmed'))
    OR EXISTS (SELECT 1 FROM remote_step_runs s WHERE s.deployment_id = d.id
        AND s.state IN ('claimed', 'started', 'cancel_requested', 'lost', 'cancel_unconfirmed'))
)
ORDER BY d.created_at, d.id
`

func (q *Queries) ListDeploymentQueueBlockers(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentQueueBlockers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentQueueEnvironments = `-- name: ListDeploymentQueueEnvironments :many
SELECT environment_id FROM deployments WHERE status IN ('queued', 'pending', 'running', 'publishing_artifact', 'awaiting_artifact_approval', 'cleanup_unconfirmed')
UNION SELECT environment_id FROM environment_deployment_slots
ORDER BY environment_id
`

func (q *Queries) ListDeploymentQueueEnvironments(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentQueueEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var environment_id int64
		if err := rows.Scan(&environment_id); err != nil {
			return nil, err
		}
		items = append(items, environment_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentQueueProjects = `-- name: ListEnvironmentQueueProjects :many
SELECT CAST(MIN(d.id) AS INTEGER) AS deployment_id FROM deployments d
JOIN releases r ON r.id=d.release_id
WHERE d.environment_id = ?
AND (d.status IN ('queued','pending','running','publishing_artifact','awaiting_artifact_approval','cleanup_unconfirmed')
    OR EXISTS (SELECT 1 FROM environment_deployment_slots s WHERE s.deployment_id=d.id))
GROUP BY r.project_id ORDER BY r.project_id
`

func (q *Queries) ListEnvironmentQueueProjects(ctx context.Context, environmentID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironmentQueueProjects, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var deployment_id int64
		if err := rows.Scan(&deployment_id); err != nil {
			return nil, err
		}
		items = append(items, deployment_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeploymentEnvironment = `-- name: LockDeploymentEnvironment :execrows
UPDATE environments SET name = name -- NOSONAR: serialize queue transactions
WHERE id = ?
`

func (q *Queries) LockDeploymentEnvironment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockDeploymentEnvironment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startQueuedLocalDeployment = `-- name: StartQueuedLocalDeployment :execrows
UPDATE deployments SET status = 'running', started_at = COALESCE(started_at, unixepoch())
WHERE id = ? AND status = 'pending' AND assigned_agent_id IS NULL
AND EXISTS (SELECT 1 FROM environment_deployment_slots s
    WHERE s.deployment_id = deployments.id AND s.environment_id = deployments.environment_id)
`

func (q *Queries) StartQueuedLocalDeployment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, startQueuedLocalDeployment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
