// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_variable_snapshots.sql

package db

import (
	"context"
)

const createDeploymentVariableSnapshot = `-- name: CreateDeploymentVariableSnapshot :exec
INSERT INTO deployment_variable_snapshots (deployment_id, value) VALUES (?, ?)
`

type CreateDeploymentVariableSnapshotParams struct {
	DeploymentID int64  `json:"deployment_id"`
	Value        string `json:"value"`
}

func (q *Queries) CreateDeploymentVariableSnapshot(ctx context.Context, arg CreateDeploymentVariableSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, createDeploymentVariableSnapshot, arg.DeploymentID, arg.Value)
	return err
}

const getDeploymentVariableSnapshot = `-- name: GetDeploymentVariableSnapshot :one
SELECT deployment_id, value FROM deployment_variable_snapshots WHERE deployment_id = ?
`

func (q *Queries) GetDeploymentVariableSnapshot(ctx context.Context, deploymentID int64) (DeploymentVariableSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentVariableSnapshot, deploymentID)
	var i DeploymentVariableSnapshot
	err := row.Scan(&i.DeploymentID, &i.Value)
	return i, err
}

const listAllDeploymentVariableSnapshots = `-- name: ListAllDeploymentVariableSnapshots :many
SELECT deployment_id, value FROM deployment_variable_snapshots ORDER BY deployment_id
`

func (q *Queries) ListAllDeploymentVariableSnapshots(ctx context.Context) ([]DeploymentVariableSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listAllDeploymentVariableSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentVariableSnapshot
	for rows.Next() {
		var i DeploymentVariableSnapshot
		if err := rows.Scan(&i.DeploymentID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentVariableSnapshotValue = `-- name: UpdateDeploymentVariableSnapshotValue :exec
UPDATE deployment_variable_snapshots SET value = ? WHERE deployment_id = ?
`

type UpdateDeploymentVariableSnapshotValueParams struct {
	Value        string `json:"value"`
	DeploymentID int64  `json:"deployment_id"`
}

func (q *Queries) UpdateDeploymentVariableSnapshotValue(ctx context.Context, arg UpdateDeploymentVariableSnapshotValueParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentVariableSnapshotValue, arg.Value, arg.DeploymentID)
	return err
}
