// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package db

import (
	"context"
	"database/sql"
)

const countDeploymentsToday = `-- name: CountDeploymentsToday :one
SELECT COUNT(*) FROM deployments WHERE created_at >= strftime('%s','now','start of day')
`

func (q *Queries) CountDeploymentsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeploymentsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeploymentsWithRefsFiltered = `-- name: CountDeploymentsWithRefsFiltered :one
SELECT COUNT(*)
FROM deployments d
JOIN releases r ON d.release_id = r.id
JOIN projects p ON r.project_id = p.id
JOIN environments e ON d.environment_id = e.id
WHERE (CAST(?1 AS INTEGER) IS NULL OR d.release_id IN (SELECT id FROM releases WHERE project_id = CAST(?1 AS INTEGER)))
  AND (CAST(?2     AS INTEGER) IS NULL OR d.environment_id = CAST(?2 AS INTEGER))
  AND (CAST(?3     AS TEXT)    IS NULL OR d.status = CAST(?3 AS TEXT))
  AND (CAST(?4  AS INTEGER) IS NULL OR d.created_at >= CAST(?4 AS INTEGER))
  AND (CAST(?5    AS INTEGER) IS NULL OR d.created_at <= CAST(?5 AS INTEGER))
`

type CountDeploymentsWithRefsFilteredParams struct {
	FProjectID sql.NullInt64  `json:"f_project_id"`
	FEnvID     sql.NullInt64  `json:"f_env_id"`
	FStatus    sql.NullString `json:"f_status"`
	FFromUnix  sql.NullInt64  `json:"f_from_unix"`
	FToUnix    sql.NullInt64  `json:"f_to_unix"`
}

func (q *Queries) CountDeploymentsWithRefsFiltered(ctx context.Context, arg CountDeploymentsWithRefsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeploymentsWithRefsFiltered,
		arg.FProjectID,
		arg.FEnvID,
		arg.FStatus,
		arg.FFromUnix,
		arg.FToUnix,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (release_id, environment_id, status, started_at, finished_at, forced, note) VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, release_id, environment_id, status, started_at, finished_at, created_at, forced, note
`

type CreateDeploymentParams struct {
	ReleaseID     int64          `json:"release_id"`
	EnvironmentID int64          `json:"environment_id"`
	Status        string         `json:"status"`
	StartedAt     sql.NullInt64  `json:"started_at"`
	FinishedAt    sql.NullInt64  `json:"finished_at"`
	Forced        int64          `json:"forced"`
	Note          sql.NullString `json:"note"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.ReleaseID,
		arg.EnvironmentID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Forced,
		arg.Note,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.EnvironmentID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.Forced,
		&i.Note,
	)
	return i, err
}

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployments WHERE id = ?
`

func (q *Queries) DeleteDeployment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeployment, id)
	return err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, release_id, environment_id, status, started_at, finished_at, created_at, forced, note FROM deployments WHERE id = ?
`

func (q *Queries) GetDeployment(ctx context.Context, id int64) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.EnvironmentID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.Forced,
		&i.Note,
	)
	return i, err
}

const getLatestDeploymentForReleaseEnv = `-- name: GetLatestDeploymentForReleaseEnv :one
SELECT id, release_id, environment_id, status, started_at, finished_at, created_at, forced, note FROM deployments WHERE release_id = ? AND environment_id = ? ORDER BY created_at DESC LIMIT 1
`

type GetLatestDeploymentForReleaseEnvParams struct {
	ReleaseID     int64 `json:"release_id"`
	EnvironmentID int64 `json:"environment_id"`
}

func (q *Queries) GetLatestDeploymentForReleaseEnv(ctx context.Context, arg GetLatestDeploymentForReleaseEnvParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getLatestDeploymentForReleaseEnv, arg.ReleaseID, arg.EnvironmentID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.EnvironmentID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.Forced,
		&i.Note,
	)
	return i, err
}

const getLatestSuccessfulDeploymentForEnv = `-- name: GetLatestSuccessfulDeploymentForEnv :one
SELECT id, release_id, environment_id, status, started_at, finished_at, created_at, forced, note FROM deployments WHERE environment_id = ? AND status = 'succeeded' ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestSuccessfulDeploymentForEnv(ctx context.Context, environmentID int64) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getLatestSuccessfulDeploymentForEnv, environmentID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.EnvironmentID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.Forced,
		&i.Note,
	)
	return i, err
}

const getLatestSuccessfulDeploymentForReleaseEnv = `-- name: GetLatestSuccessfulDeploymentForReleaseEnv :one
SELECT id, release_id, environment_id, status, started_at, finished_at, created_at, forced, note FROM deployments WHERE release_id = ? AND environment_id = ? AND status = 'succeeded' ORDER BY created_at DESC LIMIT 1
`

type GetLatestSuccessfulDeploymentForReleaseEnvParams struct {
	ReleaseID     int64 `json:"release_id"`
	EnvironmentID int64 `json:"environment_id"`
}

func (q *Queries) GetLatestSuccessfulDeploymentForReleaseEnv(ctx context.Context, arg GetLatestSuccessfulDeploymentForReleaseEnvParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getLatestSuccessfulDeploymentForReleaseEnv, arg.ReleaseID, arg.EnvironmentID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.EnvironmentID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.Forced,
		&i.Note,
	)
	return i, err
}

const listDeployments = `-- name: ListDeployments :many
SELECT id, release_id, environment_id, status, started_at, finished_at, created_at, forced, note FROM deployments ORDER BY created_at DESC
`

func (q *Queries) ListDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.EnvironmentID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.Forced,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByRelease = `-- name: ListDeploymentsByRelease :many
SELECT id, release_id, environment_id, status, started_at, finished_at, created_at, forced, note FROM deployments WHERE release_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByRelease(ctx context.Context, releaseID int64) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsByRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.EnvironmentID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.Forced,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsWithRefs = `-- name: ListDeploymentsWithRefs :many
SELECT
    d.id, d.release_id, d.environment_id, d.status,
    d.started_at, d.finished_at, d.created_at, d.forced, d.note,
    p.name AS project_name,
    r.version AS release_version,
    e.name AS environment_name
FROM deployments d
JOIN releases r ON d.release_id = r.id
JOIN projects p ON r.project_id = p.id
JOIN environments e ON d.environment_id = e.id
ORDER BY d.created_at DESC
`

type ListDeploymentsWithRefsRow struct {
	ID              int64          `json:"id"`
	ReleaseID       int64          `json:"release_id"`
	EnvironmentID   int64          `json:"environment_id"`
	Status          string         `json:"status"`
	StartedAt       sql.NullInt64  `json:"started_at"`
	FinishedAt      sql.NullInt64  `json:"finished_at"`
	CreatedAt       int64          `json:"created_at"`
	Forced          int64          `json:"forced"`
	Note            sql.NullString `json:"note"`
	ProjectName     string         `json:"project_name"`
	ReleaseVersion  string         `json:"release_version"`
	EnvironmentName string         `json:"environment_name"`
}

func (q *Queries) ListDeploymentsWithRefs(ctx context.Context) ([]ListDeploymentsWithRefsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsWithRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeploymentsWithRefsRow
	for rows.Next() {
		var i ListDeploymentsWithRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.EnvironmentID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.Forced,
			&i.Note,
			&i.ProjectName,
			&i.ReleaseVersion,
			&i.EnvironmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsWithRefsFiltered = `-- name: ListDeploymentsWithRefsFiltered :many
SELECT
    d.id, d.release_id, d.environment_id, d.status,
    d.started_at, d.finished_at, d.created_at, d.forced, d.note,
    p.name AS project_name,
    r.version AS release_version,
    e.name AS environment_name
FROM deployments d
JOIN releases r ON d.release_id = r.id
JOIN projects p ON r.project_id = p.id
JOIN environments e ON d.environment_id = e.id
WHERE (CAST(?1 AS INTEGER) IS NULL OR d.release_id IN (SELECT id FROM releases WHERE project_id = CAST(?1 AS INTEGER)))
  AND (CAST(?2     AS INTEGER) IS NULL OR d.environment_id = CAST(?2 AS INTEGER))
  AND (CAST(?3     AS TEXT)    IS NULL OR d.status = CAST(?3 AS TEXT))
  AND (CAST(?4  AS INTEGER) IS NULL OR d.created_at >= CAST(?4 AS INTEGER))
  AND (CAST(?5    AS INTEGER) IS NULL OR d.created_at <= CAST(?5 AS INTEGER))
ORDER BY d.created_at DESC
LIMIT ?7 OFFSET ?6
`

type ListDeploymentsWithRefsFilteredParams struct {
	FProjectID sql.NullInt64  `json:"f_project_id"`
	FEnvID     sql.NullInt64  `json:"f_env_id"`
	FStatus    sql.NullString `json:"f_status"`
	FFromUnix  sql.NullInt64  `json:"f_from_unix"`
	FToUnix    sql.NullInt64  `json:"f_to_unix"`
	PageOffset int64          `json:"page_offset"`
	PageLimit  int64          `json:"page_limit"`
}

type ListDeploymentsWithRefsFilteredRow struct {
	ID              int64          `json:"id"`
	ReleaseID       int64          `json:"release_id"`
	EnvironmentID   int64          `json:"environment_id"`
	Status          string         `json:"status"`
	StartedAt       sql.NullInt64  `json:"started_at"`
	FinishedAt      sql.NullInt64  `json:"finished_at"`
	CreatedAt       int64          `json:"created_at"`
	Forced          int64          `json:"forced"`
	Note            sql.NullString `json:"note"`
	ProjectName     string         `json:"project_name"`
	ReleaseVersion  string         `json:"release_version"`
	EnvironmentName string         `json:"environment_name"`
}

func (q *Queries) ListDeploymentsWithRefsFiltered(ctx context.Context, arg ListDeploymentsWithRefsFilteredParams) ([]ListDeploymentsWithRefsFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsWithRefsFiltered,
		arg.FProjectID,
		arg.FEnvID,
		arg.FStatus,
		arg.FFromUnix,
		arg.FToUnix,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeploymentsWithRefsFilteredRow
	for rows.Next() {
		var i ListDeploymentsWithRefsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.EnvironmentID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.Forced,
			&i.Note,
			&i.ProjectName,
			&i.ReleaseVersion,
			&i.EnvironmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestDeploymentPerReleaseEnv = `-- name: ListLatestDeploymentPerReleaseEnv :many
SELECT id, release_id, environment_id, status, started_at, finished_at, created_at, forced, note, project_name, release_version, environment_name
FROM (
    SELECT d.id, d.release_id, d.environment_id, d.status, d.started_at, d.finished_at, d.created_at, d.forced, d.note,
           p.name AS project_name, r.version AS release_version, e.name AS environment_name,
           ROW_NUMBER() OVER (PARTITION BY d.release_id, d.environment_id ORDER BY d.created_at DESC) AS rn
    FROM deployments d
    JOIN releases r ON d.release_id = r.id
    JOIN projects p ON r.project_id = p.id
    JOIN environments e ON d.environment_id = e.id
) WHERE rn = 1 ORDER BY created_at DESC
`

type ListLatestDeploymentPerReleaseEnvRow struct {
	ID              int64          `json:"id"`
	ReleaseID       int64          `json:"release_id"`
	EnvironmentID   int64          `json:"environment_id"`
	Status          string         `json:"status"`
	StartedAt       sql.NullInt64  `json:"started_at"`
	FinishedAt      sql.NullInt64  `json:"finished_at"`
	CreatedAt       int64          `json:"created_at"`
	Forced          int64          `json:"forced"`
	Note            sql.NullString `json:"note"`
	ProjectName     string         `json:"project_name"`
	ReleaseVersion  string         `json:"release_version"`
	EnvironmentName string         `json:"environment_name"`
}

func (q *Queries) ListLatestDeploymentPerReleaseEnv(ctx context.Context) ([]ListLatestDeploymentPerReleaseEnvRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestDeploymentPerReleaseEnv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestDeploymentPerReleaseEnvRow
	for rows.Next() {
		var i ListLatestDeploymentPerReleaseEnvRow
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.EnvironmentID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.Forced,
			&i.Note,
			&i.ProjectName,
			&i.ReleaseVersion,
			&i.EnvironmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeployments = `-- name: ListRecentDeployments :many
SELECT id, release_id, environment_id, status, started_at, finished_at, created_at, forced, note FROM deployments ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListRecentDeployments(ctx context.Context, limit int64) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listRecentDeployments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.EnvironmentID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.Forced,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeploymentsForEnv = `-- name: ListRecentDeploymentsForEnv :many
SELECT id, release_id, environment_id, status, started_at, finished_at, created_at, forced, note FROM deployments WHERE environment_id = ? ORDER BY created_at DESC LIMIT ?
`

type ListRecentDeploymentsForEnvParams struct {
	EnvironmentID int64 `json:"environment_id"`
	Limit         int64 `json:"limit"`
}

func (q *Queries) ListRecentDeploymentsForEnv(ctx context.Context, arg ListRecentDeploymentsForEnvParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listRecentDeploymentsForEnv, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.EnvironmentID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.Forced,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningDeploymentsWithRefs = `-- name: ListRunningDeploymentsWithRefs :many
SELECT
    d.id, d.release_id, d.environment_id, d.status,
    d.started_at, d.finished_at, d.created_at, d.forced, d.note,
    p.name AS project_name,
    r.version AS release_version,
    e.name AS environment_name
FROM deployments d
JOIN releases r ON d.release_id = r.id
JOIN projects p ON r.project_id = p.id
JOIN environments e ON d.environment_id = e.id
WHERE d.status IN ('pending','running')
ORDER BY d.created_at DESC
`

type ListRunningDeploymentsWithRefsRow struct {
	ID              int64          `json:"id"`
	ReleaseID       int64          `json:"release_id"`
	EnvironmentID   int64          `json:"environment_id"`
	Status          string         `json:"status"`
	StartedAt       sql.NullInt64  `json:"started_at"`
	FinishedAt      sql.NullInt64  `json:"finished_at"`
	CreatedAt       int64          `json:"created_at"`
	Forced          int64          `json:"forced"`
	Note            sql.NullString `json:"note"`
	ProjectName     string         `json:"project_name"`
	ReleaseVersion  string         `json:"release_version"`
	EnvironmentName string         `json:"environment_name"`
}

func (q *Queries) ListRunningDeploymentsWithRefs(ctx context.Context) ([]ListRunningDeploymentsWithRefsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunningDeploymentsWithRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunningDeploymentsWithRefsRow
	for rows.Next() {
		var i ListRunningDeploymentsWithRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.EnvironmentID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.Forced,
			&i.Note,
			&i.ProjectName,
			&i.ReleaseVersion,
			&i.EnvironmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeployment = `-- name: UpdateDeployment :one
UPDATE deployments SET release_id = ?, environment_id = ?, status = ?, started_at = ?, finished_at = ?, note = ? WHERE id = ? RETURNING id, release_id, environment_id, status, started_at, finished_at, created_at, forced, note
`

type UpdateDeploymentParams struct {
	ReleaseID     int64          `json:"release_id"`
	EnvironmentID int64          `json:"environment_id"`
	Status        string         `json:"status"`
	StartedAt     sql.NullInt64  `json:"started_at"`
	FinishedAt    sql.NullInt64  `json:"finished_at"`
	Note          sql.NullString `json:"note"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, updateDeployment,
		arg.ReleaseID,
		arg.EnvironmentID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Note,
		arg.ID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.EnvironmentID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.Forced,
		&i.Note,
	)
	return i, err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments SET status = ?, started_at = ?, finished_at = ? WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status     string        `json:"status"`
	StartedAt  sql.NullInt64 `json:"started_at"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
	ID         int64         `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
