// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_approvals.sql

package db

import (
	"context"
	"database/sql"
)

const createApproval = `-- name: CreateApproval :one
INSERT INTO deployment_approvals (deployment_id, approved_by, approver_user_id, required_approver_role) VALUES (?, ?, ?, ?) RETURNING id, deployment_id, approved_by, approved_at, approver_user_id, required_approver_role
`

type CreateApprovalParams struct {
	DeploymentID         int64         `json:"deployment_id"`
	ApprovedBy           string        `json:"approved_by"`
	ApproverUserID       sql.NullInt64 `json:"approver_user_id"`
	RequiredApproverRole string        `json:"required_approver_role"`
}

func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (DeploymentApproval, error) {
	row := q.db.QueryRowContext(ctx, createApproval,
		arg.DeploymentID,
		arg.ApprovedBy,
		arg.ApproverUserID,
		arg.RequiredApproverRole,
	)
	var i DeploymentApproval
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ApproverUserID,
		&i.RequiredApproverRole,
	)
	return i, err
}

const getApprovalByDeployment = `-- name: GetApprovalByDeployment :one
SELECT id, deployment_id, approved_by, approved_at, approver_user_id, required_approver_role FROM deployment_approvals WHERE deployment_id = ? ORDER BY approved_at ASC LIMIT 1
`

func (q *Queries) GetApprovalByDeployment(ctx context.Context, deploymentID int64) (DeploymentApproval, error) {
	row := q.db.QueryRowContext(ctx, getApprovalByDeployment, deploymentID)
	var i DeploymentApproval
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ApproverUserID,
		&i.RequiredApproverRole,
	)
	return i, err
}
