// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_queue.sql

package db

import (
	"context"
	"database/sql"
)

const admitQueuedDeployment = `-- name: AdmitQueuedDeployment :execrows
UPDATE deployments SET status = 'pending' WHERE id = ? AND status = 'queued'
`

func (q *Queries) AdmitQueuedDeployment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, admitQueuedDeployment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelQueuedDeployment = `-- name: CancelQueuedDeployment :execrows
UPDATE deployments SET status = 'cancelled', finished_at = unixepoch()
WHERE id = ? AND status IN ('queued', 'pending_approval', 'pending')
AND NOT EXISTS (SELECT 1 FROM remote_deployment_claims c WHERE c.deployment_id = deployments.id
    AND c.state NOT IN ('waiting', 'cancelled'))
`

func (q *Queries) CancelQueuedDeployment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelQueuedDeployment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelWaitingQueuedRemoteClaim = `-- name: CancelWaitingQueuedRemoteClaim :exec
UPDATE remote_deployment_claims SET state = 'cancelled', finished_at = unixepoch(), updated_at = unixepoch()
WHERE deployment_id = ? AND state = 'waiting'
`

func (q *Queries) CancelWaitingQueuedRemoteClaim(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, cancelWaitingQueuedRemoteClaim, deploymentID)
	return err
}

const createEnvironmentDeploymentSlot = `-- name: CreateEnvironmentDeploymentSlot :exec
INSERT INTO environment_deployment_slots (environment_id, deployment_id) VALUES (?, ?)
`

type CreateEnvironmentDeploymentSlotParams struct {
	EnvironmentID int64 `json:"environment_id"`
	DeploymentID  int64 `json:"deployment_id"`
}

func (q *Queries) CreateEnvironmentDeploymentSlot(ctx context.Context, arg CreateEnvironmentDeploymentSlotParams) error {
	_, err := q.db.ExecContext(ctx, createEnvironmentDeploymentSlot, arg.EnvironmentID, arg.DeploymentID)
	return err
}

const deleteEnvironmentDeploymentSlot = `-- name: DeleteEnvironmentDeploymentSlot :exec
DELETE FROM environment_deployment_slots WHERE environment_id = ?
`

func (q *Queries) DeleteEnvironmentDeploymentSlot(ctx context.Context, environmentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEnvironmentDeploymentSlot, environmentID)
	return err
}

const getDeploymentQueuePosition = `-- name: GetDeploymentQueuePosition :one
SELECT COUNT(*) FROM deployments ahead JOIN deployments target ON target.id = ?1
WHERE target.status = 'queued' AND ahead.environment_id = target.environment_id
AND ahead.status = 'queued'
AND (ahead.created_at < target.created_at OR (ahead.created_at = target.created_at AND ahead.id <= target.id))
`

func (q *Queries) GetDeploymentQueuePosition(ctx context.Context, deploymentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentQueuePosition, deploymentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEnvironmentDeploymentSlot = `-- name: GetEnvironmentDeploymentSlot :one
SELECT deployment_id FROM environment_deployment_slots WHERE environment_id = ?
`

func (q *Queries) GetEnvironmentDeploymentSlot(ctx context.Context, environmentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentDeploymentSlot, environmentID)
	var deployment_id int64
	err := row.Scan(&deployment_id)
	return deployment_id, err
}

const getNextQueuedDeployment = `-- name: GetNextQueuedDeployment :one
SELECT id FROM deployments WHERE environment_id = ? AND status = 'queued'
ORDER BY created_at, id LIMIT 1
`

func (q *Queries) GetNextQueuedDeployment(ctx context.Context, environmentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextQueuedDeployment, environmentID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getVisibleEnvironmentDeploymentSlot = `-- name: GetVisibleEnvironmentDeploymentSlot :one
SELECT d.id, d.kind, r.project_id, x.id AS runbook_execution_id
FROM environment_deployment_slots s
JOIN deployments d ON d.id = s.deployment_id
JOIN releases r ON r.id = d.release_id
LEFT JOIN runbook_executions x ON x.deployment_id = d.id
WHERE s.environment_id = ?1
AND (CAST(?2 AS INTEGER) = 1 OR EXISTS (
    SELECT 1 FROM project_members p WHERE p.project_id = r.project_id AND p.user_id = ?3))
`

type GetVisibleEnvironmentDeploymentSlotParams struct {
	EnvironmentID int64 `json:"environment_id"`
	IsAdmin       int64 `json:"is_admin"`
	UserID        int64 `json:"user_id"`
}

type GetVisibleEnvironmentDeploymentSlotRow struct {
	ID                 int64         `json:"id"`
	Kind               string        `json:"kind"`
	ProjectID          int64         `json:"project_id"`
	RunbookExecutionID sql.NullInt64 `json:"runbook_execution_id"`
}

func (q *Queries) GetVisibleEnvironmentDeploymentSlot(ctx context.Context, arg GetVisibleEnvironmentDeploymentSlotParams) (GetVisibleEnvironmentDeploymentSlotRow, error) {
	row := q.db.QueryRowContext(ctx, getVisibleEnvironmentDeploymentSlot, arg.EnvironmentID, arg.IsAdmin, arg.UserID)
	var i GetVisibleEnvironmentDeploymentSlotRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProjectID,
		&i.RunbookExecutionID,
	)
	return i, err
}

const listDeploymentQueueEnvironments = `-- name: ListDeploymentQueueEnvironments :many
SELECT environment_id FROM deployments WHERE status IN ('queued', 'pending', 'running', 'cleanup_unconfirmed')
UNION SELECT environment_id FROM environment_deployment_slots
ORDER BY environment_id
`

func (q *Queries) ListDeploymentQueueEnvironments(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentQueueEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var environment_id int64
		if err := rows.Scan(&environment_id); err != nil {
			return nil, err
		}
		items = append(items, environment_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentQueueBlockers = `-- name: ListEnvironmentQueueBlockers :many
SELECT d.id FROM deployments d
WHERE d.environment_id = ? AND (
    d.status IN ('pending', 'running', 'cleanup_unconfirmed')
    OR EXISTS (SELECT 1 FROM remote_deployment_claims c WHERE c.deployment_id = d.id
        AND c.state IN ('claimed', 'started', 'cancel_requested', 'lost', 'cancel_unconfirmed'))
    OR EXISTS (SELECT 1 FROM remote_step_runs s WHERE s.deployment_id = d.id
        AND s.state IN ('claimed', 'started', 'cancel_requested', 'lost', 'cancel_unconfirmed'))
)
ORDER BY d.created_at, d.id
`

func (q *Queries) ListEnvironmentQueueBlockers(ctx context.Context, environmentID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironmentQueueBlockers, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeploymentEnvironment = `-- name: LockDeploymentEnvironment :execrows
UPDATE environments SET name = name -- NOSONAR: serialize queue transactions
WHERE id = ?
`

func (q *Queries) LockDeploymentEnvironment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockDeploymentEnvironment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startQueuedLocalDeployment = `-- name: StartQueuedLocalDeployment :execrows
UPDATE deployments SET status = 'running', started_at = unixepoch()
WHERE id = ? AND status = 'pending' AND assigned_agent_id IS NULL
AND EXISTS (SELECT 1 FROM environment_deployment_slots s
    WHERE s.deployment_id = deployments.id AND s.environment_id = deployments.environment_id)
`

func (q *Queries) StartQueuedLocalDeployment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, startQueuedLocalDeployment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
