// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_state.sql

package db

import (
	"context"
	"database/sql"
)

const approveDeploymentStatus = `-- name: ApproveDeploymentStatus :execrows
UPDATE deployments SET status = 'pending'
WHERE id = ?1 AND status = 'pending_approval'
`

func (q *Queries) ApproveDeploymentStatus(ctx context.Context, deploymentID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, approveDeploymentStatus, deploymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelStepDeployment = `-- name: CancelStepDeployment :execrows
UPDATE deployments SET status = 'cancelled', finished_at = unixepoch()
WHERE id = ? AND status IN ('pending', 'running')
`

func (q *Queries) CancelStepDeployment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelStepDeployment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const lockAssignedRemoteDeployment = `-- name: LockAssignedRemoteDeployment :execrows
UPDATE deployments SET status = status
WHERE id = ?1
  AND assigned_agent_id = ?2
`

type LockAssignedRemoteDeploymentParams struct {
	DeploymentID int64          `json:"deployment_id"`
	AgentID      sql.NullString `json:"agent_id"`
}

func (q *Queries) LockAssignedRemoteDeployment(ctx context.Context, arg LockAssignedRemoteDeploymentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockAssignedRemoteDeployment, arg.DeploymentID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const lockDeploymentApproval = `-- name: LockDeploymentApproval :execrows
UPDATE deployments SET status = status
WHERE id = ?1 AND status = 'pending_approval'
`

func (q *Queries) LockDeploymentApproval(ctx context.Context, deploymentID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockDeploymentApproval, deploymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const lockDeploymentSnapshot = `-- name: LockDeploymentSnapshot :execrows
UPDATE deployments SET status = status WHERE id = ?1 AND status IN ('pending', 'pending_approval')
AND NOT EXISTS (SELECT 1 FROM deployment_step_sources WHERE deployment_id = ?1)
AND NOT EXISTS (SELECT 1 FROM deployment_steps WHERE deployment_id = ?1)
`

func (q *Queries) LockDeploymentSnapshot(ctx context.Context, deploymentID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockDeploymentSnapshot, deploymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const replaceDeploymentDispatch = `-- name: ReplaceDeploymentDispatch :execrows
UPDATE deployment_dispatches SET ciphertext = ?1, updated_at = unixepoch()
WHERE deployment_dispatches.deployment_id = ?2 AND deployment_dispatches.step_index = ?3 AND deployment_dispatches.attempt = ?4
AND EXISTS (SELECT 1 FROM deployment_step_attempts a
    WHERE a.deployment_id = deployment_dispatches.deployment_id AND a.step_index = deployment_dispatches.step_index
    AND a.attempt = deployment_dispatches.attempt AND a.agent_id = ?5
    AND a.claim_token_hash = ?6 AND a.state = 'claimed')
`

type ReplaceDeploymentDispatchParams struct {
	Ciphertext     sql.NullString `json:"ciphertext"`
	DeploymentID   int64          `json:"deployment_id"`
	StepIndex      int64          `json:"step_index"`
	Attempt        int64          `json:"attempt"`
	AgentID        sql.NullString `json:"agent_id"`
	ClaimTokenHash []byte         `json:"claim_token_hash"`
}

func (q *Queries) ReplaceDeploymentDispatch(ctx context.Context, arg ReplaceDeploymentDispatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, replaceDeploymentDispatch,
		arg.Ciphertext,
		arg.DeploymentID,
		arg.StepIndex,
		arg.Attempt,
		arg.AgentID,
		arg.ClaimTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
