// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_logs.sql

package db

import (
	"context"
	"database/sql"
)

const createDeploymentLog = `-- name: CreateDeploymentLog :one
INSERT INTO deployment_logs (deployment_id, step_name, line) VALUES (?, ?, ?) RETURNING id, deployment_id, step_name, line, created_at
`

type CreateDeploymentLogParams struct {
	DeploymentID int64          `json:"deployment_id"`
	StepName     sql.NullString `json:"step_name"`
	Line         string         `json:"line"`
}

func (q *Queries) CreateDeploymentLog(ctx context.Context, arg CreateDeploymentLogParams) (DeploymentLog, error) {
	row := q.db.QueryRowContext(ctx, createDeploymentLog, arg.DeploymentID, arg.StepName, arg.Line)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.StepName,
		&i.Line,
		&i.CreatedAt,
	)
	return i, err
}

const createDeploymentLogScope = `-- name: CreateDeploymentLogScope :exec
INSERT INTO deployment_log_scopes (log_id, deployment_id, step_index, attempt, sequence)
VALUES (?, ?, ?, ?, ?)
`

type CreateDeploymentLogScopeParams struct {
	LogID        int64         `json:"log_id"`
	DeploymentID int64         `json:"deployment_id"`
	StepIndex    sql.NullInt64 `json:"step_index"`
	Attempt      sql.NullInt64 `json:"attempt"`
	Sequence     int64         `json:"sequence"`
}

func (q *Queries) CreateDeploymentLogScope(ctx context.Context, arg CreateDeploymentLogScopeParams) error {
	_, err := q.db.ExecContext(ctx, createDeploymentLogScope,
		arg.LogID,
		arg.DeploymentID,
		arg.StepIndex,
		arg.Attempt,
		arg.Sequence,
	)
	return err
}

const createRemoteDeploymentLog = `-- name: CreateRemoteDeploymentLog :one
INSERT INTO deployment_logs (deployment_id, step_name, line, created_at)
VALUES (?, NULL, ?, ?) RETURNING id, deployment_id, step_name, line, created_at
`

type CreateRemoteDeploymentLogParams struct {
	DeploymentID int64  `json:"deployment_id"`
	Line         string `json:"line"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) CreateRemoteDeploymentLog(ctx context.Context, arg CreateRemoteDeploymentLogParams) (DeploymentLog, error) {
	row := q.db.QueryRowContext(ctx, createRemoteDeploymentLog, arg.DeploymentID, arg.Line, arg.CreatedAt)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.StepName,
		&i.Line,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeploymentLog = `-- name: DeleteDeploymentLog :exec
DELETE FROM deployment_logs WHERE id = ?
`

func (q *Queries) DeleteDeploymentLog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeploymentLog, id)
	return err
}

const getDeploymentLog = `-- name: GetDeploymentLog :one
SELECT id, deployment_id, step_name, line, created_at FROM deployment_logs WHERE id = ?
`

func (q *Queries) GetDeploymentLog(ctx context.Context, id int64) (DeploymentLog, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentLog, id)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.StepName,
		&i.Line,
		&i.CreatedAt,
	)
	return i, err
}

const getLastRemoteDeploymentLogSequence = `-- name: GetLastRemoteDeploymentLogSequence :one
SELECT CAST(COALESCE(MAX(sequence), -1) AS INTEGER) FROM deployment_log_scopes
WHERE deployment_id = ? AND step_index IS NULL
`

func (q *Queries) GetLastRemoteDeploymentLogSequence(ctx context.Context, deploymentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLastRemoteDeploymentLogSequence, deploymentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getRemoteDeploymentLogBySequence = `-- name: GetRemoteDeploymentLogBySequence :one
SELECT l.id, l.deployment_id, l.step_name, l.line, l.created_at FROM deployment_logs l
JOIN deployment_log_scopes s ON s.log_id = l.id AND s.deployment_id = l.deployment_id
WHERE s.deployment_id = ? AND s.step_index IS NULL AND s.attempt IS NULL
    AND s.sequence = ?
`

type GetRemoteDeploymentLogBySequenceParams struct {
	DeploymentID int64 `json:"deployment_id"`
	Sequence     int64 `json:"sequence"`
}

func (q *Queries) GetRemoteDeploymentLogBySequence(ctx context.Context, arg GetRemoteDeploymentLogBySequenceParams) (DeploymentLog, error) {
	row := q.db.QueryRowContext(ctx, getRemoteDeploymentLogBySequence, arg.DeploymentID, arg.Sequence)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.StepName,
		&i.Line,
		&i.CreatedAt,
	)
	return i, err
}

const getScopedDeploymentLog = `-- name: GetScopedDeploymentLog :one
SELECT l.id, l.deployment_id, l.step_name, l.line, l.created_at FROM deployment_logs l JOIN deployment_log_scopes s ON s.log_id = l.id AND s.deployment_id = l.deployment_id
WHERE s.deployment_id = ? AND s.step_index = ? AND s.attempt = ? AND s.sequence = ?
`

type GetScopedDeploymentLogParams struct {
	DeploymentID int64         `json:"deployment_id"`
	StepIndex    sql.NullInt64 `json:"step_index"`
	Attempt      sql.NullInt64 `json:"attempt"`
	Sequence     int64         `json:"sequence"`
}

func (q *Queries) GetScopedDeploymentLog(ctx context.Context, arg GetScopedDeploymentLogParams) (DeploymentLog, error) {
	row := q.db.QueryRowContext(ctx, getScopedDeploymentLog,
		arg.DeploymentID,
		arg.StepIndex,
		arg.Attempt,
		arg.Sequence,
	)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.StepName,
		&i.Line,
		&i.CreatedAt,
	)
	return i, err
}

const listDeploymentLogsByDeployment = `-- name: ListDeploymentLogsByDeployment :many
SELECT l.id, l.deployment_id, l.step_name, l.line, l.created_at FROM deployment_logs l
LEFT JOIN deployment_log_scopes s ON s.log_id = l.id
WHERE l.deployment_id = ?
ORDER BY CASE
    WHEN s.step_index IS NULL AND s.attempt IS NULL THEN 0 ELSE 1
END,
CASE
    WHEN s.step_index IS NULL AND s.attempt IS NULL THEN s.sequence
END,
l.created_at DESC, l.id DESC
`

func (q *Queries) ListDeploymentLogsByDeployment(ctx context.Context, deploymentID int64) ([]DeploymentLog, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentLogsByDeployment, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentLog
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.StepName,
			&i.Line,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentLog = `-- name: UpdateDeploymentLog :one
UPDATE deployment_logs SET deployment_id = ?, step_name = ?, line = ? WHERE id = ? RETURNING id, deployment_id, step_name, line, created_at
`

type UpdateDeploymentLogParams struct {
	DeploymentID int64          `json:"deployment_id"`
	StepName     sql.NullString `json:"step_name"`
	Line         string         `json:"line"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateDeploymentLog(ctx context.Context, arg UpdateDeploymentLogParams) (DeploymentLog, error) {
	row := q.db.QueryRowContext(ctx, updateDeploymentLog,
		arg.DeploymentID,
		arg.StepName,
		arg.Line,
		arg.ID,
	)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.StepName,
		&i.Line,
		&i.CreatedAt,
	)
	return i, err
}

const updateRemoteDeploymentLogBuffer = `-- name: UpdateRemoteDeploymentLogBuffer :execrows
UPDATE remote_deployment_claims
SET log_buffer_ciphertext = ?1
WHERE deployment_id = ?2
  AND agent_id = ?3
  AND claim_token_hash = ?4
`

type UpdateRemoteDeploymentLogBufferParams struct {
	LogBufferCiphertext sql.NullString `json:"log_buffer_ciphertext"`
	DeploymentID        int64          `json:"deployment_id"`
	AgentID             string         `json:"agent_id"`
	ClaimTokenHash      []byte         `json:"claim_token_hash"`
}

func (q *Queries) UpdateRemoteDeploymentLogBuffer(ctx context.Context, arg UpdateRemoteDeploymentLogBufferParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRemoteDeploymentLogBuffer,
		arg.LogBufferCiphertext,
		arg.DeploymentID,
		arg.AgentID,
		arg.ClaimTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
