// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_agent_wait.sql

package db

import (
	"context"
)

const deploymentWaitingForAgents = `-- name: DeploymentWaitingForAgents :one
SELECT CAST(CASE WHEN d.status IN ('pending', 'running')
    AND (
        EXISTS (SELECT 1 FROM remote_step_runs r
            WHERE r.deployment_id = d.id AND r.state = 'waiting')
        OR EXISTS (SELECT 1 FROM remote_deployment_claims c
            WHERE c.deployment_id = d.id AND c.state = 'waiting')
    )
    AND NOT (
        EXISTS (SELECT 1 FROM remote_step_runs r
            WHERE r.deployment_id = d.id
              AND r.state IN ('claimed', 'started', 'cancel_requested'))
        OR EXISTS (SELECT 1 FROM remote_deployment_claims c
            WHERE c.deployment_id = d.id
              AND c.state IN ('claimed', 'started', 'cancel_requested'))
    )
    THEN 1 ELSE 0 END AS INTEGER) AS waiting_for_agents
FROM deployments d WHERE d.id = ?1
`

func (q *Queries) DeploymentWaitingForAgents(ctx context.Context, deploymentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deploymentWaitingForAgents, deploymentID)
	var waiting_for_agents int64
	err := row.Scan(&waiting_for_agents)
	return waiting_for_agents, err
}
