// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_steps.sql

package db

import (
	"context"
	"database/sql"
)

const addDeploymentStepSelector = `-- name: AddDeploymentStepSelector :execrows
INSERT INTO deployment_step_selectors (deployment_id, step_index, label)
SELECT ?1, ?2, ?3
WHERE EXISTS (SELECT 1 FROM deployments WHERE id = ?1 AND status IN ('pending', 'pending_approval'))
  AND NOT EXISTS (SELECT 1 FROM deployment_step_sources WHERE deployment_id = ?1)
  AND NOT EXISTS (SELECT 1 FROM deployment_step_attempts WHERE deployment_id = ?1)
`

type AddDeploymentStepSelectorParams struct {
	DeploymentID int64  `json:"deployment_id"`
	StepIndex    int64  `json:"step_index"`
	Label        string `json:"label"`
}

func (q *Queries) AddDeploymentStepSelector(ctx context.Context, arg AddDeploymentStepSelectorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addDeploymentStepSelector, arg.DeploymentID, arg.StepIndex, arg.Label)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createDeploymentStep = `-- name: CreateDeploymentStep :execrows
INSERT INTO deployment_steps (deployment_id, step_index, source_step_id, name, script_body, timeout_seconds, max_retries, execution_target, interpreter)
SELECT ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    COALESCE(NULLIF(CAST(?9 AS TEXT), ''), 'bash')
WHERE EXISTS (SELECT 1 FROM deployments WHERE id = ?1 AND status IN ('pending', 'pending_approval'))
  AND NOT EXISTS (SELECT 1 FROM deployment_step_sources WHERE deployment_id = ?1)
  AND NOT EXISTS (SELECT 1 FROM deployment_step_attempts WHERE deployment_id = ?1)
`

type CreateDeploymentStepParams struct {
	DeploymentID    int64         `json:"deployment_id"`
	StepIndex       int64         `json:"step_index"`
	SourceStepID    sql.NullInt64 `json:"source_step_id"`
	Name            string        `json:"name"`
	ScriptBody      string        `json:"script_body"`
	TimeoutSeconds  int64         `json:"timeout_seconds"`
	MaxRetries      int64         `json:"max_retries"`
	ExecutionTarget string        `json:"execution_target"`
	Interpreter     string        `json:"interpreter"`
}

func (q *Queries) CreateDeploymentStep(ctx context.Context, arg CreateDeploymentStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createDeploymentStep,
		arg.DeploymentID,
		arg.StepIndex,
		arg.SourceStepID,
		arg.Name,
		arg.ScriptBody,
		arg.TimeoutSeconds,
		arg.MaxRetries,
		arg.ExecutionTarget,
		arg.Interpreter,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createDeploymentStepAttempt = `-- name: CreateDeploymentStepAttempt :execrows
INSERT INTO deployment_step_attempts (deployment_id, step_index, attempt, wait_deadline)
SELECT s.deployment_id, s.step_index, ?1, ?2
FROM deployment_steps s JOIN deployments d ON d.id = s.deployment_id
WHERE s.deployment_id = ?3 AND s.step_index = ?4
  AND d.status IN ('pending', 'running') AND ?2 > CAST(?5 AS INTEGER)
  AND CAST(?1 AS INTEGER) > 0 AND ?1 <= s.max_retries + 1
  AND NOT EXISTS (SELECT 1 FROM deployment_steps earlier WHERE earlier.deployment_id = s.deployment_id
      AND earlier.step_index < s.step_index AND NOT EXISTS (SELECT 1 FROM deployment_step_attempts done
          WHERE done.deployment_id = earlier.deployment_id AND done.step_index = earlier.step_index AND done.state = 'succeeded'))
  AND ?1 = 1 + (SELECT COUNT(*) FROM deployment_step_attempts a
      WHERE a.deployment_id = s.deployment_id AND a.step_index = s.step_index)
  AND NOT EXISTS (SELECT 1 FROM deployment_step_attempts a WHERE a.deployment_id = s.deployment_id
      AND a.step_index = s.step_index AND a.state != 'failed')
`

type CreateDeploymentStepAttemptParams struct {
	Attempt      int64 `json:"attempt"`
	WaitDeadline int64 `json:"wait_deadline"`
	DeploymentID int64 `json:"deployment_id"`
	StepIndex    int64 `json:"step_index"`
	Now          int64 `json:"now"`
}

func (q *Queries) CreateDeploymentStepAttempt(ctx context.Context, arg CreateDeploymentStepAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createDeploymentStepAttempt,
		arg.Attempt,
		arg.WaitDeadline,
		arg.DeploymentID,
		arg.StepIndex,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishCompletedDeployment = `-- name: FinishCompletedDeployment :execrows
UPDATE deployments SET status = 'succeeded', finished_at = unixepoch()
WHERE id = ?1 AND status IN ('pending', 'running')
  AND NOT EXISTS (SELECT 1 FROM deployment_steps s WHERE s.deployment_id = deployments.id
      AND NOT EXISTS (SELECT 1 FROM deployment_step_attempts a WHERE a.deployment_id = s.deployment_id
          AND a.step_index = s.step_index AND a.state = 'succeeded'))
`

func (q *Queries) FinishCompletedDeployment(ctx context.Context, deploymentID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishCompletedDeployment, deploymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishLocalDeploymentStep = `-- name: FinishLocalDeploymentStep :execrows
UPDATE deployment_step_attempts SET state = ?1, reason = ?2,
    finished_at = ?3, updated_at = ?3
WHERE deployment_step_attempts.deployment_id = ?4 AND deployment_step_attempts.step_index = ?5 AND deployment_step_attempts.attempt = ?6
  AND agent_id IS NULL AND state = 'started' AND (?1 = 'succeeded' OR ?1 = 'failed')
  AND EXISTS (SELECT 1 FROM deployments d WHERE d.id = deployment_step_attempts.deployment_id AND d.status IN ('pending', 'running'))
`

type FinishLocalDeploymentStepParams struct {
	State        string         `json:"state"`
	Reason       sql.NullString `json:"reason"`
	Now          sql.NullInt64  `json:"now"`
	DeploymentID int64          `json:"deployment_id"`
	StepIndex    int64          `json:"step_index"`
	Attempt      int64          `json:"attempt"`
}

func (q *Queries) FinishLocalDeploymentStep(ctx context.Context, arg FinishLocalDeploymentStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishLocalDeploymentStep,
		arg.State,
		arg.Reason,
		arg.Now,
		arg.DeploymentID,
		arg.StepIndex,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const freezeDeploymentStepSource = `-- name: FreezeDeploymentStepSource :execrows
INSERT INTO deployment_step_sources (deployment_id, steps_json)
SELECT d.id, r.steps_json FROM deployments d JOIN releases r ON r.id = d.release_id
WHERE d.id = ?1 AND d.status IN ('pending', 'pending_approval')
  AND NOT EXISTS (SELECT 1 FROM deployment_step_sources s WHERE s.deployment_id = d.id)
`

func (q *Queries) FreezeDeploymentStepSource(ctx context.Context, deploymentID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, freezeDeploymentStepSource, deploymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const freezeDeploymentStepSourceJSON = `-- name: FreezeDeploymentStepSourceJSON :execrows
INSERT INTO deployment_step_sources (deployment_id, steps_json)
SELECT d.id, ?1 FROM deployments d
WHERE d.id = ?2 AND d.status IN ('pending', 'pending_approval')
  AND NOT EXISTS (SELECT 1 FROM deployment_step_sources s WHERE s.deployment_id = d.id)
`

type FreezeDeploymentStepSourceJSONParams struct {
	StepsJson    string `json:"steps_json"`
	DeploymentID int64  `json:"deployment_id"`
}

func (q *Queries) FreezeDeploymentStepSourceJSON(ctx context.Context, arg FreezeDeploymentStepSourceJSONParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, freezeDeploymentStepSourceJSON, arg.StepsJson, arg.DeploymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDeploymentStepAttempt = `-- name: GetDeploymentStepAttempt :one
SELECT deployment_id, step_index, attempt, state, reason, agent_id, claim_token_hash, claim_expires_at, last_heartbeat_at, wait_deadline, started_at, finished_at, cancel_requested_at, created_at, updated_at FROM deployment_step_attempts WHERE deployment_id = ? AND step_index = ? AND attempt = ?
`

type GetDeploymentStepAttemptParams struct {
	DeploymentID int64 `json:"deployment_id"`
	StepIndex    int64 `json:"step_index"`
	Attempt      int64 `json:"attempt"`
}

func (q *Queries) GetDeploymentStepAttempt(ctx context.Context, arg GetDeploymentStepAttemptParams) (DeploymentStepAttempt, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentStepAttempt, arg.DeploymentID, arg.StepIndex, arg.Attempt)
	var i DeploymentStepAttempt
	err := row.Scan(
		&i.DeploymentID,
		&i.StepIndex,
		&i.Attempt,
		&i.State,
		&i.Reason,
		&i.AgentID,
		&i.ClaimTokenHash,
		&i.ClaimExpiresAt,
		&i.LastHeartbeatAt,
		&i.WaitDeadline,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeploymentStepCursor = `-- name: GetDeploymentStepCursor :one
SELECT s.deployment_id, s.step_index, s.source_step_id, s.name, s.script_body, s.timeout_seconds, s.max_retries, s.execution_target, s.created_at, s.interpreter FROM deployment_steps s
WHERE s.deployment_id = ?1
  AND NOT EXISTS (SELECT 1 FROM deployment_step_attempts a WHERE a.deployment_id = s.deployment_id
      AND a.step_index = s.step_index AND a.state = 'succeeded')
ORDER BY s.step_index LIMIT 1
`

// The cursor is the first immutable step without a successful attempt.
func (q *Queries) GetDeploymentStepCursor(ctx context.Context, deploymentID int64) (DeploymentStep, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentStepCursor, deploymentID)
	var i DeploymentStep
	err := row.Scan(
		&i.DeploymentID,
		&i.StepIndex,
		&i.SourceStepID,
		&i.Name,
		&i.ScriptBody,
		&i.TimeoutSeconds,
		&i.MaxRetries,
		&i.ExecutionTarget,
		&i.CreatedAt,
		&i.Interpreter,
	)
	return i, err
}

const getDeploymentStepSource = `-- name: GetDeploymentStepSource :one
SELECT deployment_id, steps_json, default_execution_target, created_at FROM deployment_step_sources WHERE deployment_id = ?
`

func (q *Queries) GetDeploymentStepSource(ctx context.Context, deploymentID int64) (DeploymentStepSource, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentStepSource, deploymentID)
	var i DeploymentStepSource
	err := row.Scan(
		&i.DeploymentID,
		&i.StepsJson,
		&i.DefaultExecutionTarget,
		&i.CreatedAt,
	)
	return i, err
}

const listDeploymentStepAttempts = `-- name: ListDeploymentStepAttempts :many
SELECT deployment_id, step_index, attempt, state, reason, agent_id, claim_token_hash, claim_expires_at, last_heartbeat_at, wait_deadline, started_at, finished_at, cancel_requested_at, created_at, updated_at FROM deployment_step_attempts WHERE deployment_id = ? ORDER BY step_index, attempt
`

func (q *Queries) ListDeploymentStepAttempts(ctx context.Context, deploymentID int64) ([]DeploymentStepAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentStepAttempts, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentStepAttempt
	for rows.Next() {
		var i DeploymentStepAttempt
		if err := rows.Scan(
			&i.DeploymentID,
			&i.StepIndex,
			&i.Attempt,
			&i.State,
			&i.Reason,
			&i.AgentID,
			&i.ClaimTokenHash,
			&i.ClaimExpiresAt,
			&i.LastHeartbeatAt,
			&i.WaitDeadline,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentStepSelectors = `-- name: ListDeploymentStepSelectors :many
SELECT label FROM deployment_step_selectors WHERE deployment_id = ? AND step_index = ? ORDER BY label
`

type ListDeploymentStepSelectorsParams struct {
	DeploymentID int64 `json:"deployment_id"`
	StepIndex    int64 `json:"step_index"`
}

func (q *Queries) ListDeploymentStepSelectors(ctx context.Context, arg ListDeploymentStepSelectorsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentStepSelectors, arg.DeploymentID, arg.StepIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentSteps = `-- name: ListDeploymentSteps :many
SELECT deployment_id, step_index, source_step_id, name, script_body, timeout_seconds, max_retries, execution_target, created_at, interpreter FROM deployment_steps WHERE deployment_id = ? ORDER BY step_index
`

func (q *Queries) ListDeploymentSteps(ctx context.Context, deploymentID int64) ([]DeploymentStep, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentSteps, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentStep
	for rows.Next() {
		var i DeploymentStep
		if err := rows.Scan(
			&i.DeploymentID,
			&i.StepIndex,
			&i.SourceStepID,
			&i.Name,
			&i.ScriptBody,
			&i.TimeoutSeconds,
			&i.MaxRetries,
			&i.ExecutionTarget,
			&i.CreatedAt,
			&i.Interpreter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startLocalDeploymentStep = `-- name: StartLocalDeploymentStep :execrows
UPDATE deployment_step_attempts SET state = 'started', started_at = ?1, updated_at = ?1
WHERE deployment_step_attempts.deployment_id = ?2 AND deployment_step_attempts.step_index = ?3 AND deployment_step_attempts.attempt = ?4
  AND state = 'waiting' AND agent_id IS NULL AND wait_deadline > ?1
  AND EXISTS (SELECT 1 FROM deployment_steps s WHERE s.deployment_id = deployment_step_attempts.deployment_id
      AND s.step_index = deployment_step_attempts.step_index AND s.execution_target = 'local')
  AND EXISTS (SELECT 1 FROM deployments d WHERE d.id = deployment_step_attempts.deployment_id AND d.status IN ('pending', 'running'))
`

type StartLocalDeploymentStepParams struct {
	Now          sql.NullInt64 `json:"now"`
	DeploymentID int64         `json:"deployment_id"`
	StepIndex    int64         `json:"step_index"`
	Attempt      int64         `json:"attempt"`
}

func (q *Queries) StartLocalDeploymentStep(ctx context.Context, arg StartLocalDeploymentStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startLocalDeploymentStep,
		arg.Now,
		arg.DeploymentID,
		arg.StepIndex,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
