// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package db

import (
	"context"
	"database/sql"
)

const countEnvironments = `-- name: CountEnvironments :one
SELECT COUNT(*) FROM environments
`

func (q *Queries) CountEnvironments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnvironments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (name, description, tags) VALUES (?, ?, ?) RETURNING id, name, description, tags, created_at
`

type CreateEnvironmentParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Tags        sql.NullString `json:"tags"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, createEnvironment, arg.Name, arg.Description, arg.Tags)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environments WHERE id = ?
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEnvironment, id)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, name, description, tags, created_at FROM environments WHERE id = ?
`

func (q *Queries) GetEnvironment(ctx context.Context, id int64) (Environment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const hasActiveEnvironmentDeployment = `-- name: HasActiveEnvironmentDeployment :one
SELECT CASE WHEN EXISTS (
    SELECT 1 FROM deployments d WHERE d.environment_id = ?
      AND (d.status IN ('pending', 'running', 'pending_approval')
        OR EXISTS (SELECT 1 FROM remote_deployment_claims c
                   WHERE c.deployment_id = d.id
                     AND c.state IN ('lost', 'cancel_unconfirmed'))
        OR EXISTS (SELECT 1 FROM remote_step_runs s
                   WHERE s.deployment_id = d.id
                     AND s.state IN ('lost', 'cancel_unconfirmed')))
) THEN 1 ELSE 0 END
`

func (q *Queries) HasActiveEnvironmentDeployment(ctx context.Context, environmentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasActiveEnvironmentDeployment, environmentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listEnvironmentDeploymentIDs = `-- name: ListEnvironmentDeploymentIDs :many
SELECT id FROM deployments WHERE environment_id = ?
`

func (q *Queries) ListEnvironmentDeploymentIDs(ctx context.Context, environmentID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironmentDeploymentIDs, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, name, description, tags, created_at FROM environments ORDER BY created_at DESC
`

func (q *Queries) ListEnvironments(ctx context.Context) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsPaginated = `-- name: ListEnvironmentsPaginated :many
SELECT id, name, description, tags, created_at FROM environments ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListEnvironmentsPaginatedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListEnvironmentsPaginated(ctx context.Context, arg ListEnvironmentsPaginatedParams) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironmentsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments SET name = ?, description = ?, tags = ? WHERE id = ? RETURNING id, name, description, tags, created_at
`

type UpdateEnvironmentParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Tags        sql.NullString `json:"tags"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, updateEnvironment,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.ID,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}
