// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package db

import (
	"context"
	"database/sql"
)

const countEnvironments = `-- name: CountEnvironments :one
SELECT COUNT(*) FROM environments
`

func (q *Queries) CountEnvironments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnvironments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (name, description, tags, verification_type, verification_target, verification_timeout_seconds)
VALUES (?1, ?2, ?3, ?4, ?5, COALESCE(NULLIF(CAST(?6 AS INTEGER), 0), 30)) RETURNING id, name, description, tags, created_at, verification_type, verification_target, verification_timeout_seconds
`

type CreateEnvironmentParams struct {
	Name                       string         `json:"name"`
	Description                sql.NullString `json:"description"`
	Tags                       sql.NullString `json:"tags"`
	VerificationType           string         `json:"verification_type"`
	VerificationTarget         string         `json:"verification_target"`
	VerificationTimeoutSeconds int64          `json:"verification_timeout_seconds"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, createEnvironment,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.VerificationType,
		arg.VerificationTarget,
		arg.VerificationTimeoutSeconds,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
		&i.VerificationType,
		&i.VerificationTarget,
		&i.VerificationTimeoutSeconds,
	)
	return i, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environments WHERE id = ?
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEnvironment, id)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, name, description, tags, created_at, verification_type, verification_target, verification_timeout_seconds FROM environments WHERE id = ?
`

func (q *Queries) GetEnvironment(ctx context.Context, id int64) (Environment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
		&i.VerificationType,
		&i.VerificationTarget,
		&i.VerificationTimeoutSeconds,
	)
	return i, err
}

const hasActiveEnvironmentDeployment = `-- name: HasActiveEnvironmentDeployment :one
SELECT CASE WHEN EXISTS (
    SELECT 1 FROM deployments d WHERE d.environment_id = ?
      AND (d.status IN ('queued', 'pending', 'running', 'pending_approval', 'publishing_artifact', 'awaiting_artifact_approval')
        OR (d.status = 'cleanup_unconfirmed'
            AND (d.container_namespace IS NOT NULL OR (
            NOT EXISTS (SELECT 1 FROM remote_step_runs s
                WHERE s.deployment_id = d.id AND s.state = 'cleanup_unconfirmed')
            AND NOT EXISTS (SELECT 1 FROM remote_deployment_claims c
                WHERE c.deployment_id = d.id AND c.state = 'cleanup_unconfirmed'))))
        OR EXISTS (SELECT 1 FROM remote_deployment_claims c
                   WHERE c.deployment_id = d.id
                     AND (c.state IN ('lost', 'cancel_unconfirmed')
                       OR (c.state = 'cleanup_unconfirmed'
                           AND c.cleanup_confirmed_at IS NULL)))
        OR EXISTS (SELECT 1 FROM remote_step_runs s
                   WHERE s.deployment_id = d.id
                     AND (s.state IN ('lost', 'cancel_unconfirmed')
                       OR (s.state = 'cleanup_unconfirmed'
                           AND s.cleanup_confirmed_at IS NULL))))
) THEN 1 ELSE 0 END
`

func (q *Queries) HasActiveEnvironmentDeployment(ctx context.Context, environmentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasActiveEnvironmentDeployment, environmentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listDeploymentEnvironmentsForUser = `-- name: ListDeploymentEnvironmentsForUser :many
SELECT e.id, e.name, e.description, e.tags, e.created_at, e.verification_type, e.verification_target, e.verification_timeout_seconds FROM environments e
WHERE EXISTS (
    SELECT 1 FROM deployments d
    JOIN releases r ON r.id = d.release_id
    JOIN project_members pm ON pm.project_id = r.project_id
    WHERE d.environment_id = e.id AND d.kind = 'deployment'
      AND pm.user_id = ?1
)
ORDER BY e.created_at DESC
`

func (q *Queries) ListDeploymentEnvironmentsForUser(ctx context.Context, userID int64) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentEnvironmentsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.CreatedAt,
			&i.VerificationType,
			&i.VerificationTarget,
			&i.VerificationTimeoutSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentDeploymentIDs = `-- name: ListEnvironmentDeploymentIDs :many
SELECT id FROM deployments WHERE environment_id = ?
`

func (q *Queries) ListEnvironmentDeploymentIDs(ctx context.Context, environmentID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironmentDeploymentIDs, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, name, description, tags, created_at, verification_type, verification_target, verification_timeout_seconds FROM environments ORDER BY created_at DESC
`

func (q *Queries) ListEnvironments(ctx context.Context) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.CreatedAt,
			&i.VerificationType,
			&i.VerificationTarget,
			&i.VerificationTimeoutSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsPaginated = `-- name: ListEnvironmentsPaginated :many
SELECT id, name, description, tags, created_at, verification_type, verification_target, verification_timeout_seconds FROM environments ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListEnvironmentsPaginatedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListEnvironmentsPaginated(ctx context.Context, arg ListEnvironmentsPaginatedParams) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironmentsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.CreatedAt,
			&i.VerificationType,
			&i.VerificationTarget,
			&i.VerificationTimeoutSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments SET name = ?1, description = ?2, tags = ?3,
verification_type = CASE WHEN CAST(?4 AS INTEGER) = 1 THEN ?5 ELSE verification_type END,
verification_target = CASE WHEN CAST(?4 AS INTEGER) = 1 THEN ?6 ELSE verification_target END,
verification_timeout_seconds = CASE WHEN CAST(?4 AS INTEGER) = 1 THEN COALESCE(NULLIF(CAST(?7 AS INTEGER), 0), 30) ELSE verification_timeout_seconds END
WHERE id = ?8 RETURNING id, name, description, tags, created_at, verification_type, verification_target, verification_timeout_seconds
`

type UpdateEnvironmentParams struct {
	Name                       string         `json:"name"`
	Description                sql.NullString `json:"description"`
	Tags                       sql.NullString `json:"tags"`
	ConfigureVerification      int64          `json:"configure_verification"`
	VerificationType           string         `json:"verification_type"`
	VerificationTarget         string         `json:"verification_target"`
	VerificationTimeoutSeconds int64          `json:"verification_timeout_seconds"`
	ID                         int64          `json:"id"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, updateEnvironment,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.ConfigureVerification,
		arg.VerificationType,
		arg.VerificationTarget,
		arg.VerificationTimeoutSeconds,
		arg.ID,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
		&i.VerificationType,
		&i.VerificationTarget,
		&i.VerificationTimeoutSeconds,
	)
	return i, err
}
