// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lifecycle_variables.sql

package db

import (
	"context"
	"database/sql"
)

const createLifecycleVariable = `-- name: CreateLifecycleVariable :one
INSERT INTO lifecycle_variables (lifecycle_id, name, value, environment_id, secret)
VALUES (?, ?, ?, ?, ?) RETURNING id, lifecycle_id, name, value, environment_id, secret, created_at
`

type CreateLifecycleVariableParams struct {
	LifecycleID   int64          `json:"lifecycle_id"`
	Name          string         `json:"name"`
	Value         sql.NullString `json:"value"`
	EnvironmentID sql.NullInt64  `json:"environment_id"`
	Secret        int64          `json:"secret"`
}

func (q *Queries) CreateLifecycleVariable(ctx context.Context, arg CreateLifecycleVariableParams) (LifecycleVariable, error) {
	row := q.db.QueryRowContext(ctx, createLifecycleVariable,
		arg.LifecycleID,
		arg.Name,
		arg.Value,
		arg.EnvironmentID,
		arg.Secret,
	)
	var i LifecycleVariable
	err := row.Scan(
		&i.ID,
		&i.LifecycleID,
		&i.Name,
		&i.Value,
		&i.EnvironmentID,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLifecycleVariable = `-- name: DeleteLifecycleVariable :execrows
DELETE FROM lifecycle_variables WHERE id = ? AND lifecycle_id = ?
`

type DeleteLifecycleVariableParams struct {
	ID          int64 `json:"id"`
	LifecycleID int64 `json:"lifecycle_id"`
}

func (q *Queries) DeleteLifecycleVariable(ctx context.Context, arg DeleteLifecycleVariableParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLifecycleVariable, arg.ID, arg.LifecycleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLifecycleVariable = `-- name: GetLifecycleVariable :one
SELECT id, lifecycle_id, name, value, environment_id, secret, created_at FROM lifecycle_variables WHERE id = ? AND lifecycle_id = ?
`

type GetLifecycleVariableParams struct {
	ID          int64 `json:"id"`
	LifecycleID int64 `json:"lifecycle_id"`
}

func (q *Queries) GetLifecycleVariable(ctx context.Context, arg GetLifecycleVariableParams) (LifecycleVariable, error) {
	row := q.db.QueryRowContext(ctx, getLifecycleVariable, arg.ID, arg.LifecycleID)
	var i LifecycleVariable
	err := row.Scan(
		&i.ID,
		&i.LifecycleID,
		&i.Name,
		&i.Value,
		&i.EnvironmentID,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const lifecycleVariableScopeAllowed = `-- name: LifecycleVariableScopeAllowed :one
SELECT COUNT(*) FROM lifecycle_stages WHERE lifecycle_id = ? AND environment_id = ?
`

type LifecycleVariableScopeAllowedParams struct {
	LifecycleID   int64 `json:"lifecycle_id"`
	EnvironmentID int64 `json:"environment_id"`
}

func (q *Queries) LifecycleVariableScopeAllowed(ctx context.Context, arg LifecycleVariableScopeAllowedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lifecycleVariableScopeAllowed, arg.LifecycleID, arg.EnvironmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAllLifecycleVariables = `-- name: ListAllLifecycleVariables :many
SELECT id, lifecycle_id, name, value, environment_id, secret, created_at FROM lifecycle_variables ORDER BY id
`

func (q *Queries) ListAllLifecycleVariables(ctx context.Context) ([]LifecycleVariable, error) {
	rows, err := q.db.QueryContext(ctx, listAllLifecycleVariables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LifecycleVariable
	for rows.Next() {
		var i LifecycleVariable
		if err := rows.Scan(
			&i.ID,
			&i.LifecycleID,
			&i.Name,
			&i.Value,
			&i.EnvironmentID,
			&i.Secret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLifecycleVariables = `-- name: ListLifecycleVariables :many
SELECT id, lifecycle_id, name, value, environment_id, secret, created_at FROM lifecycle_variables WHERE lifecycle_id = ? ORDER BY name, id
`

func (q *Queries) ListLifecycleVariables(ctx context.Context, lifecycleID int64) ([]LifecycleVariable, error) {
	rows, err := q.db.QueryContext(ctx, listLifecycleVariables, lifecycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LifecycleVariable
	for rows.Next() {
		var i LifecycleVariable
		if err := rows.Scan(
			&i.ID,
			&i.LifecycleID,
			&i.Name,
			&i.Value,
			&i.EnvironmentID,
			&i.Secret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByLifecycle = `-- name: ListProjectsByLifecycle :many
SELECT id, name FROM projects WHERE lifecycle_id = ? ORDER BY name
`

type ListProjectsByLifecycleRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListProjectsByLifecycle(ctx context.Context, lifecycleID sql.NullInt64) ([]ListProjectsByLifecycleRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByLifecycle, lifecycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsByLifecycleRow
	for rows.Next() {
		var i ListProjectsByLifecycleRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLifecycleVariable = `-- name: UpdateLifecycleVariable :one
UPDATE lifecycle_variables SET name = ?, value = ?, environment_id = ?, secret = ?
WHERE id = ? AND lifecycle_id = ? RETURNING id, lifecycle_id, name, value, environment_id, secret, created_at
`

type UpdateLifecycleVariableParams struct {
	Name          string         `json:"name"`
	Value         sql.NullString `json:"value"`
	EnvironmentID sql.NullInt64  `json:"environment_id"`
	Secret        int64          `json:"secret"`
	ID            int64          `json:"id"`
	LifecycleID   int64          `json:"lifecycle_id"`
}

func (q *Queries) UpdateLifecycleVariable(ctx context.Context, arg UpdateLifecycleVariableParams) (LifecycleVariable, error) {
	row := q.db.QueryRowContext(ctx, updateLifecycleVariable,
		arg.Name,
		arg.Value,
		arg.EnvironmentID,
		arg.Secret,
		arg.ID,
		arg.LifecycleID,
	)
	var i LifecycleVariable
	err := row.Scan(
		&i.ID,
		&i.LifecycleID,
		&i.Name,
		&i.Value,
		&i.EnvironmentID,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const updateLifecycleVariableKeepValue = `-- name: UpdateLifecycleVariableKeepValue :one
UPDATE lifecycle_variables SET name = ?, environment_id = ?, secret = ?
WHERE id = ? AND lifecycle_id = ? RETURNING id, lifecycle_id, name, value, environment_id, secret, created_at
`

type UpdateLifecycleVariableKeepValueParams struct {
	Name          string        `json:"name"`
	EnvironmentID sql.NullInt64 `json:"environment_id"`
	Secret        int64         `json:"secret"`
	ID            int64         `json:"id"`
	LifecycleID   int64         `json:"lifecycle_id"`
}

func (q *Queries) UpdateLifecycleVariableKeepValue(ctx context.Context, arg UpdateLifecycleVariableKeepValueParams) (LifecycleVariable, error) {
	row := q.db.QueryRowContext(ctx, updateLifecycleVariableKeepValue,
		arg.Name,
		arg.EnvironmentID,
		arg.Secret,
		arg.ID,
		arg.LifecycleID,
	)
	var i LifecycleVariable
	err := row.Scan(
		&i.ID,
		&i.LifecycleID,
		&i.Name,
		&i.Value,
		&i.EnvironmentID,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const updateLifecycleVariableValue = `-- name: UpdateLifecycleVariableValue :exec
UPDATE lifecycle_variables SET value = ? WHERE id = ?
`

type UpdateLifecycleVariableValueParams struct {
	Value sql.NullString `json:"value"`
	ID    int64          `json:"id"`
}

func (q *Queries) UpdateLifecycleVariableValue(ctx context.Context, arg UpdateLifecycleVariableValueParams) error {
	_, err := q.db.ExecContext(ctx, updateLifecycleVariableValue, arg.Value, arg.ID)
	return err
}
