// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa.sql

package db

import (
	"context"
	"database/sql"
)

const advanceTOTPIfNewer = `-- name: AdvanceTOTPIfNewer :execrows
UPDATE mfa_totp
SET last_accepted_step = ?1, updated_at = unixepoch()
WHERE user_id = ?2
  AND (last_accepted_step IS NULL OR last_accepted_step < ?1)
`

type AdvanceTOTPIfNewerParams struct {
	NextStep sql.NullInt64 `json:"next_step"`
	UserID   int64         `json:"user_id"`
}

func (q *Queries) AdvanceTOTPIfNewer(ctx context.Context, arg AdvanceTOTPIfNewerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceTOTPIfNewer, arg.NextStep, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeMFAChallenge = `-- name: ConsumeMFAChallenge :execrows
DELETE FROM mfa_challenges WHERE token_hash = ?
`

func (q *Queries) ConsumeMFAChallenge(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeMFAChallenge, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeMFAChallengeBySessionGuarded = `-- name: ConsumeMFAChallengeBySessionGuarded :execrows
DELETE FROM mfa_challenges
WHERE token_hash = ?1
  AND user_id = ?2
  AND purpose = ?3
  AND session_id = ?4
  AND expires_at > ?5
`

type ConsumeMFAChallengeBySessionGuardedParams struct {
	TokenHash []byte         `json:"token_hash"`
	UserID    int64          `json:"user_id"`
	Purpose   string         `json:"purpose"`
	SessionID sql.NullString `json:"session_id"`
	ExpiresAt int64          `json:"expires_at"`
}

func (q *Queries) ConsumeMFAChallengeBySessionGuarded(ctx context.Context, arg ConsumeMFAChallengeBySessionGuardedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeMFAChallengeBySessionGuarded,
		arg.TokenHash,
		arg.UserID,
		arg.Purpose,
		arg.SessionID,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeMFAChallengeGuarded = `-- name: ConsumeMFAChallengeGuarded :execrows
DELETE FROM mfa_challenges
WHERE token_hash = ?1
  AND user_id = ?2
  AND purpose = ?3
  AND (session_id = ?4 OR (session_id IS NULL AND ?4 IS NULL))
  AND csrf_hash = ?5
   AND expires_at > ?6
   AND attempts < ?7
`

type ConsumeMFAChallengeGuardedParams struct {
	TokenHash []byte         `json:"token_hash"`
	UserID    int64          `json:"user_id"`
	Purpose   string         `json:"purpose"`
	SessionID sql.NullString `json:"session_id"`
	CsrfHash  []byte         `json:"csrf_hash"`
	ExpiresAt int64          `json:"expires_at"`
	Attempts  int64          `json:"attempts"`
}

func (q *Queries) ConsumeMFAChallengeGuarded(ctx context.Context, arg ConsumeMFAChallengeGuardedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeMFAChallengeGuarded,
		arg.TokenHash,
		arg.UserID,
		arg.Purpose,
		arg.SessionID,
		arg.CsrfHash,
		arg.ExpiresAt,
		arg.Attempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :one
UPDATE mfa_recovery_codes SET used_at = ?
WHERE user_id = ? AND code_hash = ? AND used_at IS NULL RETURNING id, user_id, code_hash, used_at, created_at
`

type ConsumeRecoveryCodeParams struct {
	UsedAt   sql.NullInt64 `json:"used_at"`
	UserID   int64         `json:"user_id"`
	CodeHash []byte        `json:"code_hash"`
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (MfaRecoveryCode, error) {
	row := q.db.QueryRowContext(ctx, consumeRecoveryCode, arg.UsedAt, arg.UserID, arg.CodeHash)
	var i MfaRecoveryCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countMFAFactors = `-- name: CountMFAFactors :one
SELECT
    (SELECT COUNT(*) FROM mfa_totp AS totp WHERE totp.user_id = ?1) +
    (SELECT COUNT(*) FROM webauthn_credentials AS credential WHERE credential.user_id = ?1)
    AS factor_count
`

func (q *Queries) CountMFAFactors(ctx context.Context, targetUserID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMFAFactors, targetUserID)
	var factor_count int64
	err := row.Scan(&factor_count)
	return factor_count, err
}

const createMFAChallenge = `-- name: CreateMFAChallenge :one
INSERT INTO mfa_challenges (
    token_hash, user_id, session_id, purpose, csrf_hash, ceremony_json, attempts,
    expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING token_hash, user_id, session_id, purpose, csrf_hash, ceremony_json, attempts, expires_at, created_at
`

type CreateMFAChallengeParams struct {
	TokenHash    []byte         `json:"token_hash"`
	UserID       int64          `json:"user_id"`
	SessionID    sql.NullString `json:"session_id"`
	Purpose      string         `json:"purpose"`
	CsrfHash     []byte         `json:"csrf_hash"`
	CeremonyJson string         `json:"ceremony_json"`
	Attempts     int64          `json:"attempts"`
	ExpiresAt    int64          `json:"expires_at"`
}

func (q *Queries) CreateMFAChallenge(ctx context.Context, arg CreateMFAChallengeParams) (MfaChallenge, error) {
	row := q.db.QueryRowContext(ctx, createMFAChallenge,
		arg.TokenHash,
		arg.UserID,
		arg.SessionID,
		arg.Purpose,
		arg.CsrfHash,
		arg.CeremonyJson,
		arg.Attempts,
		arg.ExpiresAt,
	)
	var i MfaChallenge
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.SessionID,
		&i.Purpose,
		&i.CsrfHash,
		&i.CeremonyJson,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMFARateLimit = `-- name: CreateMFARateLimit :one
INSERT INTO mfa_rate_limits (
    user_id, window_started_at, failure_count, blocked_until
) VALUES (?, ?, ?, ?) RETURNING user_id, window_started_at, failure_count, blocked_until
`

type CreateMFARateLimitParams struct {
	UserID          int64         `json:"user_id"`
	WindowStartedAt int64         `json:"window_started_at"`
	FailureCount    int64         `json:"failure_count"`
	BlockedUntil    sql.NullInt64 `json:"blocked_until"`
}

func (q *Queries) CreateMFARateLimit(ctx context.Context, arg CreateMFARateLimitParams) (MfaRateLimit, error) {
	row := q.db.QueryRowContext(ctx, createMFARateLimit,
		arg.UserID,
		arg.WindowStartedAt,
		arg.FailureCount,
		arg.BlockedUntil,
	)
	var i MfaRateLimit
	err := row.Scan(
		&i.UserID,
		&i.WindowStartedAt,
		&i.FailureCount,
		&i.BlockedUntil,
	)
	return i, err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :one
INSERT INTO mfa_recovery_codes (id, user_id, code_hash)
VALUES (?, ?, ?) RETURNING id, user_id, code_hash, used_at, created_at
`

type CreateRecoveryCodeParams struct {
	ID       string `json:"id"`
	UserID   int64  `json:"user_id"`
	CodeHash []byte `json:"code_hash"`
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) (MfaRecoveryCode, error) {
	row := q.db.QueryRowContext(ctx, createRecoveryCode, arg.ID, arg.UserID, arg.CodeHash)
	var i MfaRecoveryCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTOTP = `-- name: CreateTOTP :one
INSERT INTO mfa_totp (user_id, encrypted_seed, last_accepted_step)
VALUES (?, ?, ?) RETURNING user_id, encrypted_seed, last_accepted_step, created_at, updated_at
`

type CreateTOTPParams struct {
	UserID           int64         `json:"user_id"`
	EncryptedSeed    []byte        `json:"encrypted_seed"`
	LastAcceptedStep sql.NullInt64 `json:"last_accepted_step"`
}

func (q *Queries) CreateTOTP(ctx context.Context, arg CreateTOTPParams) (MfaTotp, error) {
	row := q.db.QueryRowContext(ctx, createTOTP, arg.UserID, arg.EncryptedSeed, arg.LastAcceptedStep)
	var i MfaTotp
	err := row.Scan(
		&i.UserID,
		&i.EncryptedSeed,
		&i.LastAcceptedStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :one
INSERT INTO webauthn_credentials (
    credential_id, user_id, name, public_key, aaguid, transports_json, flags,
    sign_count, clone_warning, attachment, attestation_type, attestation_format,
    attestation_client_data_json, attestation_client_data_hash,
    attestation_authenticator_data, attestation_public_key_algorithm,
    attestation_object
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING credential_id, user_id, name, public_key, aaguid, transports_json, flags, sign_count, clone_warning, attachment, created_at, updated_at, attestation_type, attestation_format, attestation_client_data_json, attestation_client_data_hash, attestation_authenticator_data, attestation_public_key_algorithm, attestation_object
`

type CreateWebAuthnCredentialParams struct {
	CredentialID                  []byte         `json:"credential_id"`
	UserID                        int64          `json:"user_id"`
	Name                          string         `json:"name"`
	PublicKey                     []byte         `json:"public_key"`
	Aaguid                        []byte         `json:"aaguid"`
	TransportsJson                string         `json:"transports_json"`
	Flags                         int64          `json:"flags"`
	SignCount                     int64          `json:"sign_count"`
	CloneWarning                  int64          `json:"clone_warning"`
	Attachment                    sql.NullString `json:"attachment"`
	AttestationType               string         `json:"attestation_type"`
	AttestationFormat             string         `json:"attestation_format"`
	AttestationClientDataJson     []byte         `json:"attestation_client_data_json"`
	AttestationClientDataHash     []byte         `json:"attestation_client_data_hash"`
	AttestationAuthenticatorData  []byte         `json:"attestation_authenticator_data"`
	AttestationPublicKeyAlgorithm int64          `json:"attestation_public_key_algorithm"`
	AttestationObject             []byte         `json:"attestation_object"`
}

func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRowContext(ctx, createWebAuthnCredential,
		arg.CredentialID,
		arg.UserID,
		arg.Name,
		arg.PublicKey,
		arg.Aaguid,
		arg.TransportsJson,
		arg.Flags,
		arg.SignCount,
		arg.CloneWarning,
		arg.Attachment,
		arg.AttestationType,
		arg.AttestationFormat,
		arg.AttestationClientDataJson,
		arg.AttestationClientDataHash,
		arg.AttestationAuthenticatorData,
		arg.AttestationPublicKeyAlgorithm,
		arg.AttestationObject,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.CredentialID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.Aaguid,
		&i.TransportsJson,
		&i.Flags,
		&i.SignCount,
		&i.CloneWarning,
		&i.Attachment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttestationType,
		&i.AttestationFormat,
		&i.AttestationClientDataJson,
		&i.AttestationClientDataHash,
		&i.AttestationAuthenticatorData,
		&i.AttestationPublicKeyAlgorithm,
		&i.AttestationObject,
	)
	return i, err
}

const createWebAuthnUser = `-- name: CreateWebAuthnUser :one
INSERT INTO webauthn_users (user_id, rp_id, user_handle)
VALUES (?, ?, ?) RETURNING user_id, rp_id, user_handle, created_at
`

type CreateWebAuthnUserParams struct {
	UserID     int64  `json:"user_id"`
	RpID       string `json:"rp_id"`
	UserHandle []byte `json:"user_handle"`
}

func (q *Queries) CreateWebAuthnUser(ctx context.Context, arg CreateWebAuthnUserParams) (WebauthnUser, error) {
	row := q.db.QueryRowContext(ctx, createWebAuthnUser, arg.UserID, arg.RpID, arg.UserHandle)
	var i WebauthnUser
	err := row.Scan(
		&i.UserID,
		&i.RpID,
		&i.UserHandle,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredMFAChallenges = `-- name: DeleteExpiredMFAChallenges :exec
DELETE FROM mfa_challenges
WHERE expires_at < ?
  AND purpose != 'admin_mfa_reset'
`

func (q *Queries) DeleteExpiredMFAChallenges(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredMFAChallenges, expiresAt)
	return err
}

const deleteMFAChallengesBySessionID = `-- name: DeleteMFAChallengesBySessionID :execrows
DELETE FROM mfa_challenges WHERE session_id = ?
`

func (q *Queries) DeleteMFAChallengesBySessionID(ctx context.Context, sessionID sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMFAChallengesBySessionID, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMFAChallengesByUserID = `-- name: DeleteMFAChallengesByUserID :execrows
DELETE FROM mfa_challenges WHERE user_id = ?
`

func (q *Queries) DeleteMFAChallengesByUserID(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMFAChallengesByUserID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMFAChallengesByUserSessionPurpose = `-- name: DeleteMFAChallengesByUserSessionPurpose :execrows
DELETE FROM mfa_challenges
WHERE user_id = ?
  AND session_id = ?
  AND purpose = ?
`

type DeleteMFAChallengesByUserSessionPurposeParams struct {
	UserID    int64          `json:"user_id"`
	SessionID sql.NullString `json:"session_id"`
	Purpose   string         `json:"purpose"`
}

func (q *Queries) DeleteMFAChallengesByUserSessionPurpose(ctx context.Context, arg DeleteMFAChallengesByUserSessionPurposeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMFAChallengesByUserSessionPurpose, arg.UserID, arg.SessionID, arg.Purpose)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMFARateLimit = `-- name: DeleteMFARateLimit :exec
DELETE FROM mfa_rate_limits WHERE user_id = ?
`

func (q *Queries) DeleteMFARateLimit(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMFARateLimit, userID)
	return err
}

const deleteRecoveryCodesByUserID = `-- name: DeleteRecoveryCodesByUserID :exec
DELETE FROM mfa_recovery_codes WHERE user_id = ?
`

func (q *Queries) DeleteRecoveryCodesByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryCodesByUserID, userID)
	return err
}

const deleteTOTP = `-- name: DeleteTOTP :execrows
DELETE FROM mfa_totp WHERE user_id = ?
`

func (q *Queries) DeleteTOTP(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTOTP, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :exec
DELETE FROM webauthn_credentials WHERE credential_id = ?
`

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, credentialID []byte) error {
	_, err := q.db.ExecContext(ctx, deleteWebAuthnCredential, credentialID)
	return err
}

const deleteWebAuthnCredentialByUserID = `-- name: DeleteWebAuthnCredentialByUserID :execrows
DELETE FROM webauthn_credentials WHERE credential_id = ? AND user_id = ?
`

type DeleteWebAuthnCredentialByUserIDParams struct {
	CredentialID []byte `json:"credential_id"`
	UserID       int64  `json:"user_id"`
}

func (q *Queries) DeleteWebAuthnCredentialByUserID(ctx context.Context, arg DeleteWebAuthnCredentialByUserIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWebAuthnCredentialByUserID, arg.CredentialID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteWebAuthnCredentialsByUserID = `-- name: DeleteWebAuthnCredentialsByUserID :exec
DELETE FROM webauthn_credentials WHERE user_id = ?
`

func (q *Queries) DeleteWebAuthnCredentialsByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteWebAuthnCredentialsByUserID, userID)
	return err
}

const getActiveMFAChallenge = `-- name: GetActiveMFAChallenge :one
SELECT token_hash, user_id, session_id, purpose, csrf_hash, ceremony_json, attempts, expires_at, created_at FROM mfa_challenges WHERE token_hash = ? AND expires_at > ?
`

type GetActiveMFAChallengeParams struct {
	TokenHash []byte `json:"token_hash"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) GetActiveMFAChallenge(ctx context.Context, arg GetActiveMFAChallengeParams) (MfaChallenge, error) {
	row := q.db.QueryRowContext(ctx, getActiveMFAChallenge, arg.TokenHash, arg.ExpiresAt)
	var i MfaChallenge
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.SessionID,
		&i.Purpose,
		&i.CsrfHash,
		&i.CeremonyJson,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMFAChallengeByUserSessionPurpose = `-- name: GetMFAChallengeByUserSessionPurpose :one
SELECT token_hash, user_id, session_id, purpose, csrf_hash, ceremony_json, attempts, expires_at, created_at FROM mfa_challenges
WHERE user_id = ?
  AND session_id = ?
  AND purpose = ?
ORDER BY created_at DESC
LIMIT 1
`

type GetMFAChallengeByUserSessionPurposeParams struct {
	UserID    int64          `json:"user_id"`
	SessionID sql.NullString `json:"session_id"`
	Purpose   string         `json:"purpose"`
}

func (q *Queries) GetMFAChallengeByUserSessionPurpose(ctx context.Context, arg GetMFAChallengeByUserSessionPurposeParams) (MfaChallenge, error) {
	row := q.db.QueryRowContext(ctx, getMFAChallengeByUserSessionPurpose, arg.UserID, arg.SessionID, arg.Purpose)
	var i MfaChallenge
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.SessionID,
		&i.Purpose,
		&i.CsrfHash,
		&i.CeremonyJson,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMFARateLimitByUserID = `-- name: GetMFARateLimitByUserID :one
SELECT user_id, window_started_at, failure_count, blocked_until FROM mfa_rate_limits WHERE user_id = ?
`

func (q *Queries) GetMFARateLimitByUserID(ctx context.Context, userID int64) (MfaRateLimit, error) {
	row := q.db.QueryRowContext(ctx, getMFARateLimitByUserID, userID)
	var i MfaRateLimit
	err := row.Scan(
		&i.UserID,
		&i.WindowStartedAt,
		&i.FailureCount,
		&i.BlockedUntil,
	)
	return i, err
}

const getTOTPByUserID = `-- name: GetTOTPByUserID :one
SELECT user_id, encrypted_seed, last_accepted_step, created_at, updated_at FROM mfa_totp WHERE user_id = ?
`

func (q *Queries) GetTOTPByUserID(ctx context.Context, userID int64) (MfaTotp, error) {
	row := q.db.QueryRowContext(ctx, getTOTPByUserID, userID)
	var i MfaTotp
	err := row.Scan(
		&i.UserID,
		&i.EncryptedSeed,
		&i.LastAcceptedStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebAuthnCredentialByID = `-- name: GetWebAuthnCredentialByID :one
SELECT credential_id, user_id, name, public_key, aaguid, transports_json, flags, sign_count, clone_warning, attachment, created_at, updated_at, attestation_type, attestation_format, attestation_client_data_json, attestation_client_data_hash, attestation_authenticator_data, attestation_public_key_algorithm, attestation_object FROM webauthn_credentials WHERE credential_id = ?
`

func (q *Queries) GetWebAuthnCredentialByID(ctx context.Context, credentialID []byte) (WebauthnCredential, error) {
	row := q.db.QueryRowContext(ctx, getWebAuthnCredentialByID, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.CredentialID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.Aaguid,
		&i.TransportsJson,
		&i.Flags,
		&i.SignCount,
		&i.CloneWarning,
		&i.Attachment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttestationType,
		&i.AttestationFormat,
		&i.AttestationClientDataJson,
		&i.AttestationClientDataHash,
		&i.AttestationAuthenticatorData,
		&i.AttestationPublicKeyAlgorithm,
		&i.AttestationObject,
	)
	return i, err
}

const getWebAuthnUserByUserID = `-- name: GetWebAuthnUserByUserID :one
SELECT user_id, rp_id, user_handle, created_at FROM webauthn_users WHERE user_id = ?
`

func (q *Queries) GetWebAuthnUserByUserID(ctx context.Context, userID int64) (WebauthnUser, error) {
	row := q.db.QueryRowContext(ctx, getWebAuthnUserByUserID, userID)
	var i WebauthnUser
	err := row.Scan(
		&i.UserID,
		&i.RpID,
		&i.UserHandle,
		&i.CreatedAt,
	)
	return i, err
}

const incrementMFAChallengeAttempts = `-- name: IncrementMFAChallengeAttempts :one
UPDATE mfa_challenges SET attempts = attempts + 1
WHERE token_hash = ? AND attempts < ? RETURNING token_hash, user_id, session_id, purpose, csrf_hash, ceremony_json, attempts, expires_at, created_at
`

type IncrementMFAChallengeAttemptsParams struct {
	TokenHash []byte `json:"token_hash"`
	Attempts  int64  `json:"attempts"`
}

func (q *Queries) IncrementMFAChallengeAttempts(ctx context.Context, arg IncrementMFAChallengeAttemptsParams) (MfaChallenge, error) {
	row := q.db.QueryRowContext(ctx, incrementMFAChallengeAttempts, arg.TokenHash, arg.Attempts)
	var i MfaChallenge
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.SessionID,
		&i.Purpose,
		&i.CsrfHash,
		&i.CeremonyJson,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUnusedRecoveryCodesByUserID = `-- name: ListUnusedRecoveryCodesByUserID :many
SELECT id, user_id, code_hash, used_at, created_at FROM mfa_recovery_codes
WHERE user_id = ? AND used_at IS NULL ORDER BY created_at, id
`

func (q *Queries) ListUnusedRecoveryCodesByUserID(ctx context.Context, userID int64) ([]MfaRecoveryCode, error) {
	rows, err := q.db.QueryContext(ctx, listUnusedRecoveryCodesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MfaRecoveryCode
	for rows.Next() {
		var i MfaRecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebAuthnCredentialsByUserID = `-- name: ListWebAuthnCredentialsByUserID :many
SELECT credential_id, user_id, name, public_key, aaguid, transports_json, flags, sign_count, clone_warning, attachment, created_at, updated_at, attestation_type, attestation_format, attestation_client_data_json, attestation_client_data_hash, attestation_authenticator_data, attestation_public_key_algorithm, attestation_object FROM webauthn_credentials WHERE user_id = ? ORDER BY created_at, name
`

func (q *Queries) ListWebAuthnCredentialsByUserID(ctx context.Context, userID int64) ([]WebauthnCredential, error) {
	rows, err := q.db.QueryContext(ctx, listWebAuthnCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.CredentialID,
			&i.UserID,
			&i.Name,
			&i.PublicKey,
			&i.Aaguid,
			&i.TransportsJson,
			&i.Flags,
			&i.SignCount,
			&i.CloneWarning,
			&i.Attachment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AttestationType,
			&i.AttestationFormat,
			&i.AttestationClientDataJson,
			&i.AttestationClientDataHash,
			&i.AttestationAuthenticatorData,
			&i.AttestationPublicKeyAlgorithm,
			&i.AttestationObject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMFAUser = `-- name: LockMFAUser :execrows
UPDATE users SET updated_at = updated_at WHERE id = ?
`

func (q *Queries) LockMFAUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockMFAUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const promoteMFAChallengeToWebAuthn = `-- name: PromoteMFAChallengeToWebAuthn :execrows
UPDATE mfa_challenges
SET purpose = ?1, ceremony_json = ?2
WHERE token_hash = ?3
  AND user_id = ?4
  AND purpose = ?5
  AND (session_id = ?6 OR (session_id IS NULL AND ?6 IS NULL))
  AND csrf_hash = ?7
  AND expires_at > ?8
  AND attempts < ?9
`

type PromoteMFAChallengeToWebAuthnParams struct {
	NextPurpose  string         `json:"next_purpose"`
	CeremonyJson string         `json:"ceremony_json"`
	TokenHash    []byte         `json:"token_hash"`
	UserID       int64          `json:"user_id"`
	Purpose      string         `json:"purpose"`
	SessionID    sql.NullString `json:"session_id"`
	CsrfHash     []byte         `json:"csrf_hash"`
	ExpiresAt    int64          `json:"expires_at"`
	Attempts     int64          `json:"attempts"`
}

func (q *Queries) PromoteMFAChallengeToWebAuthn(ctx context.Context, arg PromoteMFAChallengeToWebAuthnParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, promoteMFAChallengeToWebAuthn,
		arg.NextPurpose,
		arg.CeremonyJson,
		arg.TokenHash,
		arg.UserID,
		arg.Purpose,
		arg.SessionID,
		arg.CsrfHash,
		arg.ExpiresAt,
		arg.Attempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renameWebAuthnCredentialByUserID = `-- name: RenameWebAuthnCredentialByUserID :execrows
UPDATE webauthn_credentials
SET name = ?, updated_at = unixepoch()
WHERE credential_id = ? AND user_id = ?
`

type RenameWebAuthnCredentialByUserIDParams struct {
	Name         string `json:"name"`
	CredentialID []byte `json:"credential_id"`
	UserID       int64  `json:"user_id"`
}

func (q *Queries) RenameWebAuthnCredentialByUserID(ctx context.Context, arg RenameWebAuthnCredentialByUserIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameWebAuthnCredentialByUserID, arg.Name, arg.CredentialID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMFARateLimit = `-- name: UpdateMFARateLimit :one
UPDATE mfa_rate_limits
SET window_started_at = ?, failure_count = ?, blocked_until = ?
WHERE user_id = ? RETURNING user_id, window_started_at, failure_count, blocked_until
`

type UpdateMFARateLimitParams struct {
	WindowStartedAt int64         `json:"window_started_at"`
	FailureCount    int64         `json:"failure_count"`
	BlockedUntil    sql.NullInt64 `json:"blocked_until"`
	UserID          int64         `json:"user_id"`
}

func (q *Queries) UpdateMFARateLimit(ctx context.Context, arg UpdateMFARateLimitParams) (MfaRateLimit, error) {
	row := q.db.QueryRowContext(ctx, updateMFARateLimit,
		arg.WindowStartedAt,
		arg.FailureCount,
		arg.BlockedUntil,
		arg.UserID,
	)
	var i MfaRateLimit
	err := row.Scan(
		&i.UserID,
		&i.WindowStartedAt,
		&i.FailureCount,
		&i.BlockedUntil,
	)
	return i, err
}

const updateTOTP = `-- name: UpdateTOTP :one
UPDATE mfa_totp
SET encrypted_seed = ?, last_accepted_step = ?, updated_at = unixepoch()
WHERE user_id = ? RETURNING user_id, encrypted_seed, last_accepted_step, created_at, updated_at
`

type UpdateTOTPParams struct {
	EncryptedSeed    []byte        `json:"encrypted_seed"`
	LastAcceptedStep sql.NullInt64 `json:"last_accepted_step"`
	UserID           int64         `json:"user_id"`
}

func (q *Queries) UpdateTOTP(ctx context.Context, arg UpdateTOTPParams) (MfaTotp, error) {
	row := q.db.QueryRowContext(ctx, updateTOTP, arg.EncryptedSeed, arg.LastAcceptedStep, arg.UserID)
	var i MfaTotp
	err := row.Scan(
		&i.UserID,
		&i.EncryptedSeed,
		&i.LastAcceptedStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebAuthnCredentialCounter = `-- name: UpdateWebAuthnCredentialCounter :one
UPDATE webauthn_credentials
SET sign_count = ?, clone_warning = ?, updated_at = unixepoch()
WHERE credential_id = ? RETURNING credential_id, user_id, name, public_key, aaguid, transports_json, flags, sign_count, clone_warning, attachment, created_at, updated_at, attestation_type, attestation_format, attestation_client_data_json, attestation_client_data_hash, attestation_authenticator_data, attestation_public_key_algorithm, attestation_object
`

type UpdateWebAuthnCredentialCounterParams struct {
	SignCount    int64  `json:"sign_count"`
	CloneWarning int64  `json:"clone_warning"`
	CredentialID []byte `json:"credential_id"`
}

func (q *Queries) UpdateWebAuthnCredentialCounter(ctx context.Context, arg UpdateWebAuthnCredentialCounterParams) (WebauthnCredential, error) {
	row := q.db.QueryRowContext(ctx, updateWebAuthnCredentialCounter, arg.SignCount, arg.CloneWarning, arg.CredentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.CredentialID,
		&i.UserID,
		&i.Name,
		&i.PublicKey,
		&i.Aaguid,
		&i.TransportsJson,
		&i.Flags,
		&i.SignCount,
		&i.CloneWarning,
		&i.Attachment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttestationType,
		&i.AttestationFormat,
		&i.AttestationClientDataJson,
		&i.AttestationClientDataHash,
		&i.AttestationAuthenticatorData,
		&i.AttestationPublicKeyAlgorithm,
		&i.AttestationObject,
	)
	return i, err
}
