// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_events.sql

package db

import (
	"context"
	"database/sql"
)

const createNotificationEvent = `-- name: CreateNotificationEvent :one
INSERT INTO notification_events (event_type, deployment_id, project_id, environment_id, message, results)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, event_type, deployment_id, project_id, environment_id, message, results, created_at
`

type CreateNotificationEventParams struct {
	EventType     string        `json:"event_type"`
	DeploymentID  sql.NullInt64 `json:"deployment_id"`
	ProjectID     sql.NullInt64 `json:"project_id"`
	EnvironmentID sql.NullInt64 `json:"environment_id"`
	Message       string        `json:"message"`
	Results       string        `json:"results"`
}

func (q *Queries) CreateNotificationEvent(ctx context.Context, arg CreateNotificationEventParams) (NotificationEvent, error) {
	row := q.db.QueryRowContext(ctx, createNotificationEvent,
		arg.EventType,
		arg.DeploymentID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Message,
		arg.Results,
	)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.DeploymentID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Message,
		&i.Results,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationEvents = `-- name: ListNotificationEvents :many
SELECT
    ne.id, ne.event_type, ne.deployment_id, ne.project_id, ne.environment_id, ne.message, ne.results, ne.created_at,
    p.name AS project_name,
    e.name AS environment_name
FROM notification_events ne
LEFT JOIN projects p ON p.id = ne.project_id
LEFT JOIN environments e ON e.id = ne.environment_id
ORDER BY ne.created_at DESC
LIMIT ?
`

type ListNotificationEventsRow struct {
	ID              int64          `json:"id"`
	EventType       string         `json:"event_type"`
	DeploymentID    sql.NullInt64  `json:"deployment_id"`
	ProjectID       sql.NullInt64  `json:"project_id"`
	EnvironmentID   sql.NullInt64  `json:"environment_id"`
	Message         string         `json:"message"`
	Results         string         `json:"results"`
	CreatedAt       int64          `json:"created_at"`
	ProjectName     sql.NullString `json:"project_name"`
	EnvironmentName sql.NullString `json:"environment_name"`
}

func (q *Queries) ListNotificationEvents(ctx context.Context, limit int64) ([]ListNotificationEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationEventsRow
	for rows.Next() {
		var i ListNotificationEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.DeploymentID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.Message,
			&i.Results,
			&i.CreatedAt,
			&i.ProjectName,
			&i.EnvironmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
