// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc.sql

package db

import (
	"context"
)

const consumeOIDCTransaction = `-- name: ConsumeOIDCTransaction :execrows
DELETE FROM oidc_transactions WHERE state_hash = ? AND expires_at > ?
`

type ConsumeOIDCTransactionParams struct {
	StateHash string `json:"state_hash"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) ConsumeOIDCTransaction(ctx context.Context, arg ConsumeOIDCTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeOIDCTransaction, arg.StateHash, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createOIDCIdentity = `-- name: CreateOIDCIdentity :one
INSERT INTO oidc_identities (issuer, subject, user_id)
VALUES (?, ?, ?) RETURNING issuer, subject, user_id, created_at
`

type CreateOIDCIdentityParams struct {
	Issuer  string `json:"issuer"`
	Subject string `json:"subject"`
	UserID  int64  `json:"user_id"`
}

func (q *Queries) CreateOIDCIdentity(ctx context.Context, arg CreateOIDCIdentityParams) (OidcIdentity, error) {
	row := q.db.QueryRowContext(ctx, createOIDCIdentity, arg.Issuer, arg.Subject, arg.UserID)
	var i OidcIdentity
	err := row.Scan(
		&i.Issuer,
		&i.Subject,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createOIDCTransaction = `-- name: CreateOIDCTransaction :exec
INSERT INTO oidc_transactions (state_hash, expires_at) VALUES (?, ?)
`

type CreateOIDCTransactionParams struct {
	StateHash string `json:"state_hash"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) CreateOIDCTransaction(ctx context.Context, arg CreateOIDCTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createOIDCTransaction, arg.StateHash, arg.ExpiresAt)
	return err
}

const deleteExpiredOIDCTransactions = `-- name: DeleteExpiredOIDCTransactions :exec
DELETE FROM oidc_transactions WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredOIDCTransactions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOIDCTransactions, expiresAt)
	return err
}

const getOIDCIdentity = `-- name: GetOIDCIdentity :one
SELECT issuer, subject, user_id, created_at FROM oidc_identities WHERE issuer = ? AND subject = ?
`

type GetOIDCIdentityParams struct {
	Issuer  string `json:"issuer"`
	Subject string `json:"subject"`
}

func (q *Queries) GetOIDCIdentity(ctx context.Context, arg GetOIDCIdentityParams) (OidcIdentity, error) {
	row := q.db.QueryRowContext(ctx, getOIDCIdentity, arg.Issuer, arg.Subject)
	var i OidcIdentity
	err := row.Scan(
		&i.Issuer,
		&i.Subject,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getOIDCIdentityByUserID = `-- name: GetOIDCIdentityByUserID :one
SELECT issuer, subject, user_id, created_at FROM oidc_identities WHERE user_id = ?
`

func (q *Queries) GetOIDCIdentityByUserID(ctx context.Context, userID int64) (OidcIdentity, error) {
	row := q.db.QueryRowContext(ctx, getOIDCIdentityByUserID, userID)
	var i OidcIdentity
	err := row.Scan(
		&i.Issuer,
		&i.Subject,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const updateOIDCUser = `-- name: UpdateOIDCUser :one
UPDATE users
SET email = ?1,
    name = ?2,
    role = ?3,
    updated_at = unixepoch()
WHERE id = ?4 AND role = ?5
RETURNING id, email, password_hash, name, role, created_at, updated_at, last_login_at
`

type UpdateOIDCUserParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	Role         string `json:"role"`
	ID           int64  `json:"id"`
	ExpectedRole string `json:"expected_role"`
}

func (q *Queries) UpdateOIDCUser(ctx context.Context, arg UpdateOIDCUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateOIDCUser,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.ID,
		arg.ExpectedRole,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
