// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const clearProjectLifecycle = `-- name: ClearProjectLifecycle :exec
UPDATE projects SET lifecycle_id = NULL WHERE id = ?
`

func (q *Queries) ClearProjectLifecycle(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearProjectLifecycle, id)
	return err
}

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description) VALUES (?, ?) RETURNING id, name, description, created_at, lifecycle_id, slack_webhook_url, notify_emails, gotify_url, gotify_token, discord_webhook_url
`

type CreateProjectParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.LifecycleID,
		&i.SlackWebhookUrl,
		&i.NotifyEmails,
		&i.GotifyUrl,
		&i.GotifyToken,
		&i.DiscordWebhookUrl,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, created_at, lifecycle_id, slack_webhook_url, notify_emails, gotify_url, gotify_token, discord_webhook_url FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.LifecycleID,
		&i.SlackWebhookUrl,
		&i.NotifyEmails,
		&i.GotifyUrl,
		&i.GotifyToken,
		&i.DiscordWebhookUrl,
	)
	return i, err
}

const hasActiveProjectDeployment = `-- name: HasActiveProjectDeployment :one
SELECT CASE WHEN EXISTS (
    SELECT 1 FROM deployments d JOIN releases r ON r.id = d.release_id
    WHERE r.project_id = ?1
      AND (d.status IN ('queued', 'pending', 'running', 'pending_approval', 'publishing_artifact', 'awaiting_artifact_approval', 'cleanup_unconfirmed')
        OR EXISTS (SELECT 1 FROM remote_deployment_claims c WHERE c.deployment_id = d.id
            AND c.state IN ('claimed', 'started', 'cancel_requested', 'lost', 'cancel_unconfirmed'))
        OR EXISTS (SELECT 1 FROM remote_step_runs s WHERE s.deployment_id = d.id
            AND s.state IN ('claimed', 'started', 'cancel_requested', 'lost', 'cancel_unconfirmed')))
) THEN 1 ELSE 0 END
`

func (q *Queries) HasActiveProjectDeployment(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasActiveProjectDeployment, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listProjectDeploymentIDs = `-- name: ListProjectDeploymentIDs :many
SELECT d.id FROM deployments d JOIN releases r ON r.id = d.release_id
WHERE r.project_id = ?
`

func (q *Queries) ListProjectDeploymentIDs(ctx context.Context, projectID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listProjectDeploymentIDs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, created_at, lifecycle_id, slack_webhook_url, notify_emails, gotify_url, gotify_token, discord_webhook_url FROM projects ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.LifecycleID,
			&i.SlackWebhookUrl,
			&i.NotifyEmails,
			&i.GotifyUrl,
			&i.GotifyToken,
			&i.DiscordWebhookUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsPaginated = `-- name: ListProjectsPaginated :many
SELECT id, name, description, created_at, lifecycle_id, slack_webhook_url, notify_emails, gotify_url, gotify_token, discord_webhook_url FROM projects ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListProjectsPaginatedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProjectsPaginated(ctx context.Context, arg ListProjectsPaginatedParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.LifecycleID,
			&i.SlackWebhookUrl,
			&i.NotifyEmails,
			&i.GotifyUrl,
			&i.GotifyToken,
			&i.DiscordWebhookUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProject = `-- name: LockProject :execrows
UPDATE projects SET name = name WHERE id = ?
`

func (q *Queries) LockProject(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setProjectLifecycle = `-- name: SetProjectLifecycle :exec

UPDATE projects SET lifecycle_id = ? WHERE id = ?
`

type SetProjectLifecycleParams struct {
	LifecycleID sql.NullInt64 `json:"lifecycle_id"`
	ID          int64         `json:"id"`
}

// NOSONAR: intentional write lock
func (q *Queries) SetProjectLifecycle(ctx context.Context, arg SetProjectLifecycleParams) error {
	_, err := q.db.ExecContext(ctx, setProjectLifecycle, arg.LifecycleID, arg.ID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET name = ?, description = ? WHERE id = ? RETURNING id, name, description, created_at, lifecycle_id, slack_webhook_url, notify_emails, gotify_url, gotify_token, discord_webhook_url
`

type UpdateProjectParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.Name, arg.Description, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.LifecycleID,
		&i.SlackWebhookUrl,
		&i.NotifyEmails,
		&i.GotifyUrl,
		&i.GotifyToken,
		&i.DiscordWebhookUrl,
	)
	return i, err
}

const updateProjectNotifications = `-- name: UpdateProjectNotifications :exec
UPDATE projects SET slack_webhook_url = ?, notify_emails = ?, gotify_url = ?, gotify_token = ?, discord_webhook_url = ? WHERE id = ?
`

type UpdateProjectNotificationsParams struct {
	SlackWebhookUrl   sql.NullString `json:"slack_webhook_url"`
	NotifyEmails      sql.NullString `json:"notify_emails"`
	GotifyUrl         sql.NullString `json:"gotify_url"`
	GotifyToken       sql.NullString `json:"gotify_token"`
	DiscordWebhookUrl sql.NullString `json:"discord_webhook_url"`
	ID                int64          `json:"id"`
}

func (q *Queries) UpdateProjectNotifications(ctx context.Context, arg UpdateProjectNotificationsParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectNotifications,
		arg.SlackWebhookUrl,
		arg.NotifyEmails,
		arg.GotifyUrl,
		arg.GotifyToken,
		arg.DiscordWebhookUrl,
		arg.ID,
	)
	return err
}
