// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pull_agent_pairing.sql

package db

import (
	"context"
	"database/sql"
)

const assignAgentToEnvironment = `-- name: AssignAgentToEnvironment :one
INSERT INTO environment_agent_assignments (
    environment_id, agent_id, updated_at
) VALUES (?, ?, ?)
ON CONFLICT(environment_id) DO UPDATE
SET agent_id = excluded.agent_id,
    updated_at = excluded.updated_at
RETURNING environment_id, agent_id, created_at, updated_at
`

type AssignAgentToEnvironmentParams struct {
	EnvironmentID int64  `json:"environment_id"`
	AgentID       string `json:"agent_id"`
	UpdatedAt     int64  `json:"updated_at"`
}

func (q *Queries) AssignAgentToEnvironment(ctx context.Context, arg AssignAgentToEnvironmentParams) (EnvironmentAgentAssignment, error) {
	row := q.db.QueryRowContext(ctx, assignAgentToEnvironment, arg.EnvironmentID, arg.AgentID, arg.UpdatedAt)
	var i EnvironmentAgentAssignment
	err := row.Scan(
		&i.EnvironmentID,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const beginAgentPairing = `-- name: BeginAgentPairing :one
UPDATE agent_pairings
SET state = CASE WHEN state = 'pending' THEN 'committing' ELSE state END,
    updated_at = CASE
        WHEN state = 'pending' THEN ?1
        ELSE updated_at
    END
WHERE agent_id = ?2
  AND pairing_code_hash = ?3
  AND agent_pin = ?4
  AND (
      (state = 'pending' AND expires_at > ?5)
      OR state IN ('committing', 'paired')
  )
RETURNING agent_id, pairing_code_hash, agent_public_identity, agent_pin, server_public_identity, server_pin, state, expires_at, paired_at, created_at, updated_at
`

type BeginAgentPairingParams struct {
	UpdatedAt       int64  `json:"updated_at"`
	AgentID         string `json:"agent_id"`
	PairingCodeHash []byte `json:"pairing_code_hash"`
	AgentPin        string `json:"agent_pin"`
	Now             int64  `json:"now"`
}

func (q *Queries) BeginAgentPairing(ctx context.Context, arg BeginAgentPairingParams) (AgentPairing, error) {
	row := q.db.QueryRowContext(ctx, beginAgentPairing,
		arg.UpdatedAt,
		arg.AgentID,
		arg.PairingCodeHash,
		arg.AgentPin,
		arg.Now,
	)
	var i AgentPairing
	err := row.Scan(
		&i.AgentID,
		&i.PairingCodeHash,
		&i.AgentPublicIdentity,
		&i.AgentPin,
		&i.ServerPublicIdentity,
		&i.ServerPin,
		&i.State,
		&i.ExpiresAt,
		&i.PairedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimOldestDirectDeployment = `-- name: ClaimOldestDirectDeployment :one
UPDATE deployment_dispatches
SET state = 'claimed',
    agent_id = ?1,
    claim_token_hash = ?2,
    claim_expires_at = ?3,
    last_heartbeat_at = ?4,
    updated_at = unixepoch()
WHERE deployment_id = (
    SELECT candidate.deployment_id
    FROM deployment_dispatches AS candidate
    JOIN agents AS agent ON agent.id = candidate.assigned_agent_id
    JOIN agent_pairings AS pairing ON pairing.agent_id = agent.id
    WHERE candidate.mode = 'remote'
      AND candidate.state = 'waiting'
      AND candidate.assigned_agent_id = ?1
      AND agent.status = 'active'
      AND pairing.state = 'paired'
      AND NOT EXISTS (
          SELECT 1
          FROM deployment_dispatches AS active_dispatch
          WHERE active_dispatch.agent_id = ?1
            AND active_dispatch.state IN ('claimed', 'started', 'cancel_requested')
      )
    ORDER BY candidate.created_at ASC, candidate.deployment_id ASC
    LIMIT 1
)
AND assigned_agent_id = ?1
AND state = 'waiting'
RETURNING deployment_id, mode, state, reason, agent_id, assigned_agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at
`

type ClaimOldestDirectDeploymentParams struct {
	AgentID         sql.NullString `json:"agent_id"`
	ClaimTokenHash  []byte         `json:"claim_token_hash"`
	ClaimExpiresAt  sql.NullInt64  `json:"claim_expires_at"`
	LastHeartbeatAt sql.NullInt64  `json:"last_heartbeat_at"`
}

func (q *Queries) ClaimOldestDirectDeployment(ctx context.Context, arg ClaimOldestDirectDeploymentParams) (DeploymentDispatch, error) {
	row := q.db.QueryRowContext(ctx, claimOldestDirectDeployment,
		arg.AgentID,
		arg.ClaimTokenHash,
		arg.ClaimExpiresAt,
		arg.LastHeartbeatAt,
	)
	var i DeploymentDispatch
	err := row.Scan(
		&i.DeploymentID,
		&i.Mode,
		&i.State,
		&i.Reason,
		&i.AgentID,
		&i.AssignedAgentID,
		&i.ClaimTokenHash,
		&i.ClaimExpiresAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastHeartbeatAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeAgentPairing = `-- name: CompleteAgentPairing :one
UPDATE agent_pairings
SET state = 'paired',
    agent_public_identity = CASE
        WHEN state = 'committing' THEN ?1
        ELSE agent_public_identity
    END,
    server_public_identity = CASE
        WHEN state = 'committing' THEN ?2
        ELSE server_public_identity
    END,
    server_pin = CASE
        WHEN state = 'committing' THEN ?3
        ELSE server_pin
    END,
    paired_at = CASE
        WHEN state = 'committing' THEN ?4
        ELSE paired_at
    END,
    updated_at = CASE
        WHEN state = 'committing' THEN ?5
        ELSE updated_at
    END
WHERE agent_id = ?6
  AND pairing_code_hash = ?7
  AND agent_pin = ?8
  AND (
      state = 'committing'
      OR state = 'paired'
  )
RETURNING agent_id, pairing_code_hash, agent_public_identity, agent_pin, server_public_identity, server_pin, state, expires_at, paired_at, created_at, updated_at
`

type CompleteAgentPairingParams struct {
	AgentPublicIdentity  string         `json:"agent_public_identity"`
	ServerPublicIdentity sql.NullString `json:"server_public_identity"`
	ServerPin            sql.NullString `json:"server_pin"`
	PairedAt             sql.NullInt64  `json:"paired_at"`
	UpdatedAt            int64          `json:"updated_at"`
	AgentID              string         `json:"agent_id"`
	PairingCodeHash      []byte         `json:"pairing_code_hash"`
	AgentPin             string         `json:"agent_pin"`
}

func (q *Queries) CompleteAgentPairing(ctx context.Context, arg CompleteAgentPairingParams) (AgentPairing, error) {
	row := q.db.QueryRowContext(ctx, completeAgentPairing,
		arg.AgentPublicIdentity,
		arg.ServerPublicIdentity,
		arg.ServerPin,
		arg.PairedAt,
		arg.UpdatedAt,
		arg.AgentID,
		arg.PairingCodeHash,
		arg.AgentPin,
	)
	var i AgentPairing
	err := row.Scan(
		&i.AgentID,
		&i.PairingCodeHash,
		&i.AgentPublicIdentity,
		&i.AgentPin,
		&i.ServerPublicIdentity,
		&i.ServerPin,
		&i.State,
		&i.ExpiresAt,
		&i.PairedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentPairing = `-- name: CreateAgentPairing :one
INSERT INTO agent_pairings (
    agent_id,
    pairing_code_hash,
    agent_public_identity,
    agent_pin,
    state,
    expires_at
) VALUES (?, ?, ?, ?, 'pending', ?)
ON CONFLICT(agent_id) DO UPDATE
SET pairing_code_hash = excluded.pairing_code_hash,
    agent_public_identity = excluded.agent_public_identity,
    agent_pin = excluded.agent_pin,
    server_public_identity = NULL,
    server_pin = NULL,
    state = 'pending',
    expires_at = excluded.expires_at,
    paired_at = NULL,
    updated_at = unixepoch()
WHERE agent_pairings.state IN ('pending', 'expired')
RETURNING agent_id, pairing_code_hash, agent_public_identity, agent_pin, server_public_identity, server_pin, state, expires_at, paired_at, created_at, updated_at
`

type CreateAgentPairingParams struct {
	AgentID             string `json:"agent_id"`
	PairingCodeHash     []byte `json:"pairing_code_hash"`
	AgentPublicIdentity string `json:"agent_public_identity"`
	AgentPin            string `json:"agent_pin"`
	ExpiresAt           int64  `json:"expires_at"`
}

func (q *Queries) CreateAgentPairing(ctx context.Context, arg CreateAgentPairingParams) (AgentPairing, error) {
	row := q.db.QueryRowContext(ctx, createAgentPairing,
		arg.AgentID,
		arg.PairingCodeHash,
		arg.AgentPublicIdentity,
		arg.AgentPin,
		arg.ExpiresAt,
	)
	var i AgentPairing
	err := row.Scan(
		&i.AgentID,
		&i.PairingCodeHash,
		&i.AgentPublicIdentity,
		&i.AgentPin,
		&i.ServerPublicIdentity,
		&i.ServerPin,
		&i.State,
		&i.ExpiresAt,
		&i.PairedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDirectDeploymentDispatch = `-- name: CreateDirectDeploymentDispatch :one
INSERT INTO deployment_dispatches (
    deployment_id, mode, state, assigned_agent_id
) VALUES (?, 'remote', 'waiting', ?)
RETURNING deployment_id, mode, state, reason, agent_id, assigned_agent_id, claim_token_hash, claim_expires_at, started_at, finished_at, last_heartbeat_at, cancel_requested_at, created_at, updated_at
`

type CreateDirectDeploymentDispatchParams struct {
	DeploymentID    int64          `json:"deployment_id"`
	AssignedAgentID sql.NullString `json:"assigned_agent_id"`
}

func (q *Queries) CreateDirectDeploymentDispatch(ctx context.Context, arg CreateDirectDeploymentDispatchParams) (DeploymentDispatch, error) {
	row := q.db.QueryRowContext(ctx, createDirectDeploymentDispatch, arg.DeploymentID, arg.AssignedAgentID)
	var i DeploymentDispatch
	err := row.Scan(
		&i.DeploymentID,
		&i.Mode,
		&i.State,
		&i.Reason,
		&i.AgentID,
		&i.AssignedAgentID,
		&i.ClaimTokenHash,
		&i.ClaimExpiresAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastHeartbeatAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentPairing = `-- name: DeleteAgentPairing :execrows
DELETE FROM agent_pairings WHERE agent_id = ?
`

func (q *Queries) DeleteAgentPairing(ctx context.Context, agentID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAgentPairing, agentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEnvironmentAgentAssignment = `-- name: DeleteEnvironmentAgentAssignment :execrows
DELETE FROM environment_agent_assignments WHERE environment_id = ?
`

func (q *Queries) DeleteEnvironmentAgentAssignment(ctx context.Context, environmentID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEnvironmentAgentAssignment, environmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEnvironmentAgentAssignmentsByAgent = `-- name: DeleteEnvironmentAgentAssignmentsByAgent :execrows
DELETE FROM environment_agent_assignments WHERE agent_id = ?
`

func (q *Queries) DeleteEnvironmentAgentAssignmentsByAgent(ctx context.Context, agentID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEnvironmentAgentAssignmentsByAgent, agentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePendingAgentPairing = `-- name: DeletePendingAgentPairing :execrows
DELETE FROM agent_pairings
WHERE agent_id = ?
  AND state = 'pending'
`

func (q *Queries) DeletePendingAgentPairing(ctx context.Context, agentID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingAgentPairing, agentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expirePendingAgentPairings = `-- name: ExpirePendingAgentPairings :execrows
UPDATE agent_pairings
SET state = 'expired', updated_at = ?1
WHERE state = 'pending'
  AND expires_at <= ?2
`

type ExpirePendingAgentPairingsParams struct {
	UpdatedAt     int64 `json:"updated_at"`
	ExpiresBefore int64 `json:"expires_before"`
}

func (q *Queries) ExpirePendingAgentPairings(ctx context.Context, arg ExpirePendingAgentPairingsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expirePendingAgentPairings, arg.UpdatedAt, arg.ExpiresBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgentPairing = `-- name: GetAgentPairing :one
SELECT agent_id, pairing_code_hash, agent_public_identity, agent_pin, server_public_identity, server_pin, state, expires_at, paired_at, created_at, updated_at FROM agent_pairings WHERE agent_id = ?
`

func (q *Queries) GetAgentPairing(ctx context.Context, agentID string) (AgentPairing, error) {
	row := q.db.QueryRowContext(ctx, getAgentPairing, agentID)
	var i AgentPairing
	err := row.Scan(
		&i.AgentID,
		&i.PairingCodeHash,
		&i.AgentPublicIdentity,
		&i.AgentPin,
		&i.ServerPublicIdentity,
		&i.ServerPin,
		&i.State,
		&i.ExpiresAt,
		&i.PairedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironmentAgentAssignment = `-- name: GetEnvironmentAgentAssignment :one
SELECT environment_id, agent_id, created_at, updated_at FROM environment_agent_assignments WHERE environment_id = ?
`

func (q *Queries) GetEnvironmentAgentAssignment(ctx context.Context, environmentID int64) (EnvironmentAgentAssignment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentAgentAssignment, environmentID)
	var i EnvironmentAgentAssignment
	err := row.Scan(
		&i.EnvironmentID,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironmentAgentAssignmentsByAgent = `-- name: ListEnvironmentAgentAssignmentsByAgent :many
SELECT environment_id, agent_id, created_at, updated_at FROM environment_agent_assignments
WHERE agent_id = ?
ORDER BY environment_id ASC
`

func (q *Queries) ListEnvironmentAgentAssignmentsByAgent(ctx context.Context, agentID string) ([]EnvironmentAgentAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironmentAgentAssignmentsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentAgentAssignment
	for rows.Next() {
		var i EnvironmentAgentAssignment
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.AgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
