// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remote_steps.sql

package db

import (
	"context"
	"database/sql"
)

const acknowledgeRemoteStepCancellation = `-- name: AcknowledgeRemoteStepCancellation :execrows
UPDATE remote_step_runs SET state = 'cancelled', finished_at = ?1,
    updated_at = ?1
WHERE deployment_id = ?2
  AND step_index = ?3 AND agent_id = ?4
  AND claim_token_hash = ?5
  AND state = 'cancel_requested'
`

type AcknowledgeRemoteStepCancellationParams struct {
	Now            sql.NullInt64 `json:"now"`
	DeploymentID   int64         `json:"deployment_id"`
	StepIndex      int64         `json:"step_index"`
	AgentID        string        `json:"agent_id"`
	ClaimTokenHash []byte        `json:"claim_token_hash"`
}

func (q *Queries) AcknowledgeRemoteStepCancellation(ctx context.Context, arg AcknowledgeRemoteStepCancellationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acknowledgeRemoteStepCancellation,
		arg.Now,
		arg.DeploymentID,
		arg.StepIndex,
		arg.AgentID,
		arg.ClaimTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimRemoteStepRun = `-- name: ClaimRemoteStepRun :execrows
UPDATE remote_step_runs SET state = 'claimed',
    claim_token_hash = ?1,
    ciphertext = ?2,
    claim_expires_at = ?3,
    last_heartbeat_at = ?4, updated_at = ?4
WHERE deployment_id = ?5
  AND step_index = ?6
  AND agent_id = ?7 AND state = 'waiting'
`

type ClaimRemoteStepRunParams struct {
	ClaimTokenHash []byte         `json:"claim_token_hash"`
	Ciphertext     sql.NullString `json:"ciphertext"`
	ClaimExpiresAt sql.NullInt64  `json:"claim_expires_at"`
	Now            sql.NullInt64  `json:"now"`
	DeploymentID   int64          `json:"deployment_id"`
	StepIndex      int64          `json:"step_index"`
	AgentID        string         `json:"agent_id"`
}

func (q *Queries) ClaimRemoteStepRun(ctx context.Context, arg ClaimRemoteStepRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimRemoteStepRun,
		arg.ClaimTokenHash,
		arg.Ciphertext,
		arg.ClaimExpiresAt,
		arg.Now,
		arg.DeploymentID,
		arg.StepIndex,
		arg.AgentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createRemoteStepLogSequence = `-- name: CreateRemoteStepLogSequence :exec
INSERT INTO remote_step_log_sequences
    (deployment_id, step_index, agent_id, sequence, log_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateRemoteStepLogSequenceParams struct {
	DeploymentID int64  `json:"deployment_id"`
	StepIndex    int64  `json:"step_index"`
	AgentID      string `json:"agent_id"`
	Sequence     int64  `json:"sequence"`
	LogID        int64  `json:"log_id"`
}

func (q *Queries) CreateRemoteStepLogSequence(ctx context.Context, arg CreateRemoteStepLogSequenceParams) error {
	_, err := q.db.ExecContext(ctx, createRemoteStepLogSequence,
		arg.DeploymentID,
		arg.StepIndex,
		arg.AgentID,
		arg.Sequence,
		arg.LogID,
	)
	return err
}

const createRemoteStepRuns = `-- name: CreateRemoteStepRuns :execrows
INSERT INTO remote_step_runs (deployment_id, step_index, agent_id)
SELECT s.deployment_id, s.step_index, a.id
FROM deployment_steps s
JOIN deployments d ON d.id = s.deployment_id
JOIN agents a ON a.status = 'active' AND a.revoked_at IS NULL
JOIN agent_pairings p ON p.agent_id = a.id AND p.state = 'paired'
JOIN agent_environment_labels e ON e.agent_id = a.id
    AND e.environment_id = d.environment_id
WHERE s.deployment_id = ?1
  AND s.step_index = ?2
  AND s.execution_target = 'agent'
  AND d.status = 'running'
  AND NOT EXISTS (
      SELECT 1 FROM deployment_step_selectors wanted
      WHERE wanted.deployment_id = s.deployment_id
        AND wanted.step_index = s.step_index
        AND NOT EXISTS (
            SELECT 1 FROM agent_labels owned
            WHERE owned.agent_id = a.id
              AND lower(owned.label) = lower(wanted.label)
        )
  )
  AND NOT EXISTS (
      SELECT 1 FROM remote_step_runs existing
      WHERE existing.deployment_id = s.deployment_id
        AND existing.step_index = s.step_index
        AND existing.agent_id = a.id
  )
`

type CreateRemoteStepRunsParams struct {
	DeploymentID int64 `json:"deployment_id"`
	StepIndex    int64 `json:"step_index"`
}

func (q *Queries) CreateRemoteStepRuns(ctx context.Context, arg CreateRemoteStepRunsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createRemoteStepRuns, arg.DeploymentID, arg.StepIndex)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expireRemoteStepCancellations = `-- name: ExpireRemoteStepCancellations :execrows
UPDATE remote_step_runs SET state = 'cancel_unconfirmed', finished_at = ?1,
    updated_at = ?1, log_buffer_ciphertext = NULL
WHERE state = 'cancel_requested'
  AND cancel_requested_at <= ?2
`

type ExpireRemoteStepCancellationsParams struct {
	Now         sql.NullInt64 `json:"now"`
	StaleBefore sql.NullInt64 `json:"stale_before"`
}

func (q *Queries) ExpireRemoteStepCancellations(ctx context.Context, arg ExpireRemoteStepCancellationsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireRemoteStepCancellations, arg.Now, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expireRemoteStepClaims = `-- name: ExpireRemoteStepClaims :execrows
UPDATE remote_step_runs SET state = 'waiting', claim_token_hash = NULL,
    ciphertext = NULL, claim_expires_at = NULL, last_heartbeat_at = NULL,
    updated_at = ?1
WHERE state = 'claimed' AND started_at IS NULL
  AND claim_expires_at <= ?1
`

func (q *Queries) ExpireRemoteStepClaims(ctx context.Context, now int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireRemoteStepClaims, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishRemoteStepRun = `-- name: FinishRemoteStepRun :execrows
UPDATE remote_step_runs SET state = ?1, finished_at = ?2,
    updated_at = ?2
WHERE deployment_id = ?3
  AND step_index = ?4 AND agent_id = ?5
  AND claim_token_hash = ?6 AND state = 'started'
`

type FinishRemoteStepRunParams struct {
	State          string        `json:"state"`
	Now            sql.NullInt64 `json:"now"`
	DeploymentID   int64         `json:"deployment_id"`
	StepIndex      int64         `json:"step_index"`
	AgentID        string        `json:"agent_id"`
	ClaimTokenHash []byte        `json:"claim_token_hash"`
}

func (q *Queries) FinishRemoteStepRun(ctx context.Context, arg FinishRemoteStepRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishRemoteStepRun,
		arg.State,
		arg.Now,
		arg.DeploymentID,
		arg.StepIndex,
		arg.AgentID,
		arg.ClaimTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLastRemoteStepLogSequence = `-- name: GetLastRemoteStepLogSequence :one
SELECT CAST(COALESCE(MAX(sequence), -1) AS INTEGER) FROM remote_step_log_sequences
WHERE deployment_id = ?1
  AND step_index = ?2
  AND agent_id = ?3
`

type GetLastRemoteStepLogSequenceParams struct {
	DeploymentID int64  `json:"deployment_id"`
	StepIndex    int64  `json:"step_index"`
	AgentID      string `json:"agent_id"`
}

func (q *Queries) GetLastRemoteStepLogSequence(ctx context.Context, arg GetLastRemoteStepLogSequenceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLastRemoteStepLogSequence, arg.DeploymentID, arg.StepIndex, arg.AgentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getRemoteStepLogBySequence = `-- name: GetRemoteStepLogBySequence :one
SELECT l.id, l.deployment_id, l.step_name, l.line, l.created_at FROM deployment_logs l
JOIN remote_step_log_sequences s ON s.log_id = l.id
WHERE s.deployment_id = ? AND s.step_index = ? AND s.agent_id = ?
  AND s.sequence = ?
`

type GetRemoteStepLogBySequenceParams struct {
	DeploymentID int64  `json:"deployment_id"`
	StepIndex    int64  `json:"step_index"`
	AgentID      string `json:"agent_id"`
	Sequence     int64  `json:"sequence"`
}

func (q *Queries) GetRemoteStepLogBySequence(ctx context.Context, arg GetRemoteStepLogBySequenceParams) (DeploymentLog, error) {
	row := q.db.QueryRowContext(ctx, getRemoteStepLogBySequence,
		arg.DeploymentID,
		arg.StepIndex,
		arg.AgentID,
		arg.Sequence,
	)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.StepName,
		&i.Line,
		&i.CreatedAt,
	)
	return i, err
}

const getRemoteStepRunByClaim = `-- name: GetRemoteStepRunByClaim :one
SELECT deployment_id, step_index, agent_id, state, claim_token_hash, ciphertext, claim_expires_at, last_heartbeat_at, started_at, finished_at, cancel_requested_at, created_at, updated_at, log_buffer_ciphertext, recovery_cancelled FROM remote_step_runs
WHERE deployment_id = ?1
  AND agent_id = ?2
  AND claim_token_hash = ?3
`

type GetRemoteStepRunByClaimParams struct {
	DeploymentID   int64  `json:"deployment_id"`
	AgentID        string `json:"agent_id"`
	ClaimTokenHash []byte `json:"claim_token_hash"`
}

func (q *Queries) GetRemoteStepRunByClaim(ctx context.Context, arg GetRemoteStepRunByClaimParams) (RemoteStepRun, error) {
	row := q.db.QueryRowContext(ctx, getRemoteStepRunByClaim, arg.DeploymentID, arg.AgentID, arg.ClaimTokenHash)
	var i RemoteStepRun
	err := row.Scan(
		&i.DeploymentID,
		&i.StepIndex,
		&i.AgentID,
		&i.State,
		&i.ClaimTokenHash,
		&i.Ciphertext,
		&i.ClaimExpiresAt,
		&i.LastHeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CancelRequestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogBufferCiphertext,
		&i.RecoveryCancelled,
	)
	return i, err
}

const heartbeatRemoteStepRun = `-- name: HeartbeatRemoteStepRun :execrows
UPDATE remote_step_runs SET last_heartbeat_at = ?1, updated_at = ?1
WHERE deployment_id = ?2
  AND step_index = ?3 AND agent_id = ?4
  AND claim_token_hash = ?5
  AND state IN ('started', 'cancel_requested')
`

type HeartbeatRemoteStepRunParams struct {
	Now            sql.NullInt64 `json:"now"`
	DeploymentID   int64         `json:"deployment_id"`
	StepIndex      int64         `json:"step_index"`
	AgentID        string        `json:"agent_id"`
	ClaimTokenHash []byte        `json:"claim_token_hash"`
}

func (q *Queries) HeartbeatRemoteStepRun(ctx context.Context, arg HeartbeatRemoteStepRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, heartbeatRemoteStepRun,
		arg.Now,
		arg.DeploymentID,
		arg.StepIndex,
		arg.AgentID,
		arg.ClaimTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listRemoteStepRuns = `-- name: ListRemoteStepRuns :many
SELECT deployment_id, step_index, agent_id, state, claim_token_hash, ciphertext, claim_expires_at, last_heartbeat_at, started_at, finished_at, cancel_requested_at, created_at, updated_at, log_buffer_ciphertext, recovery_cancelled FROM remote_step_runs
WHERE deployment_id = ? AND step_index = ? ORDER BY agent_id
`

type ListRemoteStepRunsParams struct {
	DeploymentID int64 `json:"deployment_id"`
	StepIndex    int64 `json:"step_index"`
}

func (q *Queries) ListRemoteStepRuns(ctx context.Context, arg ListRemoteStepRunsParams) ([]RemoteStepRun, error) {
	rows, err := q.db.QueryContext(ctx, listRemoteStepRuns, arg.DeploymentID, arg.StepIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteStepRun
	for rows.Next() {
		var i RemoteStepRun
		if err := rows.Scan(
			&i.DeploymentID,
			&i.StepIndex,
			&i.AgentID,
			&i.State,
			&i.ClaimTokenHash,
			&i.Ciphertext,
			&i.ClaimExpiresAt,
			&i.LastHeartbeatAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LogBufferCiphertext,
			&i.RecoveryCancelled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingRemoteStepRuns = `-- name: ListWaitingRemoteStepRuns :many
SELECT r.deployment_id, r.step_index, r.agent_id, r.state, r.claim_token_hash, r.ciphertext, r.claim_expires_at, r.last_heartbeat_at, r.started_at, r.finished_at, r.cancel_requested_at, r.created_at, r.updated_at, r.log_buffer_ciphertext, r.recovery_cancelled FROM remote_step_runs r
JOIN deployments d ON d.id = r.deployment_id
WHERE r.agent_id = ?1 AND r.state = 'waiting'
  AND d.status = 'running'
  AND NOT EXISTS (
      SELECT 1 FROM remote_deployment_claims legacy
      WHERE legacy.agent_id = r.agent_id
        AND legacy.state IN ('claimed', 'started', 'cancel_requested')
  )
ORDER BY r.created_at, r.deployment_id, r.step_index
`

func (q *Queries) ListWaitingRemoteStepRuns(ctx context.Context, agentID string) ([]RemoteStepRun, error) {
	rows, err := q.db.QueryContext(ctx, listWaitingRemoteStepRuns, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoteStepRun
	for rows.Next() {
		var i RemoteStepRun
		if err := rows.Scan(
			&i.DeploymentID,
			&i.StepIndex,
			&i.AgentID,
			&i.State,
			&i.ClaimTokenHash,
			&i.Ciphertext,
			&i.ClaimExpiresAt,
			&i.LastHeartbeatAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CancelRequestedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LogBufferCiphertext,
			&i.RecoveryCancelled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRemoteStepRun = `-- name: LockRemoteStepRun :execrows
UPDATE remote_step_runs SET updated_at = updated_at -- NOSONAR: intentional write lock
WHERE deployment_id = ?1
  AND agent_id = ?2
  AND claim_token_hash = ?3
`

type LockRemoteStepRunParams struct {
	DeploymentID   int64  `json:"deployment_id"`
	AgentID        string `json:"agent_id"`
	ClaimTokenHash []byte `json:"claim_token_hash"`
}

func (q *Queries) LockRemoteStepRun(ctx context.Context, arg LockRemoteStepRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockRemoteStepRun, arg.DeploymentID, arg.AgentID, arg.ClaimTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const loseStaleRemoteStepRuns = `-- name: LoseStaleRemoteStepRuns :execrows
UPDATE remote_step_runs SET state = 'lost', finished_at = ?1,
    updated_at = ?1, log_buffer_ciphertext = NULL
WHERE state = 'started'
  AND last_heartbeat_at <= ?2
`

type LoseStaleRemoteStepRunsParams struct {
	Now         sql.NullInt64 `json:"now"`
	StaleBefore sql.NullInt64 `json:"stale_before"`
}

func (q *Queries) LoseStaleRemoteStepRuns(ctx context.Context, arg LoseStaleRemoteStepRunsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, loseStaleRemoteStepRuns, arg.Now, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requestRemoteStepCancellation = `-- name: RequestRemoteStepCancellation :execrows
UPDATE remote_step_runs SET
    state = CASE WHEN state = 'waiting' THEN 'cancelled'
        ELSE 'cancel_requested' END,
    cancel_requested_at = ?1,
    finished_at = CASE WHEN state = 'waiting' THEN ?1
        ELSE finished_at END,
    updated_at = ?1
WHERE deployment_id = ?2
  AND state IN ('waiting', 'claimed', 'started')
`

type RequestRemoteStepCancellationParams struct {
	Now          sql.NullInt64 `json:"now"`
	DeploymentID int64         `json:"deployment_id"`
}

func (q *Queries) RequestRemoteStepCancellation(ctx context.Context, arg RequestRemoteStepCancellationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestRemoteStepCancellation, arg.Now, arg.DeploymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startRemoteStepRun = `-- name: StartRemoteStepRun :execrows
UPDATE remote_step_runs SET state = 'started', started_at = ?1,
    last_heartbeat_at = ?1, updated_at = ?1
WHERE remote_step_runs.deployment_id = ?2
  AND remote_step_runs.step_index = ?3
  AND remote_step_runs.agent_id = ?4
  AND remote_step_runs.claim_token_hash = ?5
  AND remote_step_runs.state = 'claimed'
  AND remote_step_runs.claim_expires_at > ?1
  AND EXISTS (SELECT 1 FROM agents a
      WHERE a.id = remote_step_runs.agent_id AND a.status = 'active'
        AND EXISTS (SELECT 1 FROM agent_pairings p
            WHERE p.agent_id = a.id AND p.state = 'paired'))
`

type StartRemoteStepRunParams struct {
	Now            sql.NullInt64 `json:"now"`
	DeploymentID   int64         `json:"deployment_id"`
	StepIndex      int64         `json:"step_index"`
	AgentID        string        `json:"agent_id"`
	ClaimTokenHash []byte        `json:"claim_token_hash"`
}

func (q *Queries) StartRemoteStepRun(ctx context.Context, arg StartRemoteStepRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startRemoteStepRun,
		arg.Now,
		arg.DeploymentID,
		arg.StepIndex,
		arg.AgentID,
		arg.ClaimTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRemoteStepLogBuffer = `-- name: UpdateRemoteStepLogBuffer :execrows
UPDATE remote_step_runs
SET log_buffer_ciphertext = ?1
WHERE deployment_id = ?2
  AND step_index = ?3
  AND agent_id = ?4
  AND claim_token_hash = ?5
`

type UpdateRemoteStepLogBufferParams struct {
	LogBufferCiphertext sql.NullString `json:"log_buffer_ciphertext"`
	DeploymentID        int64          `json:"deployment_id"`
	StepIndex           int64          `json:"step_index"`
	AgentID             string         `json:"agent_id"`
	ClaimTokenHash      []byte         `json:"claim_token_hash"`
}

func (q *Queries) UpdateRemoteStepLogBuffer(ctx context.Context, arg UpdateRemoteStepLogBufferParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRemoteStepLogBuffer,
		arg.LogBufferCiphertext,
		arg.DeploymentID,
		arg.StepIndex,
		arg.AgentID,
		arg.ClaimTokenHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
