// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rollback.sql

package db

import (
	"context"
)

const createDeploymentRollback = `-- name: CreateDeploymentRollback :exec
INSERT INTO deployment_rollbacks (deployment_id, source_deployment_id, target_deployment_id, source_version, target_version)
VALUES (?, ?, ?, ?, ?)
`

type CreateDeploymentRollbackParams struct {
	DeploymentID       int64  `json:"deployment_id"`
	SourceDeploymentID int64  `json:"source_deployment_id"`
	TargetDeploymentID int64  `json:"target_deployment_id"`
	SourceVersion      string `json:"source_version"`
	TargetVersion      string `json:"target_version"`
}

func (q *Queries) CreateDeploymentRollback(ctx context.Context, arg CreateDeploymentRollbackParams) error {
	_, err := q.db.ExecContext(ctx, createDeploymentRollback,
		arg.DeploymentID,
		arg.SourceDeploymentID,
		arg.TargetDeploymentID,
		arg.SourceVersion,
		arg.TargetVersion,
	)
	return err
}

const getDeploymentRollback = `-- name: GetDeploymentRollback :one
SELECT deployment_id, source_deployment_id, target_deployment_id, source_version, target_version FROM deployment_rollbacks WHERE deployment_id = ?
`

func (q *Queries) GetDeploymentRollback(ctx context.Context, deploymentID int64) (DeploymentRollback, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentRollback, deploymentID)
	var i DeploymentRollback
	err := row.Scan(
		&i.DeploymentID,
		&i.SourceDeploymentID,
		&i.TargetDeploymentID,
		&i.SourceVersion,
		&i.TargetVersion,
	)
	return i, err
}

const getLatestProjectEnvironmentDeployment = `-- name: GetLatestProjectEnvironmentDeployment :one
SELECT d.id, d.release_id, d.environment_id, d.status, d.started_at, d.finished_at, d.created_at, d.forced, d.note, d.assigned_agent_id, d.kind, d.container_namespace, d.cleanup_confirmed_at FROM deployments d JOIN releases r ON r.id = d.release_id
WHERE r.project_id = ? AND d.environment_id = ? AND d.kind = 'deployment'
ORDER BY d.created_at DESC, d.id DESC LIMIT 1
`

type GetLatestProjectEnvironmentDeploymentParams struct {
	ProjectID     int64 `json:"project_id"`
	EnvironmentID int64 `json:"environment_id"`
}

func (q *Queries) GetLatestProjectEnvironmentDeployment(ctx context.Context, arg GetLatestProjectEnvironmentDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getLatestProjectEnvironmentDeployment, arg.ProjectID, arg.EnvironmentID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.EnvironmentID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.Forced,
		&i.Note,
		&i.AssignedAgentID,
		&i.Kind,
		&i.ContainerNamespace,
		&i.CleanupConfirmedAt,
	)
	return i, err
}

const getRollbackTarget = `-- name: GetRollbackTarget :one
SELECT d.id, d.release_id, d.environment_id, d.status, d.started_at, d.finished_at, d.created_at, d.forced, d.note, d.assigned_agent_id, d.kind, d.container_namespace, d.cleanup_confirmed_at FROM deployments d JOIN releases r ON r.id = d.release_id
JOIN deployments source ON source.id = ?1
JOIN releases source_release ON source_release.id = source.release_id
WHERE r.project_id = source_release.project_id
  AND d.environment_id = source.environment_id
  AND d.kind = 'deployment' AND d.status = 'succeeded'
  AND d.release_id != source.release_id
  AND (d.created_at < source.created_at OR (d.created_at = source.created_at AND d.id < source.id))
ORDER BY d.created_at DESC, d.id DESC LIMIT 1
`

func (q *Queries) GetRollbackTarget(ctx context.Context, sourceDeploymentID int64) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getRollbackTarget, sourceDeploymentID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.EnvironmentID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.Forced,
		&i.Note,
		&i.AssignedAgentID,
		&i.Kind,
		&i.ContainerNamespace,
		&i.CleanupConfirmedAt,
	)
	return i, err
}

const hasActiveProjectEnvironmentDeployment = `-- name: HasActiveProjectEnvironmentDeployment :one
SELECT CASE WHEN EXISTS (
    SELECT 1 FROM deployments d JOIN releases r ON r.id = d.release_id
    WHERE r.project_id = ? AND d.environment_id = ? AND d.kind = 'deployment'
      AND (d.status IN ('queued', 'pending', 'running', 'pending_approval', 'publishing_artifact', 'awaiting_artifact_approval')
        OR (d.status = 'cleanup_unconfirmed'
            AND (d.container_namespace IS NOT NULL OR (
            d.cleanup_confirmed_at IS NULL AND
            NOT EXISTS (SELECT 1 FROM remote_step_runs s
                WHERE s.deployment_id = d.id AND s.state = 'cleanup_unconfirmed')
            AND NOT EXISTS (SELECT 1 FROM remote_deployment_claims c
                WHERE c.deployment_id = d.id AND c.state = 'cleanup_unconfirmed'))))
        OR EXISTS (SELECT 1 FROM remote_deployment_claims c
                   WHERE c.deployment_id = d.id
                     AND (c.state IN ('claimed', 'started', 'cancel_requested', 'lost', 'cancel_unconfirmed')
                       OR (c.state = 'cleanup_unconfirmed'
                           AND c.cleanup_confirmed_at IS NULL)))
        OR EXISTS (SELECT 1 FROM remote_step_runs s
                   WHERE s.deployment_id = d.id
                     AND (s.state IN ('claimed', 'started', 'cancel_requested', 'lost', 'cancel_unconfirmed')
                       OR (s.state = 'cleanup_unconfirmed'
                           AND s.cleanup_confirmed_at IS NULL))))
) THEN 1 ELSE 0 END
`

type HasActiveProjectEnvironmentDeploymentParams struct {
	ProjectID     int64 `json:"project_id"`
	EnvironmentID int64 `json:"environment_id"`
}

func (q *Queries) HasActiveProjectEnvironmentDeployment(ctx context.Context, arg HasActiveProjectEnvironmentDeploymentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasActiveProjectEnvironmentDeployment, arg.ProjectID, arg.EnvironmentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
