// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runbooks.sql

package db

import (
	"context"
	"database/sql"
)

const advanceRunbookSchedule = `-- name: AdvanceRunbookSchedule :execrows
UPDATE runbook_schedules SET next_run_at = ?, last_fired_at = ?
WHERE id = ? AND enabled = 1 AND next_run_at <= ?
`

type AdvanceRunbookScheduleParams struct {
	NextRunAt   int64         `json:"next_run_at"`
	LastFiredAt sql.NullInt64 `json:"last_fired_at"`
	ID          int64         `json:"id"`
	NextRunAt_2 int64         `json:"next_run_at_2"`
}

func (q *Queries) AdvanceRunbookSchedule(ctx context.Context, arg AdvanceRunbookScheduleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceRunbookSchedule,
		arg.NextRunAt,
		arg.LastFiredAt,
		arg.ID,
		arg.NextRunAt_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countRunbookExecutions = `-- name: CountRunbookExecutions :one
SELECT COUNT(*) FROM runbook_executions x
JOIN runbook_versions v ON v.id = x.runbook_version_id
JOIN runbooks b ON b.id = v.runbook_id
WHERE b.project_id = ?
`

func (q *Queries) CountRunbookExecutions(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunbookExecutions, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRunbook = `-- name: CreateRunbook :one
INSERT INTO runbooks (project_id, name, description) VALUES (?, ?, ?) RETURNING id, project_id, name, description, created_at
`

type CreateRunbookParams struct {
	ProjectID   int64  `json:"project_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateRunbook(ctx context.Context, arg CreateRunbookParams) (Runbook, error) {
	row := q.db.QueryRowContext(ctx, createRunbook, arg.ProjectID, arg.Name, arg.Description)
	var i Runbook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createRunbookExecution = `-- name: CreateRunbookExecution :one
INSERT INTO runbook_executions
    (runbook_version_id, deployment_id, actor_user_id, schedule_id)
VALUES (?, ?, ?, ?) RETURNING id, runbook_version_id, deployment_id, actor_user_id, schedule_id, created_at
`

type CreateRunbookExecutionParams struct {
	RunbookVersionID int64         `json:"runbook_version_id"`
	DeploymentID     int64         `json:"deployment_id"`
	ActorUserID      sql.NullInt64 `json:"actor_user_id"`
	ScheduleID       sql.NullInt64 `json:"schedule_id"`
}

func (q *Queries) CreateRunbookExecution(ctx context.Context, arg CreateRunbookExecutionParams) (RunbookExecution, error) {
	row := q.db.QueryRowContext(ctx, createRunbookExecution,
		arg.RunbookVersionID,
		arg.DeploymentID,
		arg.ActorUserID,
		arg.ScheduleID,
	)
	var i RunbookExecution
	err := row.Scan(
		&i.ID,
		&i.RunbookVersionID,
		&i.DeploymentID,
		&i.ActorUserID,
		&i.ScheduleID,
		&i.CreatedAt,
	)
	return i, err
}

const createRunbookSchedule = `-- name: CreateRunbookSchedule :one
INSERT INTO runbook_schedules
    (runbook_id, version_id, environment_id, cron, next_run_at)
VALUES (?, ?, ?, ?, ?) RETURNING id, runbook_id, version_id, environment_id, cron, next_run_at, enabled, last_fired_at, created_at
`

type CreateRunbookScheduleParams struct {
	RunbookID     int64         `json:"runbook_id"`
	VersionID     sql.NullInt64 `json:"version_id"`
	EnvironmentID int64         `json:"environment_id"`
	Cron          string        `json:"cron"`
	NextRunAt     int64         `json:"next_run_at"`
}

func (q *Queries) CreateRunbookSchedule(ctx context.Context, arg CreateRunbookScheduleParams) (RunbookSchedule, error) {
	row := q.db.QueryRowContext(ctx, createRunbookSchedule,
		arg.RunbookID,
		arg.VersionID,
		arg.EnvironmentID,
		arg.Cron,
		arg.NextRunAt,
	)
	var i RunbookSchedule
	err := row.Scan(
		&i.ID,
		&i.RunbookID,
		&i.VersionID,
		&i.EnvironmentID,
		&i.Cron,
		&i.NextRunAt,
		&i.Enabled,
		&i.LastFiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRunbookVersion = `-- name: CreateRunbookVersion :one
INSERT INTO runbook_versions (runbook_id, version, release_id)
VALUES (?, ?, ?) RETURNING id, runbook_id, version, release_id, created_at
`

type CreateRunbookVersionParams struct {
	RunbookID int64 `json:"runbook_id"`
	Version   int64 `json:"version"`
	ReleaseID int64 `json:"release_id"`
}

func (q *Queries) CreateRunbookVersion(ctx context.Context, arg CreateRunbookVersionParams) (RunbookVersion, error) {
	row := q.db.QueryRowContext(ctx, createRunbookVersion, arg.RunbookID, arg.Version, arg.ReleaseID)
	var i RunbookVersion
	err := row.Scan(
		&i.ID,
		&i.RunbookID,
		&i.Version,
		&i.ReleaseID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProjectRunbookExecutions = `-- name: DeleteProjectRunbookExecutions :exec
DELETE FROM runbook_executions WHERE runbook_version_id IN (
    SELECT v.id FROM runbook_versions v
    JOIN runbooks b ON b.id = v.runbook_id WHERE b.project_id = ?
)
`

func (q *Queries) DeleteProjectRunbookExecutions(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectRunbookExecutions, projectID)
	return err
}

const deleteProjectRunbookReleases = `-- name: DeleteProjectRunbookReleases :exec
DELETE FROM releases WHERE project_id = ? AND kind = 'runbook'
`

func (q *Queries) DeleteProjectRunbookReleases(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectRunbookReleases, projectID)
	return err
}

const deleteProjectRunbookSchedules = `-- name: DeleteProjectRunbookSchedules :exec
DELETE FROM runbook_schedules WHERE runbook_id IN (
    SELECT id FROM runbooks WHERE project_id = ?
)
`

func (q *Queries) DeleteProjectRunbookSchedules(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectRunbookSchedules, projectID)
	return err
}

const deleteProjectRunbookVersions = `-- name: DeleteProjectRunbookVersions :exec
DELETE FROM runbook_versions WHERE runbook_id IN (
    SELECT id FROM runbooks WHERE project_id = ?
)
`

func (q *Queries) DeleteProjectRunbookVersions(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectRunbookVersions, projectID)
	return err
}

const deleteRunbookDispatches = `-- name: DeleteRunbookDispatches :exec
DELETE FROM deployment_dispatches WHERE deployment_id = ?
`

func (q *Queries) DeleteRunbookDispatches(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRunbookDispatches, deploymentID)
	return err
}

const deleteRunbookLogScopes = `-- name: DeleteRunbookLogScopes :exec
DELETE FROM deployment_log_scopes WHERE deployment_id = ?
`

func (q *Queries) DeleteRunbookLogScopes(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRunbookLogScopes, deploymentID)
	return err
}

const deleteRunbookRemoteClaim = `-- name: DeleteRunbookRemoteClaim :exec
DELETE FROM remote_deployment_claims WHERE deployment_id = ?
`

func (q *Queries) DeleteRunbookRemoteClaim(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRunbookRemoteClaim, deploymentID)
	return err
}

const deleteRunbookRemoteStepLogSequences = `-- name: DeleteRunbookRemoteStepLogSequences :exec
DELETE FROM remote_step_log_sequences WHERE deployment_id = ?
`

func (q *Queries) DeleteRunbookRemoteStepLogSequences(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRunbookRemoteStepLogSequences, deploymentID)
	return err
}

const deleteRunbookRemoteStepRuns = `-- name: DeleteRunbookRemoteStepRuns :exec
DELETE FROM remote_step_runs WHERE deployment_id = ?
`

func (q *Queries) DeleteRunbookRemoteStepRuns(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRunbookRemoteStepRuns, deploymentID)
	return err
}

const deleteRunbookStepAttempts = `-- name: DeleteRunbookStepAttempts :exec
DELETE FROM deployment_step_attempts WHERE deployment_id = ?
`

func (q *Queries) DeleteRunbookStepAttempts(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRunbookStepAttempts, deploymentID)
	return err
}

const deleteRunbookStepSelectors = `-- name: DeleteRunbookStepSelectors :exec
DELETE FROM deployment_step_selectors WHERE deployment_id = ?
`

func (q *Queries) DeleteRunbookStepSelectors(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRunbookStepSelectors, deploymentID)
	return err
}

const deleteRunbookStepSource = `-- name: DeleteRunbookStepSource :exec
DELETE FROM deployment_step_sources WHERE deployment_id = ?
`

func (q *Queries) DeleteRunbookStepSource(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRunbookStepSource, deploymentID)
	return err
}

const deleteRunbookSteps = `-- name: DeleteRunbookSteps :exec
DELETE FROM deployment_steps WHERE deployment_id = ?
`

func (q *Queries) DeleteRunbookSteps(ctx context.Context, deploymentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRunbookSteps, deploymentID)
	return err
}

const disableRunbookSchedule = `-- name: DisableRunbookSchedule :exec
UPDATE runbook_schedules SET enabled = 0 WHERE id = ?
`

func (q *Queries) DisableRunbookSchedule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, disableRunbookSchedule, id)
	return err
}

const getLatestRunbookVersion = `-- name: GetLatestRunbookVersion :one
SELECT id, runbook_id, version, release_id, created_at FROM runbook_versions WHERE runbook_id = ?
ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetLatestRunbookVersion(ctx context.Context, runbookID int64) (RunbookVersion, error) {
	row := q.db.QueryRowContext(ctx, getLatestRunbookVersion, runbookID)
	var i RunbookVersion
	err := row.Scan(
		&i.ID,
		&i.RunbookID,
		&i.Version,
		&i.ReleaseID,
		&i.CreatedAt,
	)
	return i, err
}

const getRunbook = `-- name: GetRunbook :one
SELECT id, project_id, name, description, created_at FROM runbooks WHERE id = ? AND project_id = ?
`

type GetRunbookParams struct {
	ID        int64 `json:"id"`
	ProjectID int64 `json:"project_id"`
}

func (q *Queries) GetRunbook(ctx context.Context, arg GetRunbookParams) (Runbook, error) {
	row := q.db.QueryRowContext(ctx, getRunbook, arg.ID, arg.ProjectID)
	var i Runbook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getRunbookByID = `-- name: GetRunbookByID :one
SELECT id, project_id, name, description, created_at FROM runbooks WHERE id = ?
`

func (q *Queries) GetRunbookByID(ctx context.Context, id int64) (Runbook, error) {
	row := q.db.QueryRowContext(ctx, getRunbookByID, id)
	var i Runbook
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getRunbookExecution = `-- name: GetRunbookExecution :one
SELECT x.id, x.runbook_version_id, x.deployment_id, x.actor_user_id, x.schedule_id, x.created_at, d.environment_id, d.status, d.started_at, d.finished_at,
    v.runbook_id, v.version, b.project_id, b.name AS runbook_name,
    e.name AS environment_name
FROM runbook_executions x
JOIN runbook_versions v ON v.id = x.runbook_version_id
JOIN runbooks b ON b.id = v.runbook_id
JOIN deployments d ON d.id = x.deployment_id
JOIN environments e ON e.id = d.environment_id
WHERE x.id = ? AND b.project_id = ?
`

type GetRunbookExecutionParams struct {
	ID        int64 `json:"id"`
	ProjectID int64 `json:"project_id"`
}

type GetRunbookExecutionRow struct {
	ID               int64         `json:"id"`
	RunbookVersionID int64         `json:"runbook_version_id"`
	DeploymentID     int64         `json:"deployment_id"`
	ActorUserID      sql.NullInt64 `json:"actor_user_id"`
	ScheduleID       sql.NullInt64 `json:"schedule_id"`
	CreatedAt        int64         `json:"created_at"`
	EnvironmentID    int64         `json:"environment_id"`
	Status           string        `json:"status"`
	StartedAt        sql.NullInt64 `json:"started_at"`
	FinishedAt       sql.NullInt64 `json:"finished_at"`
	RunbookID        int64         `json:"runbook_id"`
	Version          int64         `json:"version"`
	ProjectID        int64         `json:"project_id"`
	RunbookName      string        `json:"runbook_name"`
	EnvironmentName  string        `json:"environment_name"`
}

func (q *Queries) GetRunbookExecution(ctx context.Context, arg GetRunbookExecutionParams) (GetRunbookExecutionRow, error) {
	row := q.db.QueryRowContext(ctx, getRunbookExecution, arg.ID, arg.ProjectID)
	var i GetRunbookExecutionRow
	err := row.Scan(
		&i.ID,
		&i.RunbookVersionID,
		&i.DeploymentID,
		&i.ActorUserID,
		&i.ScheduleID,
		&i.CreatedAt,
		&i.EnvironmentID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RunbookID,
		&i.Version,
		&i.ProjectID,
		&i.RunbookName,
		&i.EnvironmentName,
	)
	return i, err
}

const getRunbookExecutionByDeployment = `-- name: GetRunbookExecutionByDeployment :one
SELECT x.id, x.runbook_version_id, x.deployment_id, x.actor_user_id, x.schedule_id, x.created_at, v.runbook_id, b.project_id
FROM runbook_executions x
JOIN runbook_versions v ON v.id = x.runbook_version_id
JOIN runbooks b ON b.id = v.runbook_id
WHERE x.deployment_id = ?
`

type GetRunbookExecutionByDeploymentRow struct {
	ID               int64         `json:"id"`
	RunbookVersionID int64         `json:"runbook_version_id"`
	DeploymentID     int64         `json:"deployment_id"`
	ActorUserID      sql.NullInt64 `json:"actor_user_id"`
	ScheduleID       sql.NullInt64 `json:"schedule_id"`
	CreatedAt        int64         `json:"created_at"`
	RunbookID        int64         `json:"runbook_id"`
	ProjectID        int64         `json:"project_id"`
}

func (q *Queries) GetRunbookExecutionByDeployment(ctx context.Context, deploymentID int64) (GetRunbookExecutionByDeploymentRow, error) {
	row := q.db.QueryRowContext(ctx, getRunbookExecutionByDeployment, deploymentID)
	var i GetRunbookExecutionByDeploymentRow
	err := row.Scan(
		&i.ID,
		&i.RunbookVersionID,
		&i.DeploymentID,
		&i.ActorUserID,
		&i.ScheduleID,
		&i.CreatedAt,
		&i.RunbookID,
		&i.ProjectID,
	)
	return i, err
}

const getRunbookSchedule = `-- name: GetRunbookSchedule :one
SELECT id, runbook_id, version_id, environment_id, cron, next_run_at, enabled, last_fired_at, created_at FROM runbook_schedules WHERE id = ? AND runbook_id = ?
`

type GetRunbookScheduleParams struct {
	ID        int64 `json:"id"`
	RunbookID int64 `json:"runbook_id"`
}

func (q *Queries) GetRunbookSchedule(ctx context.Context, arg GetRunbookScheduleParams) (RunbookSchedule, error) {
	row := q.db.QueryRowContext(ctx, getRunbookSchedule, arg.ID, arg.RunbookID)
	var i RunbookSchedule
	err := row.Scan(
		&i.ID,
		&i.RunbookID,
		&i.VersionID,
		&i.EnvironmentID,
		&i.Cron,
		&i.NextRunAt,
		&i.Enabled,
		&i.LastFiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRunbookVersion = `-- name: GetRunbookVersion :one
SELECT id, runbook_id, version, release_id, created_at FROM runbook_versions WHERE id = ? AND runbook_id = ?
`

type GetRunbookVersionParams struct {
	ID        int64 `json:"id"`
	RunbookID int64 `json:"runbook_id"`
}

func (q *Queries) GetRunbookVersion(ctx context.Context, arg GetRunbookVersionParams) (RunbookVersion, error) {
	row := q.db.QueryRowContext(ctx, getRunbookVersion, arg.ID, arg.RunbookID)
	var i RunbookVersion
	err := row.Scan(
		&i.ID,
		&i.RunbookID,
		&i.Version,
		&i.ReleaseID,
		&i.CreatedAt,
	)
	return i, err
}

const hasActiveProjectRunbookExecution = `-- name: HasActiveProjectRunbookExecution :one
SELECT CASE WHEN EXISTS (
    SELECT 1 FROM runbook_executions x
    JOIN runbook_versions v ON v.id = x.runbook_version_id
    JOIN runbooks b ON b.id = v.runbook_id
    JOIN deployments d ON d.id = x.deployment_id
    WHERE b.project_id = ?
      AND (d.status IN ('pending', 'running', 'pending_approval')
        OR EXISTS (SELECT 1 FROM remote_deployment_claims c
                   WHERE c.deployment_id = d.id
                     AND c.state IN ('lost', 'cancel_unconfirmed'))
        OR EXISTS (SELECT 1 FROM remote_step_runs s
                   WHERE s.deployment_id = d.id
                     AND s.state IN ('lost', 'cancel_unconfirmed')))
) THEN 1 ELSE 0 END
`

func (q *Queries) HasActiveProjectRunbookExecution(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasActiveProjectRunbookExecution, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const hasActiveRunbookScheduleExecution = `-- name: HasActiveRunbookScheduleExecution :one
SELECT CASE WHEN EXISTS (
    SELECT 1 FROM runbook_executions x
    JOIN deployments d ON d.id = x.deployment_id
    WHERE x.schedule_id = ?
      AND (d.status IN ('pending', 'running', 'pending_approval')
        OR EXISTS (SELECT 1 FROM remote_deployment_claims c
                   WHERE c.deployment_id = d.id
                     AND c.state IN ('lost', 'cancel_unconfirmed'))
        OR EXISTS (SELECT 1 FROM remote_step_runs s
                   WHERE s.deployment_id = d.id
                     AND s.state IN ('lost', 'cancel_unconfirmed')))
) THEN 1 ELSE 0 END
`

func (q *Queries) HasActiveRunbookScheduleExecution(ctx context.Context, scheduleID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasActiveRunbookScheduleExecution, scheduleID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const hasUnconfirmedRunbookRemoteOutcome = `-- name: HasUnconfirmedRunbookRemoteOutcome :one
SELECT CASE WHEN EXISTS (
    SELECT 1 FROM remote_deployment_claims
    WHERE remote_deployment_claims.deployment_id = ?1
      AND remote_deployment_claims.state IN ('lost', 'cancel_unconfirmed')
) OR EXISTS (
    SELECT 1 FROM remote_step_runs
    WHERE remote_step_runs.deployment_id = ?1
      AND remote_step_runs.state IN ('lost', 'cancel_unconfirmed')
) THEN 1 ELSE 0 END
`

func (q *Queries) HasUnconfirmedRunbookRemoteOutcome(ctx context.Context, sourceDeploymentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasUnconfirmedRunbookRemoteOutcome, sourceDeploymentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listDueRunbookSchedules = `-- name: ListDueRunbookSchedules :many
SELECT id, runbook_id, version_id, environment_id, cron, next_run_at, enabled, last_fired_at, created_at FROM runbook_schedules WHERE enabled = 1 AND next_run_at <= ?
ORDER BY next_run_at, id
`

func (q *Queries) ListDueRunbookSchedules(ctx context.Context, nextRunAt int64) ([]RunbookSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listDueRunbookSchedules, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunbookSchedule
	for rows.Next() {
		var i RunbookSchedule
		if err := rows.Scan(
			&i.ID,
			&i.RunbookID,
			&i.VersionID,
			&i.EnvironmentID,
			&i.Cron,
			&i.NextRunAt,
			&i.Enabled,
			&i.LastFiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectRunbookDeploymentIDs = `-- name: ListProjectRunbookDeploymentIDs :many
SELECT x.deployment_id FROM runbook_executions x
JOIN runbook_versions v ON v.id = x.runbook_version_id
JOIN runbooks b ON b.id = v.runbook_id
WHERE b.project_id = ?
`

func (q *Queries) ListProjectRunbookDeploymentIDs(ctx context.Context, projectID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listProjectRunbookDeploymentIDs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var deployment_id int64
		if err := rows.Scan(&deployment_id); err != nil {
			return nil, err
		}
		items = append(items, deployment_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunbookExecutions = `-- name: ListRunbookExecutions :many
SELECT x.id, x.runbook_version_id, x.deployment_id, x.actor_user_id, x.schedule_id, x.created_at, d.environment_id, d.status, d.started_at, d.finished_at,
    v.runbook_id, v.version, b.project_id, b.name AS runbook_name,
    e.name AS environment_name
FROM runbook_executions x
JOIN runbook_versions v ON v.id = x.runbook_version_id
JOIN runbooks b ON b.id = v.runbook_id
JOIN deployments d ON d.id = x.deployment_id
JOIN environments e ON e.id = d.environment_id
WHERE b.project_id = ? ORDER BY x.id DESC
LIMIT ? OFFSET ?
`

type ListRunbookExecutionsParams struct {
	ProjectID int64 `json:"project_id"`
	Limit     int64 `json:"limit"`
	Offset    int64 `json:"offset"`
}

type ListRunbookExecutionsRow struct {
	ID               int64         `json:"id"`
	RunbookVersionID int64         `json:"runbook_version_id"`
	DeploymentID     int64         `json:"deployment_id"`
	ActorUserID      sql.NullInt64 `json:"actor_user_id"`
	ScheduleID       sql.NullInt64 `json:"schedule_id"`
	CreatedAt        int64         `json:"created_at"`
	EnvironmentID    int64         `json:"environment_id"`
	Status           string        `json:"status"`
	StartedAt        sql.NullInt64 `json:"started_at"`
	FinishedAt       sql.NullInt64 `json:"finished_at"`
	RunbookID        int64         `json:"runbook_id"`
	Version          int64         `json:"version"`
	ProjectID        int64         `json:"project_id"`
	RunbookName      string        `json:"runbook_name"`
	EnvironmentName  string        `json:"environment_name"`
}

func (q *Queries) ListRunbookExecutions(ctx context.Context, arg ListRunbookExecutionsParams) ([]ListRunbookExecutionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunbookExecutions, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunbookExecutionsRow
	for rows.Next() {
		var i ListRunbookExecutionsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunbookVersionID,
			&i.DeploymentID,
			&i.ActorUserID,
			&i.ScheduleID,
			&i.CreatedAt,
			&i.EnvironmentID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.RunbookID,
			&i.Version,
			&i.ProjectID,
			&i.RunbookName,
			&i.EnvironmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunbookSchedules = `-- name: ListRunbookSchedules :many
SELECT id, runbook_id, version_id, environment_id, cron, next_run_at, enabled, last_fired_at, created_at FROM runbook_schedules WHERE runbook_id = ? ORDER BY id DESC
`

func (q *Queries) ListRunbookSchedules(ctx context.Context, runbookID int64) ([]RunbookSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listRunbookSchedules, runbookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunbookSchedule
	for rows.Next() {
		var i RunbookSchedule
		if err := rows.Scan(
			&i.ID,
			&i.RunbookID,
			&i.VersionID,
			&i.EnvironmentID,
			&i.Cron,
			&i.NextRunAt,
			&i.Enabled,
			&i.LastFiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunbookVersions = `-- name: ListRunbookVersions :many
SELECT id, runbook_id, version, release_id, created_at FROM runbook_versions WHERE runbook_id = ? ORDER BY version DESC
`

func (q *Queries) ListRunbookVersions(ctx context.Context, runbookID int64) ([]RunbookVersion, error) {
	rows, err := q.db.QueryContext(ctx, listRunbookVersions, runbookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunbookVersion
	for rows.Next() {
		var i RunbookVersion
		if err := rows.Scan(
			&i.ID,
			&i.RunbookID,
			&i.Version,
			&i.ReleaseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunbooks = `-- name: ListRunbooks :many
SELECT id, project_id, name, description, created_at FROM runbooks WHERE project_id = ? ORDER BY name, id
`

func (q *Queries) ListRunbooks(ctx context.Context, projectID int64) ([]Runbook, error) {
	rows, err := q.db.QueryContext(ctx, listRunbooks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Runbook
	for rows.Next() {
		var i Runbook
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRunbookDeploymentKind = `-- name: SetRunbookDeploymentKind :exec
UPDATE deployments SET kind = 'runbook' WHERE id = ?
`

func (q *Queries) SetRunbookDeploymentKind(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setRunbookDeploymentKind, id)
	return err
}

const setRunbookReleaseKind = `-- name: SetRunbookReleaseKind :exec
UPDATE releases SET kind = 'runbook' WHERE id = ?
`

func (q *Queries) SetRunbookReleaseKind(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setRunbookReleaseKind, id)
	return err
}

const skipRunbookSchedule = `-- name: SkipRunbookSchedule :execrows
UPDATE runbook_schedules SET next_run_at = ?
WHERE id = ? AND enabled = 1 AND next_run_at <= ?
`

type SkipRunbookScheduleParams struct {
	NextRunAt   int64 `json:"next_run_at"`
	ID          int64 `json:"id"`
	NextRunAt_2 int64 `json:"next_run_at_2"`
}

func (q *Queries) SkipRunbookSchedule(ctx context.Context, arg SkipRunbookScheduleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, skipRunbookSchedule, arg.NextRunAt, arg.ID, arg.NextRunAt_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
