// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, csrf_token, expires_at, ip_address, user_agent) VALUES (?, ?, ?, ?, ?, ?) RETURNING id, user_id, csrf_token, created_at, expires_at, ip_address, user_agent
`

type CreateSessionParams struct {
	ID        string         `json:"id"`
	UserID    int64          `json:"user_id"`
	CsrfToken string         `json:"csrf_token"`
	ExpiresAt int64          `json:"expires_at"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CsrfToken,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.user_id, s.csrf_token, s.created_at, s.expires_at, s.ip_address, s.user_agent, u.email, u.name, u.role FROM sessions s JOIN users u ON s.user_id = u.id WHERE s.id = ? AND s.expires_at > ?
`

type GetSessionParams struct {
	ID        string `json:"id"`
	ExpiresAt int64  `json:"expires_at"`
}

type GetSessionRow struct {
	ID        string         `json:"id"`
	UserID    int64          `json:"user_id"`
	CsrfToken string         `json:"csrf_token"`
	CreatedAt int64          `json:"created_at"`
	ExpiresAt int64          `json:"expires_at"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	Role      string         `json:"role"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.ID, arg.ExpiresAt)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Email,
		&i.Name,
		&i.Role,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET expires_at = ? WHERE id = ?
`

type TouchSessionParams struct {
	ExpiresAt int64  `json:"expires_at"`
	ID        string `json:"id"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.ExpiresAt, arg.ID)
	return err
}
