// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: step_placement.sql

package db

import (
	"context"
	"strings"
)

const addStepAgentSelector = `-- name: AddStepAgentSelector :exec
INSERT INTO step_agent_selectors (step_id, label) VALUES (?, ?)
`

type AddStepAgentSelectorParams struct {
	StepID int64  `json:"step_id"`
	Label  string `json:"label"`
}

func (q *Queries) AddStepAgentSelector(ctx context.Context, arg AddStepAgentSelectorParams) error {
	_, err := q.db.ExecContext(ctx, addStepAgentSelector, arg.StepID, arg.Label)
	return err
}

const addTemplateAgentSelector = `-- name: AddTemplateAgentSelector :exec
INSERT INTO step_template_agent_selectors (template_id, label) VALUES (?, ?)
`

type AddTemplateAgentSelectorParams struct {
	TemplateID int64  `json:"template_id"`
	Label      string `json:"label"`
}

func (q *Queries) AddTemplateAgentSelector(ctx context.Context, arg AddTemplateAgentSelectorParams) error {
	_, err := q.db.ExecContext(ctx, addTemplateAgentSelector, arg.TemplateID, arg.Label)
	return err
}

const addTemplateVersionAgentSelector = `-- name: AddTemplateVersionAgentSelector :exec
INSERT INTO step_template_version_agent_selectors (template_version_id, label) VALUES (?, ?)
`

type AddTemplateVersionAgentSelectorParams struct {
	TemplateVersionID int64  `json:"template_version_id"`
	Label             string `json:"label"`
}

func (q *Queries) AddTemplateVersionAgentSelector(ctx context.Context, arg AddTemplateVersionAgentSelectorParams) error {
	_, err := q.db.ExecContext(ctx, addTemplateVersionAgentSelector, arg.TemplateVersionID, arg.Label)
	return err
}

const deleteStepAgentSelectors = `-- name: DeleteStepAgentSelectors :exec
DELETE FROM step_agent_selectors WHERE step_id = ?
`

func (q *Queries) DeleteStepAgentSelectors(ctx context.Context, stepID int64) error {
	_, err := q.db.ExecContext(ctx, deleteStepAgentSelectors, stepID)
	return err
}

const deleteTemplateAgentSelectors = `-- name: DeleteTemplateAgentSelectors :exec
DELETE FROM step_template_agent_selectors WHERE template_id = ?
`

func (q *Queries) DeleteTemplateAgentSelectors(ctx context.Context, templateID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateAgentSelectors, templateID)
	return err
}

const listStepAgentSelectors = `-- name: ListStepAgentSelectors :many
SELECT label FROM step_agent_selectors WHERE step_id = ? ORDER BY label
`

func (q *Queries) ListStepAgentSelectors(ctx context.Context, stepID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listStepAgentSelectors, stepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepAgentSelectorsByStepIDs = `-- name: ListStepAgentSelectorsByStepIDs :many
SELECT step_id, label FROM step_agent_selectors
WHERE step_id IN (/*SLICE:step_ids*/?) ORDER BY step_id, label
`

func (q *Queries) ListStepAgentSelectorsByStepIDs(ctx context.Context, stepIds []int64) ([]StepAgentSelector, error) {
	query := listStepAgentSelectorsByStepIDs
	var queryParams []interface{}
	if len(stepIds) > 0 {
		for _, v := range stepIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:step_ids*/?", strings.Repeat(",?", len(stepIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:step_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StepAgentSelector
	for rows.Next() {
		var i StepAgentSelector
		if err := rows.Scan(&i.StepID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateAgentSelectors = `-- name: ListTemplateAgentSelectors :many
SELECT label FROM step_template_agent_selectors WHERE template_id = ? ORDER BY label
`

func (q *Queries) ListTemplateAgentSelectors(ctx context.Context, templateID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateAgentSelectors, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateAgentSelectorsByTemplateIDs = `-- name: ListTemplateAgentSelectorsByTemplateIDs :many
SELECT template_id, label FROM step_template_agent_selectors
WHERE template_id IN (/*SLICE:template_ids*/?) ORDER BY template_id, label
`

func (q *Queries) ListTemplateAgentSelectorsByTemplateIDs(ctx context.Context, templateIds []int64) ([]StepTemplateAgentSelector, error) {
	query := listTemplateAgentSelectorsByTemplateIDs
	var queryParams []interface{}
	if len(templateIds) > 0 {
		for _, v := range templateIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:template_ids*/?", strings.Repeat(",?", len(templateIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:template_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StepTemplateAgentSelector
	for rows.Next() {
		var i StepTemplateAgentSelector
		if err := rows.Scan(&i.TemplateID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateVersionAgentSelectors = `-- name: ListTemplateVersionAgentSelectors :many
SELECT label FROM step_template_version_agent_selectors WHERE template_version_id = ? ORDER BY label
`

func (q *Queries) ListTemplateVersionAgentSelectors(ctx context.Context, templateVersionID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateVersionAgentSelectors, templateVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateVersionAgentSelectorsByVersionIDs = `-- name: ListTemplateVersionAgentSelectorsByVersionIDs :many
SELECT template_version_id, label FROM step_template_version_agent_selectors
WHERE template_version_id IN (/*SLICE:version_ids*/?)
ORDER BY template_version_id, label
`

func (q *Queries) ListTemplateVersionAgentSelectorsByVersionIDs(ctx context.Context, versionIds []int64) ([]StepTemplateVersionAgentSelector, error) {
	query := listTemplateVersionAgentSelectorsByVersionIDs
	var queryParams []interface{}
	if len(versionIds) > 0 {
		for _, v := range versionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:version_ids*/?", strings.Repeat(",?", len(versionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:version_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StepTemplateVersionAgentSelector
	for rows.Next() {
		var i StepTemplateVersionAgentSelector
		if err := rows.Scan(&i.TemplateVersionID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStepExecutionTarget = `-- name: SetStepExecutionTarget :execrows
UPDATE steps SET execution_target = ? WHERE id = ?
`

type SetStepExecutionTargetParams struct {
	ExecutionTarget string `json:"execution_target"`
	ID              int64  `json:"id"`
}

func (q *Queries) SetStepExecutionTarget(ctx context.Context, arg SetStepExecutionTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setStepExecutionTarget, arg.ExecutionTarget, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTemplateExecutionTarget = `-- name: SetTemplateExecutionTarget :execrows
UPDATE step_templates SET execution_target = ? WHERE id = ?
`

type SetTemplateExecutionTargetParams struct {
	ExecutionTarget string `json:"execution_target"`
	ID              int64  `json:"id"`
}

func (q *Queries) SetTemplateExecutionTarget(ctx context.Context, arg SetTemplateExecutionTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTemplateExecutionTarget, arg.ExecutionTarget, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTemplateVersionExecutionTarget = `-- name: SetTemplateVersionExecutionTarget :execrows
UPDATE step_template_versions SET execution_target = ? WHERE id = ?
`

type SetTemplateVersionExecutionTargetParams struct {
	ExecutionTarget string `json:"execution_target"`
	ID              int64  `json:"id"`
}

func (q *Queries) SetTemplateVersionExecutionTarget(ctx context.Context, arg SetTemplateVersionExecutionTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTemplateVersionExecutionTarget, arg.ExecutionTarget, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
