// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: step_placement.sql

package db

import (
	"context"
)

const addStepAgentSelector = `-- name: AddStepAgentSelector :exec
INSERT INTO step_agent_selectors (step_id, label) VALUES (?, ?)
`

type AddStepAgentSelectorParams struct {
	StepID int64  `json:"step_id"`
	Label  string `json:"label"`
}

func (q *Queries) AddStepAgentSelector(ctx context.Context, arg AddStepAgentSelectorParams) error {
	_, err := q.db.ExecContext(ctx, addStepAgentSelector, arg.StepID, arg.Label)
	return err
}

const addTemplateAgentSelector = `-- name: AddTemplateAgentSelector :exec
INSERT INTO step_template_agent_selectors (template_id, label) VALUES (?, ?)
`

type AddTemplateAgentSelectorParams struct {
	TemplateID int64  `json:"template_id"`
	Label      string `json:"label"`
}

func (q *Queries) AddTemplateAgentSelector(ctx context.Context, arg AddTemplateAgentSelectorParams) error {
	_, err := q.db.ExecContext(ctx, addTemplateAgentSelector, arg.TemplateID, arg.Label)
	return err
}

const addTemplateVersionAgentSelector = `-- name: AddTemplateVersionAgentSelector :exec
INSERT INTO step_template_version_agent_selectors (template_version_id, label) VALUES (?, ?)
`

type AddTemplateVersionAgentSelectorParams struct {
	TemplateVersionID int64  `json:"template_version_id"`
	Label             string `json:"label"`
}

func (q *Queries) AddTemplateVersionAgentSelector(ctx context.Context, arg AddTemplateVersionAgentSelectorParams) error {
	_, err := q.db.ExecContext(ctx, addTemplateVersionAgentSelector, arg.TemplateVersionID, arg.Label)
	return err
}

const deleteStepAgentSelectors = `-- name: DeleteStepAgentSelectors :exec
DELETE FROM step_agent_selectors WHERE step_id = ?
`

func (q *Queries) DeleteStepAgentSelectors(ctx context.Context, stepID int64) error {
	_, err := q.db.ExecContext(ctx, deleteStepAgentSelectors, stepID)
	return err
}

const deleteTemplateAgentSelectors = `-- name: DeleteTemplateAgentSelectors :exec
DELETE FROM step_template_agent_selectors WHERE template_id = ?
`

func (q *Queries) DeleteTemplateAgentSelectors(ctx context.Context, templateID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateAgentSelectors, templateID)
	return err
}

const listStepAgentSelectors = `-- name: ListStepAgentSelectors :many
SELECT label FROM step_agent_selectors WHERE step_id = ? ORDER BY label
`

func (q *Queries) ListStepAgentSelectors(ctx context.Context, stepID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listStepAgentSelectors, stepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateAgentSelectors = `-- name: ListTemplateAgentSelectors :many
SELECT label FROM step_template_agent_selectors WHERE template_id = ? ORDER BY label
`

func (q *Queries) ListTemplateAgentSelectors(ctx context.Context, templateID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateAgentSelectors, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateVersionAgentSelectors = `-- name: ListTemplateVersionAgentSelectors :many
SELECT label FROM step_template_version_agent_selectors WHERE template_version_id = ? ORDER BY label
`

func (q *Queries) ListTemplateVersionAgentSelectors(ctx context.Context, templateVersionID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTemplateVersionAgentSelectors, templateVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStepExecutionTarget = `-- name: SetStepExecutionTarget :execrows
UPDATE steps SET execution_target = ? WHERE id = ?
`

type SetStepExecutionTargetParams struct {
	ExecutionTarget string `json:"execution_target"`
	ID              int64  `json:"id"`
}

func (q *Queries) SetStepExecutionTarget(ctx context.Context, arg SetStepExecutionTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setStepExecutionTarget, arg.ExecutionTarget, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTemplateExecutionTarget = `-- name: SetTemplateExecutionTarget :execrows
UPDATE step_templates SET execution_target = ? WHERE id = ?
`

type SetTemplateExecutionTargetParams struct {
	ExecutionTarget string `json:"execution_target"`
	ID              int64  `json:"id"`
}

func (q *Queries) SetTemplateExecutionTarget(ctx context.Context, arg SetTemplateExecutionTargetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTemplateExecutionTarget, arg.ExecutionTarget, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
